### ISSUE TITLE
Return / Debit note: Unable to create Return / Debit note from Purchase Invoice create button shows error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#102]
### Information about bug

![image](https://github.com/user-attachments/assets/10d319ef-dfc0-479e-93c1-16c6257716ad)

### Module

accounts

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 1901, in make_debit_note
    return make_return_doc("Purchase Invoice", source_name, target_doc)
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 652, in make_return_doc
    doclist = get_mapped_doc(
  File "apps/frappe/frappe/model/mapper.py", line 152, in get_mapped_doc
    map_child_doc(source_d, target_doc, table_map, source_doc)
  File "apps/frappe/frappe/model/mapper.py", line 268, in map_child_doc
    map_doc(source_d, target_d, table_map, source_parent)
  File "apps/frappe/frappe/model/mapper.py", line 177, in map_doc
    table_map["postprocess"](source_doc, target_doc, source_parent)
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 529, in update_item
    returned_qty_map = get_returned_qty_map_for_row(
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 296, in get_returned_qty_map_for_row
    data = frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPurchase Invoice.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabPurchase Invoice"."modified" DESC
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.accounts.doctype.purchase_invoice.purchase_invoice.make_debit_note",
		"source_name": "ACC-PINV-2024-00001",
		"args": null,
		"selected_children": "{}"
	},
	"freeze": true,
	"freeze_message": "",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.make_mapped_doc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPurchase Invoice.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 5:     order by \\\"tabPurchase Invoice\\\".\\\"modified\\\" DESC\\n                     ^\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closed...
