### ISSUE TITLE
While navigating to Journal entry doctype from asset facing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#103]
### Information about bug

While navigating to Journal entry doctype from asset facing error,  we can create journal entry from asset but error is showing in doctype list 
![image](https://github.com/user-attachments/assets/5d0fdbaa-71d1-4e7f-b5e7-9a4a46989302)
![image](https://github.com/user-attachments/assets/1a3c7fef-0e12-4fcb-8c99-bcef9e7d7f8c)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
List/Journal Entry/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 69, in get_count
    count = frappe.db.sql(f"""select count(*) from ( {partial_query} ) p""")[0][0]
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "distinct"
LINE 1: select count(*) from ( select distinct distinct cast("tabJou...
                                               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Journal Entry",
		"filters": "[[\"Journal Entry Account\",\"reference_name\",\"=\",\"ACC-ASS-2024-00003\"]]",
		"fields": "[]",
		"distinct": true,
		"limit": 1001
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_debug_messages": "[\"Syntax error in query:\\nselect count(*) from ( select distinct distinct cast(\\\"tabJournal Entry\\\".name as varchar)\\n\\t\\t\\tfrom \\\"tabJournal Entry\\\" left join \\\"tabJournal Entry Account\\\" on (\\\"tabJournal Entry Account\\\".parenttype = 'Journal Entry' and \\\"tabJournal Entry Account\\\".parent = cast(\\\"tabJournal Entry\\\".name as varchar))\\n\\t\\t\\twhere \\\"tabJournal Entry Account\\\".\\\"reference_name\\\" = 'ACC-ASS-2024-00003'\\n\\t\\t\\t\\n\\t\\t\\t\\n\\t\\t\\tlimit 1001 offset 0 ) p \"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
