### ISSUE TITLE
Stock Entry Submission

### ISSUE THREAD

**Issue by arvind8848** [8848digital/erpnext#106]
### Information about bug

After creating stock entry while submitting, system show error.
![Screenshot 2024-09-30 172644](https://github.com/user-attachments/assets/a83e86f0-009f-4b0e-bc40-e67b4802fc5d)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Stock Entry/MAT-STE-2024-00008
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 245, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1354, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 869, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 75, in make_sl_entries
    future_sle_exists(args, sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1549, in future_sle_exists
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "index"
LINE 2:   from "tabStock Ledger Entry" force index (item_warehouse)
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-STE-2024-00008\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 15:10:07.810864\",\"modified\":\"2024-09-30 15:10:07.810864\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-STE-.YYYY.-\",\"stock_entry_type\":\"Material Transfer for Manufacture\",\"purpose\":\"Material Transfer for Manufacture\",\"add_to_transit\":0,\"work_order\":\"MFG-WO-2024-00001\",\"company\":\"8848 Digital\",\"posting_date\":\"2024-09-30\",\"posting_time\":\"15:10:07.848514\",\"set_posting_time\":0,\"inspection_required\":0,\"apply_putaway_rule\":0,\"from_bom\":1,\"use_multi_level_bom\":1,\"bom_no\":\"BOM-_Test FG Item-001\",\"fg_completed_qty\":40,\"process_loss_percentage\":0,\"process_loss_qty\":0,\"to_warehouse\":\"Work In Progress - 8D\",\"total_outgoing_value\":12000,\"total_incoming_value\":12000,\"value_difference\":0,\"total_additional_costs\":0,\"is_opening\":\"No\",\"per_transferred\":0,\"total_amount\":12000,\"is_return\":0,\"doctype\":\"Stock Entry\",\"items\":[{\"name\":\"gster4g43l\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 15:10:07.810864\",\"modified\":\"2024-09-30 15:10:07.810864\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"s_warehouse\":\"Mumbai  - 8D\",\"t_warehouse\":\"Work In Progress - 8D\",\"item_code\":\"_Test Item\",\"item_name\":\"_Test Item\",\"is_finished_item\":0,\"is_scrap_item\":0,\"description\":\"_Test Item 1\",\"item_group\":\"_Test Item Group\",\"qty\":40,\"transfer_qty\":40,\"retain_sample\":0,\"uom\":\"_Test UOM\",\"stock_uom\":\"_Test UOM\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":100,\"additional_cost\":0,\"valuation_rate\":100,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":4000,\"amount\":4000,\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Adjustment - 8D\",\"cost_center\":\"Main - 8D\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"parent\":\"MAT-STE-2024-00008\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\"},{\"name\":\"gstehvnkdp\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 15:10:07.810864\",\"modified\":\"2024-09-30 15:10:07.810864\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"has_item_scanned\":0,\"s_warehouse\":\"Mumbai  - 8D\",\"t_warehouse\":\"Work In Progress - 8D\",\"item_code\":\"_Test Item Home Desktop 100\",\"item_name\":\"_Test Item Home Desktop 100\",\"is_finished_item\":0,\"is_scrap_item\":0,\"description\":\"_Test Item Home Desktop 100 3\",\"item_group\":\"_Test Item Group Desktops\",\"qty\":80,\"transfer_qty\":80,\"retain_sample\":0,\"uom\":\"_Test UOM 1\",\"stock_uom\":\"_Test UOM 1\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":100,\"additional_cost\":0,\"valuation_rate\":100,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":8000,\"amount\":8000,\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Adjustment - 8D\",\"cost_center\":\"Main - 8D\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"parent\":\"MAT-STE-2024-00008\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\"}],\"additional_costs\":[],\"__last_sync_on\":\"2024-09-30T11:55:06.317Z\",\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
		"action": "Submit"
	},
	"btn": {
		"jQuery37000535178583696178661": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1257,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect item_code, warehouse, count(name) as total_row\\n\\t\\tfrom \\\"tabStock Ledger Entry\\\" force index (item_warehouse)\\n\\t\\twhere\\n\\t\\t\\t(warehouse = 'Mumbai  - 8D'\\n\\t\\t\\t\\tand item_code in ('_Test Item', '_Test Item Home Desktop 100') or warehouse = 'Work In Progress - 8D'\\n\\t\\t\\t\\tand item_code in ('_Test Item', '_Test Item Home Desktop 100'))\\n\\t\\t\\tand timestamp(posting_date, posting_time)\\n\\t\\t\\t\\t>= timestamp(%(posting_date)s, %(posting_time)s)\\n\\t\\t\\tand voucher_no != %(voucher_no)s\\n\\t\\t\\tand is_cancelled = '0'\\n\\t\\tGROUP BY\\n\\t\\t\\titem_code, warehouse {'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2024-00008', 'posting_date': '2024-09-30', 'posting_time': '17:25:10.745284'}\"]"
}
```
```

**Comment by 8848swa** [comment]
Unable to submit material receipt entry
![image](https://github.com/user-attachments/assets/77d2e690-30c5-45a6-8db9-5479a2de83fe)
### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Stock Entry/MAT-STE-2024-00011
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 69, in get_count
    count = frappe.db.sql(f"""select count(*) from ( {partial_query} ) p""")[0][0]
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "distinct"
LINE 1: select count(*) from ( select distinct distinct cast("tabTim...
                                               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Timesheet",
		"filters": "[[\"Timesheet Detail\",\"task\",\"=\",\"TASK-2024-00001\"]]",
		"fields": "[]",
		"distinct": true,
		"limit": 1001
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_debug_messages": "[\"Syntax error in query:\\nselect count(*) from ( select distinct distinct cast(\\\"tabTimesheet\\\".name as varchar)\\n\\t\\t\\tfrom \\\"tabTimesheet\\\" left join \\\"tabTimesheet Detail\\\" on (\\\"tabTimesheet Detail\\\".parenttype = 'Timesheet' and \\\"tabTimesheet Detail\\\".parent = cast(\\\"tabTimesheet\\\".name as varchar))\\n\\t\\t\\twhere \\\"tabTimesheet Detail\\\".\\\"task\\\" = 'TASK-2024-00001'\\n\\t\\t\\t\\n\\t\\t\\t\\n\\t\\t\\tlimit 1001 offset 0 ) p \"]"
}
```

**Comment by hrishikesh8848** [comment]
The stock entry **MAT-STE-2024-00011** is submitted, please check and confirm

**Comment by 8848swa** [comment]
It's working fine hence Closed.
