### ISSUE TITLE
Asset - Not able to view Asset Depreciation Ledger Report

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#113]
### Information about bug

![image](https://github.com/user-attachments/assets/a2c814dd-87ec-4e72-a2b5-a7353becad19)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Asset Depreciation Ledger
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/assets/doctype/asset_capitalization/asset_capitalization.py", line 128, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/assets/doctype/asset_capitalization/asset_capitalization.py", line 431, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 869, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 75, in make_sl_entries
    future_sle_exists(args, sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1549, in future_sle_exists
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "index"
LINE 2:   from "tabStock Ledger Entry" force index (item_warehouse)
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-ASC-2024-00002\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 17:30:25.004378\",\"modified\":\"2024-09-30 17:30:25.004378\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Test_asset1\",\"company\":\"8848 Digital\",\"naming_series\":\"ACC-ASC-.YYYY.-\",\"entry_type\":\"Capitalization\",\"target_item_name\":\"Test_asset1\",\"target_is_fixed_asset\":1,\"target_has_batch_no\":0,\"target_has_serial_no\":0,\"capitalization_method\":\"Choose a WIP composite asset\",\"target_item_code\":\"Test_asset1\",\"target_asset_location\":null,\"target_asset\":\"ACC-ASS-2024-00004\",\"target_asset_name\":\"Test_asset1\",\"target_warehouse\":null,\"target_qty\":1,\"target_stock_uom\":\"Nos\",\"target_batch_no\":null,\"target_serial_no\":\"\",\"finance_book\":null,\"posting_date\":\"2024-09-30\",\"posting_time\":\"17:30:25.031880\",\"set_posting_time\":0,\"amended_from\":null,\"stock_items_total\":0,\"asset_items_total\":50000,\"service_items_total\":0,\"total_value\":50000,\"target_incoming_rate\":50000,\"cost_center\":\"Main - 8D\",\"target_fixed_asset_account\":\"Office Equipments - 8D\",\"doctype\":\"Asset Capitalization\",\"asset_items\":[{\"name\":\"jf3qrfc5e7\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 17:30:25.004378\",\"modified\":\"2024-09-30 17:30:25.004378\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"asset\":\"ACC-ASS-2024-00002\",\"asset_name\":\"Test_asset\",\"finance_book\":null,\"item_code\":\"Test_asset\",\"item_name\":\"Test_asset\",\"current_asset_value\":50000,\"asset_value\":50000,\"cost_center\":\"Main - 8D\",\"fixed_asset_account\":\"Office Equipments - 8D\",\"parent\":\"ACC-ASC-2024-00002\",\"parentfield\":\"asset_items\",\"parenttype\":\"Asset Capitalization\",\"doctype\":\"Asset Capitalization Asset Item\",\"__unsaved\":1}],\"service_items\":[],\"stock_items\":[{\"name\":\"jf3qggs9sf\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 17:30:25.004378\",\"modified\":\"2024-09-30 17:30:25.004378\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"_Test FG Item\",\"item_name\":\"_Test FG Item\",\"warehouse\":\"Stores - 8D\",\"stock_qty\":1,\"stock_uom\":\"_Test UOM\",\"actual_qty\":0,\"valuation_rate\":0,\"amount\":0,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":0,\"serial_no\":\"\",\"batch_no\":null,\"cost_center\":\"Main - 8D\",\"parent\":\"ACC-ASC-2024-00002\",\"parentfield\":\"stock_items\",\"parenttype\":\"Asset Capitalization\",\"doctype\":\"Asset Capitalization Stock Item\",\"__unsaved\":1}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-09-30T12:00:25.737Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370063809730538011711": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1406,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect item_code, warehouse, count(name) as total_row\\n\\t\\tfrom \\\"tabStock Ledger Entry\\\" force index (item_warehouse)\\n\\t\\twhere\\n\\t\\t\\t(warehouse = 'Stores - 8D'\\n\\t\\t\\t\\tand item_code in ('_Test FG Item'))\\n\\t\\t\\tand timestamp(posting_date, posting_time)\\n\\t\\t\\t\\t>= timestamp(%(posting_date)s, %(posting_time)s)\\n\\t\\t\\tand voucher_no != %(voucher_no)s\\n\\t\\t\\tand is_cancelled = '0'\\n\\t\\tGROUP BY\\n\\t\\t\\titem_code, warehouse {'voucher_type': 'Asset Capitalization', 'voucher_no': 'ACC-ASC-2024-00002', 'posting_date': '2024-09-30', 'posting_time': '17:30:27.466863'}\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
