### ISSUE TITLE
Delivery Note Not able to submit

### ISSUE THREAD

**Issue by aasif-patel** [8848digital/erpnext#121]
### Information about bug

![image](https://github.com/user-attachments/assets/a017041d-884e-498d-9542-fafcb3e5648d)

### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Delivery Note/MAT-DN-2024-00005
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 273, in validate
    self.validate_against_stock_reservation_entries()
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 670, in validate_against_stock_reservation_entries
    reserved_warehouses = get_sre_reserved_warehouses_for_voucher(
  File "apps/erpnext/erpnext/stock/doctype/stock_reservation_entry/stock_reservation_entry.py", line 706, in get_sre_reserved_warehouses_for_voucher
    warehouses = query.run(as_list=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...d') AND "voucher_detail_no"='dopcd1ecqt' ORDER BY "creation"
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-DN-.YYYY.-\",\"customer\":\"_Test Customer 3\",\"customer_name\":\"_Test Customer 3\",\"posting_date\":\"2024-10-01\",\"posting_time\":\"12:19:00.334047\",\"set_posting_time\":0,\"company\":\"8848 Digital\",\"is_return\":0,\"issue_credit_note\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":45,\"base_net_total\":45,\"total\":45,\"net_total\":45,\"tax_category\":\"\",\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":45,\"base_rounding_adjustment\":0,\"base_rounded_total\":45,\"base_in_words\":\"\",\"grand_total\":45,\"rounding_adjustment\":0,\"rounded_total\":45,\"in_words\":\"\",\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"company_address\":\"8848 Digital-Billing\",\"company_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"per_billed\":0,\"status\":\"Draft\",\"per_installed\":0,\"per_returned\":0,\"lr_date\":\"2024-10-01\",\"po_no\":\"\",\"amount_eligible_for_commission\":45,\"commission_rate\":0,\"total_commission\":0,\"print_without_amount\":0,\"group_same_items\":0,\"language\":\"en\",\"is_internal_customer\":0,\"customer_group\":\"_Test Customer Group\",\"territory\":\"_Test Territory\",\"doctype\":\"Delivery Note\",\"packed_items\":[],\"pricing_rules\":[],\"items\":[{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"_Test FG Item\",\"item_name\":\"_Test FG Item\",\"description\":\"_Test FG Item 6\",\"item_group\":\"_Test Item Group Desktops\",\"image\":\"\",\"qty\":1,\"stock_uom\":\"_Test UOM\",\"uom\":\"_Test UOM\",\"conversion_factor\":1,\"stock_qty\":1,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":45,\"amount\":45,\"base_rate\":45,\"base_amount\":45,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":45,\"net_amount\":45,\"base_net_rate\":45,\"base_net_amount\":45,\"billed_amt\":0,\"incoming_rate\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - 8D\",\"allow_zero_valuation_rate\":0,\"against_sales_order\":\"SAL-ORD-2024-00012\",\"so_detail\":\"dopcd1ecqt\",\"use_serial_batch_fields\":1,\"actual_batch_qty\":0,\"actual_qty\":0,\"installed_qty\":0,\"item_tax_rate\":\"{}\",\"packed_qty\":0,\"received_qty\":0,\"expense_account\":\"Cost of Goods Sold - 8D\",\"cost_center\":\"Main - 8D\",\"page_break\":0,\"parentfield\":\"items\",\"parenttype\":\"Delivery Note\",\"doctype\":\"Delivery Note Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-delivery-note-jelmlrjskw\",\"name\":\"new-delivery-note-item-dijauewvkd\"}],\"taxes\":[],\"sales_team\":[],\"__islocal\":1,\"__onload\":{\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-delivery-note-jelmlrjskw\",\"__last_sync_on\":\"2024-10-01T06:49:00.730Z\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700406496492512618431": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4708,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidColumnReference",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfor SELECT DISTINCT, ORDER BY expressions must appear in select list\\nLINE 1: ...d') AND \\\"voucher_detail_no\\\"='dopcd1ecqt' ORDER BY \\\"creation\\\"\\n                                                             ^\\n\"]"
}
```

### Module

selling

### Version

"erpnext": "15.34.0",
"frappe": "15.41.0",
"payments": "0.0.1"

### Installation method

manual install

**Comment by aasif-patel** [comment]
Linked with #77

**Comment by nilesh8848** [comment]
https://github.com/8848digital/erpnext/pull/143 resolved

**Comment by aasif-patel** [comment]
Pending as cant able to select serial number for the item on Delivery Note...

**Comment by aasif-patel** [comment]
Tested, Resolved hence closing...
