### ISSUE TITLE
Report:Daily Timesheet Summary 

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#14]
### Information about bug

click on show report , showing an error
![Screenshot from 2024-09-19 15-34-36](https://github.com/user-attachments/assets/82a442bd-52a2-40b2-90d8-f39544772134)

### Module

projects

### Version

ERPNext: v16.0.0-dev (cost_center)

Frappe Framework: v15.40.6 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "16.0.0-dev",
	"frappe": "15.40.6"
}
```
### Route
```
query-report/Daily Timesheet Summary
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/projects/report/daily_timesheet_summary/daily_timesheet_summary.py", line 19, in execute
    data = get_data(conditions, filters)
  File "apps/erpnext/erpnext/projects/report/daily_timesheet_summary/daily_timesheet_summary.py", line 40, in get_data
    time_sheet = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "'2024-09-19'"
LINE 5: ... and "tabTimesheet Detail".from_time >= timestamp('2024-09-1...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 81, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Daily Timesheet Summary",
		"filters": "{\"from_date\":\"2024-09-19\",\"to_date\":\"2024-09-19\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect \\\"tabTimesheet\\\".name, \\\"tabTimesheet\\\".employee, \\\"tabTimesheet\\\".employee_name,\\n\\t\\t\\\"tabTimesheet Detail\\\".from_time, \\\"tabTimesheet Detail\\\".to_time, \\\"tabTimesheet Detail\\\".hours,\\n\\t\\t\\\"tabTimesheet Detail\\\".activity_type, \\\"tabTimesheet Detail\\\".task, \\\"tabTimesheet Detail\\\".project,\\n\\t\\t\\\"tabTimesheet\\\".status from \\\"tabTimesheet Detail\\\", \\\"tabTimesheet\\\" where\\n\\t\\t\\\"tabTimesheet Detail\\\".parent = \\\"tabTimesheet\\\".name and \\\"tabTimesheet\\\".docstatus = '1' and \\\"tabTimesheet Detail\\\".from_time >= timestamp(%(from_date)s, %(from_time)s) and \\\"tabTimesheet Detail\\\".to_time <= timestamp(%(to_date)s, %(to_time)s) order by \\\"tabTimesheet\\\".name {'from_date': '2024-09-19', 'to_date': '2024-09-19', 'from_time': '00:00:00', 'to_time': '24:00:00'}\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by VishvParikh** [comment]
Issue is resolve 
change from date and to date formats according to postgres sql 
change function in daliy_timsheet_summary.py 
def get_conditions(filters):
	conditions = "`tabTimesheet`.docstatus = 0"
	if filters.get("from_date"):
		conditions += " and `tabTimesheet Detail`.from_time >= to_timestamp(%(from_date)s || ' ' || %(from_time)s, 'YYYY-MM-DD HH24:MI:SS')"

	if filters.get("to_date"):
		conditions += " AND `tabTimesheet Detail`.to_time <= to_timestamp(%(to_date)s || ' ' || %(to_time)s, 'YYYY-MM-DD HH24:MI:SS')"

	match_conditions = build_match_conditions("Timesheet")
	if match_conditions:
		conditions += " and %s" % match_conditions

	return conditions

**Comment by VishvParikh** [comment]
Issue is resolved 
code is push in the daliy_timsheet_summary branch 
and pr number is 
https://github.com/8848digital/erpnext/pull/18

**Comment by aasif-patel** [comment]
@VishvParikh please raise another PR for pre-prod,

**Comment by aasif-patel** [comment]
Tested and Resolved, Hence closing...
