### ISSUE TITLE
When selecting Batch from Select batch Dialog.

### ISSUE THREAD

**Issue by aasif-patel** [8848digital/erpnext#145]
### Information about bug

**Exactly when applied filter Fetch Based On as Expiry, this error occurs**

To generate the error, Goto Delivery Note (MAT-DN-2024-00004) => Open Item Table (Item should have Has Batch checked) then goto Serial and Batch No section and click on **Pick Serial/Batch No** button=> On dialog apply filter as  Fetch Based On as Expiry
![image](https://github.com/user-attachments/assets/3492fd40-19a0-4fad-9400-ce58ac0e31f0)

ERROR SS=>
![image](https://github.com/user-attachments/assets/77641ab0-bbce-48bf-a330-dcfc496102c6)

### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Delivery Note/MAT-DN-2024-00004
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1471, in get_auto_data
    return get_auto_batch_nos(kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1811, in get_auto_batch_nos
    available_batches = get_available_batches(kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1946, in get_available_batches
    data = query.run(as_dict=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabBatch.expiry_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...Entry"."warehouse","tabBatch"."creation" ORDER BY "tabBatch"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "_Test FG Item",
		"warehouse": "Stores - 8D",
		"has_serial_no": 0,
		"has_batch_no": 1,
		"qty": 1,
		"based_on": "Expiry"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.doctype.serial_and_batch_bundle.serial_and_batch_bundle.get_auto_data",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabBatch.expiry_date\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...Entry\\\".\\\"warehouse\\\",\\\"tabBatch\\\".\\\"creation\\\" ORDER BY \\\"tabBatch\\\"...\\n                                                             ^\\n\"]"
}
```

### Module

other

### Version

"erpnext": "15.34.0",
"frappe": "15.41.0",
"payments": "0.0.1"

### Installation method

manual install

**Comment by aasif-patel** [comment]
Resolved hence closing...
