### ISSUE TITLE
Pick List: while submitting pick list getting error 

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#146]
### Information about bug

Unable to submit pick list
![image](https://github.com/user-attachments/assets/05e53606-d2fc-4ed8-9a5e-3fb00e86d2f1)

### Module

stock

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Pick List/STO-PICK-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 196, in on_submit
    self.update_reference_qty()
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 320, in update_reference_qty
    self.update_sales_order_item_qty(so_items)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 340, in update_sales_order_item_qty
    picked_items = get_picked_items_qty(so_items)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 724, in get_picked_items_qty
    return (
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.FeatureNotSupported: FOR UPDATE is not allowed with GROUP BY clause


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"STO-PICK-2024-00001\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 16:56:29.142147\",\"modified\":\"2024-10-01 16:56:29.165198\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"STO-PICK-.YYYY.-\",\"company\":\"8848 Digital\",\"purpose\":\"Delivery\",\"customer\":\"Test_xyz\",\"customer_name\":\"Test_xyz\",\"for_qty\":0,\"consider_rejected_warehouses\":0,\"pick_manually\":0,\"ignore_pricing_rule\":0,\"scan_mode\":0,\"prompt_qty\":0,\"group_same_items\":0,\"status\":\"Draft\",\"doctype\":\"Pick List\",\"locations\":[{\"name\":\"d6vjqskji7\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 16:56:29.142147\",\"modified\":\"2024-10-01 16:56:29.142147\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"_Test FG Item 2\",\"item_name\":\"_Test FG Item 2\",\"description\":\"_Test FG Item 2 11\",\"item_group\":\"_Test Item Group Desktops\",\"warehouse\":\"Stores - 8D\",\"qty\":10,\"stock_qty\":10,\"picked_qty\":0,\"stock_reserved_qty\":0,\"uom\":\"_Test UOM\",\"conversion_factor\":1,\"stock_uom\":\"_Test UOM\",\"use_serial_batch_fields\":1,\"serial_no\":\"TESTFG200001\\nABC-001\\nABC-002\\nABC-003\\nABC-004\\nABC-005\\nABC-006\\nABC-007\\nABC-008\\nABC-009\",\"sales_order\":\"SAL-ORD-2024-00016\",\"sales_order_item\":\"c4t6jtui3b\",\"parent\":\"STO-PICK-2024-00001\",\"parentfield\":\"locations\",\"parenttype\":\"Pick List\",\"doctype\":\"Pick List Item\"}],\"__last_sync_on\":\"2024-10-01T11:26:42.617Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370078053770369246631": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 581,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "FeatureNotSupported",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nFOR UPDATE is not allowed with GROUP BY clause\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
issue resolved 
PR 196

**Comment by tinadn** [comment]
Working Fine. Hence closing.
