### ISSUE TITLE
 Request for Raw Material creation through sales order create button getting error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#147]
### Information about bug

![image](https://github.com/user-attachments/assets/566f943d-df5d-4d6a-81ab-7d7f13e1b521)
![image](https://github.com/user-attachments/assets/725714da-aa60-4e58-ac02-69fa5f9d3168)

### Module

selling

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Order/SAL-ORD-2024-00003
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 1559, in make_raw_material_request
    raw_materials = get_items_for_material_requests(items)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 1539, in get_items_for_material_requests
    item_details = get_subitems(
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 1172, in get_subitems
    items = (
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabItem.default_material_request_type" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "tabBOM Item"."item_code","tabItem"."default_material...
                                         ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"items": "{\"include_exploded_items\":0,\"ignore_existing_ordered_qty\":0,\"items\":[{\"name\":\"fa5kqleqb9\",\"item_code\":\"_Test FG Item 2\",\"description\":\"_Test FG Item 2 11\",\"bom\":\"BOM-_Test FG Item 2-002\",\"warehouse\":\"Stores - 8D\",\"pending_qty\":1,\"required_qty\":1,\"sales_order_item\":\"fa5kqleqb9\",\"idx\":1},{\"name\":\"fa5ktlkdfc\",\"item_code\":\"_Test FG Item 2\",\"description\":\"_Test FG Item 2 11\",\"bom\":\"BOM-_Test FG Item 2-002\",\"warehouse\":\"Stores - 8D\",\"pending_qty\":562,\"required_qty\":562,\"sales_order_item\":\"fa5ktlkdfc\",\"idx\":2}]}",
		"company": "8848 Digital",
		"sales_order": "SAL-ORD-2024-00003"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.selling.doctype.sales_order.sales_order.make_raw_material_request",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabItem.default_material_request_type\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: SELECT \\\"tabBOM Item\\\".\\\"item_code\\\",\\\"tabItem\\\".\\\"default_material...\\n                                         ^\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closed
