### ISSUE TITLE
Sales Order Connection tab getting error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#150]
### Information about bug

when you click on connection tab of sales order getting error
![image](https://github.com/user-attachments/assets/5f391737-3516-4a2b-bbb5-aff1d98262b3)

### Module

selling

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Order/SAL-ORD-2024-00016
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 289, in get_open_count
    external_links_data_for_d = get_external_links(d, name, links)
  File "apps/frappe/frappe/desk/notifications.py", line 336, in get_external_links
    total_count = get_doc_count(doctype, filters)
  File "apps/frappe/frappe/desk/notifications.py", line 348, in get_doc_count
    frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 167, in execute
    if is_virtual_doctype(self.doctype):
  File "apps/frappe/frappe/utils/caching.py", line 121, in site_cache_wrapper
    _SITE_CACHE[func_key][frappe.local.site][func_call_key] = func(*args, **kwargs)
  File "apps/frappe/frappe/model/utils/__init__.py", line 133, in is_virtual_doctype
    return frappe.db.get_value("DocType", doctype, "is_virtual")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Sales Order",
		"name": "SAL-ORD-2024-00016",
		"items": "[\"Sales Invoice\",\"Pick List\",\"Delivery Note\",\"Maintenance Visit\",\"Material Request\",\"Purchase Order\",\"Project\",\"Work Order\",\"Quotation\",\"Auto Repeat\",\"Stock Reservation Entry\",\"Payment Entry\",\"Payment Request\",\"Journal Entry\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_debug_messages": "[\"Error in query:\\ncolumn tabQuotation.sales_order does not exist\\nLINE 3:    where \\\"tabQuotation\\\".\\\"sales_order\\\" = 'SAL-ORD-2024-00016'\\n                 ^\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by IamSaiyyamChhetri** [comment]
After adding frappe.db.rollback() the error is not showing.

Reference doc :
1. https://stackoverflow.com/questions/10399727/psqlexception-current-transaction-is-aborted-commands-ignored-until-end-of-tra
2. https://dba.stackexchange.com/questions/303935/error-current-transaction-is-aborted-commands-ignored-until-end-of-transaction

![Screenshot 2024-10-08 at 1 29 34 PM](https://github.com/user-attachments/assets/57b1de56-5617-4204-b207-e0c17103cb25)

**Comment by VishvParikh** [comment]
@IamSaiyyamChhetri 
semgrep rule is not allow to add  roll back line in code  
and roll back is not a proper solution

**Comment by aasif-patel** [comment]
Resolved hence closing...
