### ISSUE TITLE
Not able to create delivery note for Serialize Item.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#151]
### Information about bug

1) Select Item - Iphone while creating delivery note as it has configure as serial item
2) Select warehouse as Store-8D
3) Serial no will auto selected OR we can pick serial number manually from item child table- Click on edit, Click on Pick serial and batch no.
4) facing error  while clicking on ADD serial no.
![image](https://github.com/user-attachments/assets/b22386c1-8d50-4881-935a-85954fde3c63)
![image](https://github.com/user-attachments/assets/2048d0f0-cd40-42b7-a7f9-3cd2fc0fdbc0)
![image](https://github.com/user-attachments/assets/56876c1c-475b-41ca-ba73-d76b59c194fe)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Delivery Note/new-delivery-note-fthpufifcg
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 478, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 544, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 869, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 97, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 226, in make_entry
    sle.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 184, in on_submit
    SerialBatchBundle(
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 23, in __init__
    self.process_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 31, in process_serial_and_batch_bundle
    self.process_serial_no()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 54, in process_serial_no
    self.make_serial_batch_no_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 115, in make_serial_batch_no_bundle
    ).make_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 948, in make_serial_and_batch_bundle
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 102, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 210, in set_incoming_rate
    self.set_incoming_rate_for_outward_transaction(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 247, in set_incoming_rate_for_outward_transaction
    sn_obj = SerialNoValuation(
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 493, in __init__
    self.calculate_stock_value_change()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 508, in calculate_stock_value_change
    incoming_rate = self.get_incoming_rate_from_bundle(serial_no)
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 553, in get_incoming_rate_from_bundle
    incoming_rate = query.run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ""tabSerial and Batch Bundle""
LINE 1: ...AST('17:29:44.171736' AS TIME) ORDER BY TIMESTAMP("tabSerial...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-DN-2024-00010\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 17:29:40.214252\",\"modified\":\"2024-10-01 17:29:40.214252\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Zudio\",\"naming_series\":\"MAT-DN-.YYYY.-\",\"customer\":\"Zudio\",\"tax_id\":null,\"customer_name\":\"Zudio\",\"posting_date\":\"2024-10-01\",\"posting_time\":\"17:29:40.248016\",\"set_posting_time\":0,\"company\":\"8848 Digital\",\"amended_from\":null,\"is_return\":0,\"issue_credit_note\":0,\"return_against\":null,\"cost_center\":null,\"project\":null,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"scan_barcode\":null,\"pick_list\":null,\"set_warehouse\":\"Stores - 8D\",\"set_target_warehouse\":null,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":50000,\"base_net_total\":50000,\"total\":50000,\"net_total\":50000,\"tax_category\":\"\",\"taxes_and_charges\":null,\"shipping_rule\":null,\"incoterm\":null,\"named_place\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":50000,\"base_rounding_adjustment\":0,\"base_rounded_total\":50000,\"base_in_words\":\"\",\"grand_total\":50000,\"rounding_adjustment\":0,\"rounded_total\":50000,\"in_words\":\"\",\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":null,\"customer_address\":\"Zudio-Billing\",\"address_display\":\"Rahate colony Nagpur<br>\\nRahate colony Nagpur<br>Nagpur<br>\\nMaharashtra<br>India<br>\\n<br>\\n\",\"contact_person\":null,\"contact_display\":null,\"contact_mobile\":null,\"contact_email\":null,\"shipping_address_name\":null,\"shipping_address\":null,\"dispatch_address_name\":null,\"dispatch_address\":null,\"company_address\":\"8848 Digital-Billing\",\"company_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"tc_name\":null,\"terms\":null,\"per_billed\":0,\"status\":\"Draft\",\"per_installed\":0,\"installation_status\":\"Not Installed\",\"per_returned\":0,\"transporter\":null,\"driver\":null,\"lr_no\":null,\"vehicle_no\":null,\"transporter_name\":null,\"driver_name\":null,\"lr_date\":\"2024-10-01\",\"po_no\":\"\",\"po_date\":null,\"sales_partner\":null,\"amount_eligible_for_commission\":50000,\"commission_rate\":0,\"total_commission\":0,\"auto_repeat\":null,\"letter_head\":\"8848 Digital\",\"print_without_amount\":0,\"group_same_items\":0,\"select_print_heading\":null,\"language\":\"en\",\"is_internal_customer\":0,\"represents_company\":null,\"inter_company_reference\":null,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"source\":null,\"campaign\":null,\"excise_page\":null,\"instructions\":null,\"doctype\":\"Delivery Note\",\"sales_team\":[],\"packed_items\":[],\"taxes\":[],\"items\":[{\"name\":\"dqdqap9tj7\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 17:29:40.214252\",\"modified\":\"2024-10-01 17:29:40.214252\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"item_code\":\"Iphone\",\"item_name\":\"Iphone\",\"customer_item_code\":null,\"description\":\"Iphone\",\"brand\":null,\"item_group\":\"_Test Item Group\",\"image\":\"\",\"qty\":1,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":1,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":50000,\"amount\":50000,\"base_rate\":50000,\"base_amount\":50000,\"pricing_rules\":\"\",\"stock_uom_rate\":50000,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":50000,\"net_amount\":50000,\"item_tax_template\":null,\"base_net_rate\":50000,\"base_net_amount\":50000,\"billed_amt\":0,\"incoming_rate\":20000,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":null,\"warehouse\":\"Stores - 8D\",\"target_warehouse\":null,\"quality_inspection\":null,\"allow_zero_valuation_rate\":0,\"against_sales_order\":null,\"so_detail\":null,\"against_sales_invoice\":null,\"si_detail\":null,\"dn_detail\":null,\"pick_list_item\":null,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":1,\"serial_no\":null,\"batch_no\":null,\"actual_batch_qty\":0,\"actual_qty\":10,\"installed_qty\":0,\"item_tax_rate\":\"{}\",\"packed_qty\":0,\"received_qty\":0,\"expense_account\":\"Cost of Goods Sold - 8D\",\"material_request\":null,\"purchase_order\":null,\"purchase_order_item\":null,\"material_request_item\":null,\"cost_center\":\"Main - 8D\",\"project\":null,\"page_break\":0,\"parent\":\"MAT-DN-2024-00010\",\"parentfield\":\"items\",\"parenttype\":\"Delivery Note\",\"doctype\":\"Delivery Note Item\",\"__unsaved\":1}],\"pricing_rules\":[],\"__onload\":{\"has_unpacked_items\":true},\"__last_sync_on\":\"2024-10-01T11:59:41.700Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery37009463974132299911": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 19503,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nSELECT \\\"tabSerial and Batch Entry\\\".\\\"incoming_rate\\\"*\\\"tabSerial and Batch Entry\\\".\\\"qty\\\" \\\"incoming_rate\\\" FROM \\\"tabSerial and Batch Bundle\\\" JOIN \\\"tabSerial and Batch Entry\\\" ON \\\"tabSerial and Batch Bundle\\\".\\\"name\\\"=\\\"tabSerial and Batch Entry\\\".\\\"parent\\\" WHERE \\\"tabSerial and Batch Bundle\\\".\\\"is_cancelled\\\"= '0' AND \\\"tabSerial and Batch Bundle\\\".\\\"docstatus\\\"= '1' AND \\\"tabSerial and Batch Entry\\\".\\\"serial_no\\\"=%(param1)s AND \\\"tabSerial and Batch Bundle\\\".\\\"type_of_transaction\\\"=%(param2)s AND \\\"tabSerial and Batch Entry\\\".\\\"qty\\\"> '0' AND \\\"tabSerial and Batch Bundle\\\".\\\"item_code\\\"=%(param3)s AND \\\"tabSerial and Batch Entry\\\".\\\"warehouse\\\"=%(param4)s AND \\\"tabSerial and Batch Bundle\\\".\\\"posting_date\\\"+\\\"tabSerial and Batch Bundle\\\".\\\"posting_time\\\"<=CAST(%(param5)s AS DATE)+CAST(%(param6)s AS TIME) ORDER BY TIMESTAMP(\\\"tabSerial and Batch Bundle\\\".\\\"posting_date\\\",\\\"tabSerial and Batch Bundle\\\".\\\"posting_time\\\") DESC LIMIT 1 {'param1': 'IP-0001', 'param2': 'Inward', 'param3': 'Iphone', 'param4': 'Stores - 8D', 'param5': '2024-10-01', 'param6': '17:29:44.171736'}\"]"
}
```
```

**Comment by tinadn** [comment]
Working Fine. Hence Closing.
