### ISSUE TITLE
Unable to submit Quality Inspection entry

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#154]
### Information about bug

Unable to submit quality inspection 
	
![image](https://github.com/user-attachments/assets/8832761f-f6cd-40e7-9b1e-0b24bb5e09ac)

### Module

stock

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Quality Inspection/MAT-QA-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/quality_inspection/quality_inspection.py", line 109, in on_submit
    self.update_qc_reference()
  File "apps/erpnext/erpnext/stock/doctype/quality_inspection/quality_inspection.py", line 153, in update_qc_reference
    frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ","
LINE 2:       "tabSubcontracting Receipt Item" t1, "tabSubcontractin...
                                                 ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-QA-2024-00001\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 17:50:54.407283\",\"modified\":\"2024-10-01 17:51:28.121907\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-QA-.YYYY.-\",\"report_date\":\"2024-10-01\",\"status\":\"Accepted\",\"manual_inspection\":0,\"inspection_type\":\"Incoming\",\"reference_type\":\"Subcontracting Receipt\",\"reference_name\":\"MAT-SCR-2024-00002\",\"item_code\":\"_Test FG Item\",\"sample_size\":0,\"item_name\":\"_Test FG Item\",\"description\":\"_Test FG Item 6\",\"inspected_by\":\"Administrator\",\"doctype\":\"Quality Inspection\",\"readings\":[{\"name\":\"e76hf85dr7\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 17:50:54.407283\",\"modified\":\"2024-10-01 17:51:28.121907\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"specification\":\"Test Parameter\",\"status\":\"Accepted\",\"numeric\":1,\"manual_inspection\":0,\"min_value\":0,\"max_value\":0,\"formula_based_criteria\":0,\"parent\":\"MAT-QA-2024-00001\",\"parentfield\":\"readings\",\"parenttype\":\"Quality Inspection\",\"doctype\":\"Quality Inspection Reading\"}],\"__last_sync_on\":\"2024-10-01T12:29:05.721Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700063392261327629651": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 723,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nUPDATE\\n\\t\\t\\t\\t\\t\\t\\\"tabSubcontracting Receipt Item\\\" t1, \\\"tabSubcontracting Receipt\\\" t2\\n\\t\\t\\t\\t\\tSET\\n\\t\\t\\t\\t\\t\\tt1.quality_inspection = %s, t2.modified = %s\\n\\t\\t\\t\\t\\tWHERE\\n\\t\\t\\t\\t\\t\\tt1.parent = %s\\n\\t\\t\\t\\t\\t\\tand t1.item_code = %s\\n\\t\\t\\t\\t\\t\\tand t1.parent = t2.name ['MAT-QA-2024-00001', '2024-10-01 17:59:14.754479', 'MAT-SCR-2024-00002', '_Test FG Item']\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
