### ISSUE TITLE
Report:Item To be Requested ,InFailedSqlTransaction

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#16]
### Information about bug

click on show report showing an error
![Screenshot from 2024-09-19 16-03-20](https://github.com/user-attachments/assets/eb5ff142-1a8f-4796-9609-a73762975105)

### Module

stock

### Version

ERPNext: v16.0.0-dev
Frappe Framework: v15.40.6 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "16.0.0-dev",
	"frappe": "15.40.6"
}
```
### Route
```
query-report/Items To Be Requested
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 149, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: relation "tabbin" does not exist
LINE 10:     tabBin, tabItem
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 81, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Items To Be Requested",
		"filters": "{}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_debug_messages": "[\"Error in query:\\nrelation \\\"tabbin\\\" does not exist\\nLINE 10:     tabBin, tabItem\\n             ^\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved, Hence Closing...
