### ISSUE TITLE
While clicking on Get Unreconciled Entries in Payment Reconciliation Showing Error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#184]
### Information about bug

Select party type and party than click on get unreconciled entries.
![image](https://github.com/user-attachments/assets/cf6de2c6-1a7c-4428-a8c2-08bc6964b083)
![image](https://github.com/user-attachments/assets/f14a9f0c-9c40-4927-9219-1de5c8c70856)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Payment Reconciliation/Payment Reconciliation
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 330, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 131, in get_unreconciled_entries
    self.get_invoice_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 348, in get_invoice_entries
    non_reconciled_invoices = get_outstanding_invoices(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1032, in get_outstanding_invoices
    invoice_list = ple_query.get_voucher_outstandings(
  File "apps/erpnext/erpnext/accounts/utils.py", line 2023, in get_voucher_outstandings
    self.query_for_outstanding()
  File "apps/erpnext/erpnext/accounts/utils.py", line 1860, in query_for_outstanding
    .run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Ledger Entry.posting_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...HAVING "amount_in_account_currency"> '0' ORDER BY "posting_d...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"Payment Reconciliation\",\"minimum_invoice_amount\":0,\"minimum_payment_amount\":0,\"maximum_invoice_amount\":0,\"maximum_payment_amount\":0,\"invoice_limit\":50,\"payment_limit\":50,\"doctype\":\"Payment Reconciliation\",\"invoices\":[],\"payments\":[],\"allocation\":[],\"company\":\"8848 Digital\",\"party_type\":\"Customer\",\"party\":\"Test_xyz\",\"receivable_payable_account\":\"Debtors - 8D\",\"__unsaved\":1,\"docstatus\":0,\"idx\":0}",
		"method": "get_unreconciled_entries"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPayment Ledger Entry.posting_date\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...HAVING \\\"amount_in_account_currency\\\"> '0' ORDER BY \\\"posting_d...\\n                                                             ^\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
