### ISSUE TITLE
Error on opening Dashboard Tab on Company Creation

### ISSUE THREAD

**Issue by DipaliMehta15** [8848digital/erpnext#203]
### Information about bug

Error encountered while opening Dashboard Tab after creating a new company. Please find attached below screen print.

![Screenshot 2024-10-09 111710](https://github.com/user-attachments/assets/ce62ce83-06d8-4cb4-8eeb-cfc74b577c55)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tohidmalik002** [comment]
PR Raised: https://github.com/8848digital/erpnext/pull/205

**Comment by tinadn** [comment]
Please check the error below:
![image](https://github.com/user-attachments/assets/40b40fc7-3910-41a5-8b1b-75a43a6e6bec)

### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Company/Test Jio Financial Services Limited
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 299, in get_open_count
    out["timeline_data"] = module.get_timeline_data(doctype, name)
  File "apps/erpnext/erpnext/setup/doctype/company/company.py", line 882, in get_timeline_data
    update_transactions_annual_history(name, True)
  File "apps/erpnext/erpnext/setup/doctype/company/company.py", line 768, in update_transactions_annual_history
    frappe.db.set_value("Company", company, "transactions_annual_history", json.dumps(transactions_history))
  File "apps/frappe/frappe/database/database.py", line 987, in set_value
    query.run(debug=debug)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Company",
		"name": "Test Jio Financial Services Limited",
		"items": "[\"Quotation\",\"Sales Order\",\"Delivery Note\",\"Sales Invoice\",\"Issue\",\"Project\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SerializationFailure",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncould not serialize access due to concurrent update\\n\"]"
}
```

**Comment by tohidmalik002** [comment]
PR Raised: https://github.com/8848digital/erpnext/pull/218

**Comment by tinadn** [comment]
Working fine. Hence closing.
