### ISSUE TITLE
Server error on Sales Person Doctype

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#206]
### Information about bug

**Syntax error in query:** 
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 1: ...D "tabSales Order"."transaction_date">CURRENT_DATE()

![Error_IMG](https://github.com/user-attachments/assets/43c3295e-1be8-491b-ad45-8501d68ba507)

### Module

other

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Person/Test Sales Person
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 299, in get_open_count
    out["timeline_data"] = module.get_timeline_data(doctype, name)
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 126, in get_timeline_data
    sales_order_activity = _fetch_activity("Sales Order", "transaction_date")
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 123, in _fetch_activity
    .run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 1: ...D "tabSales Order"."transaction_date">CURRENT_DATE()-INTERVA...
                                                             ^


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Sales Person",
		"name": "Test Sales Person",
		"items": "[\"Sales Order\",\"Delivery Note\",\"Sales Invoice\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nSELECT EXTRACT(epoch FROM \\\"tabSales Order\\\".\\\"transaction_date\\\"),COUNT(*) FROM \\\"tabSales Order\\\" JOIN \\\"tabSales Team\\\" ON \\\"tabSales Order\\\".\\\"name\\\"=\\\"tabSales Team\\\".\\\"parent\\\" WHERE \\\"tabSales Team\\\".\\\"sales_person\\\"=%(param1)s AND \\\"tabSales Order\\\".\\\"transaction_date\\\">CURRENT_DATE()-INTERVAL '1 YEAR' GROUP BY \\\"tabSales Order\\\".\\\"transaction_date\\\" {'param1': 'Test Sales Person'}\"]"
}
```
```

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/207

**Comment by tinadn** [comment]
Working Fine. Hence Closing.
