### ISSUE TITLE
while opening the POS getting error

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#209]
### Information about bug

**Bug Details:**

- Open the Point of sale then error will be occur
![Screenshot from 2024-10-09 15-27-30](https://github.com/user-attachments/assets/68a864ec-242b-4038-b9f5-8aa8fe1c2897)

### Module

selling

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 333, in run_doc_method
    response = doc.run_method(method, args)
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 626, in set_missing_values
    profile = self.set_pos_fields(for_validate)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 547, in set_pos_fields
    update_multi_mode_option(self, profile)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2606, in update_multi_mode_option
    mode_of_payments_info = get_mode_of_payments_info(mode_of_payments, doc.company)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2637, in get_mode_of_payments_info
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "mpa.default_account" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:    mpa.default_account, mpa.parent as mop, mp.type as type
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
