### ISSUE TITLE
Sales Order:Click on Submit button then showing an error

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#21]
### Information about bug

When the user clicks on the Sales Order submit button, an error is shown.
![Screenshot from 2024-09-24 12-26-27](https://github.com/user-attachments/assets/e4313e06-2632-41d5-a4c1-fa2e70dea70d)

### Module

selling

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.41.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0"
}
```
### Route
```
Form/Sales Order/SAL-ORD-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 404, in on_submit
    self.update_reserved_qty()
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 530, in update_reserved_qty
    update_bin_qty(item_code, warehouse, {"reserved_qty": get_reserved_qty(item_code, warehouse)})
  File "apps/erpnext/erpnext/stock/stock_balance.py", line 95, in get_reserved_qty
    reserved_qty = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function if(integer, numeric, integer) does not exist
LINE 2: ...npi_qty * ((so_item_qty - so_item_delivered_qty - if(dont_re...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"SAL-ORD-2024-00001\",\"owner\":\"satya@8848digital.com\",\"creation\":\"2024-09-24 02:18:24.124436\",\"modified\":\"2024-09-24 02:18:24.124436\",\"modified_by\":\"satya@8848digital.com\",\"docstatus\":0,\"idx\":0,\"title\":\"{customer_name}\",\"naming_series\":\"SAL-ORD-.YYYY.-\",\"customer\":\"Test\",\"customer_name\":\"Test\",\"order_type\":\"Sales\",\"transaction_date\":\"2024-09-24\",\"delivery_date\":\"2024-09-24\",\"company\":\"8848 Digital\",\"skip_delivery_note\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"reserve_stock\":0,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":120,\"base_net_total\":120,\"total\":120,\"net_total\":120,\"tax_category\":\"\",\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":120,\"base_rounding_adjustment\":0,\"base_rounded_total\":120,\"base_in_words\":\"\",\"grand_total\":120,\"rounding_adjustment\":0,\"rounded_total\":120,\"in_words\":\"\",\"advance_paid\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"status\":\"Draft\",\"delivery_status\":\"Not Delivered\",\"per_delivered\":0,\"per_billed\":0,\"per_picked\":0,\"billing_status\":\"Not Billed\",\"amount_eligible_for_commission\":120,\"commission_rate\":0,\"total_commission\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"group_same_items\":0,\"language\":\"en\",\"is_internal_customer\":0,\"party_account_currency\":\"INR\",\"doctype\":\"Sales Order\",\"items\":[{\"name\":\"4i7hv95h0f\",\"owner\":\"satya@8848digital.com\",\"creation\":\"2024-09-24 02:18:24.124436\",\"modified\":\"2024-09-24 02:18:24.124436\",\"modified_by\":\"satya@8848digital.com\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Test1\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":0,\"delivery_date\":\"2024-09-24\",\"item_name\":\"Test1\",\"description\":\"Test1\",\"item_group\":\"Consumable\",\"image\":\"\",\"qty\":1,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":1,\"stock_reserved_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":120,\"amount\":120,\"base_rate\":120,\"base_amount\":120,\"pricing_rules\":\"\",\"stock_uom_rate\":120,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":120,\"net_amount\":120,\"base_net_rate\":120,\"base_net_amount\":120,\"billed_amt\":0,\"valuation_rate\":0,\"gross_profit\":120,\"delivered_by_supplier\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - 8D\",\"against_blanket_order\":0,\"blanket_order_rate\":0,\"projected_qty\":0,\"actual_qty\":0,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"page_break\":0,\"item_tax_rate\":\"{}\",\"transaction_date\":\"2024-09-24\",\"parent\":\"SAL-ORD-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"doctype\":\"Sales Order Item\"}],\"sales_team\":[],\"packed_items\":[],\"taxes\":[],\"pricing_rules\":[],\"payment_schedule\":[{\"name\":\"4i7jvvhgmv\",\"owner\":\"satya@8848digital.com\",\"creation\":\"2024-09-24 02:18:24.333282\",\"modified\":\"2024-09-24 02:18:24.333282\",\"modified_by\":\"satya@8848digital.com\",\"docstatus\":0,\"idx\":1,\"due_date\":\"2024-09-24\",\"invoice_portion\":100,\"discount\":0,\"payment_amount\":120,\"outstanding\":120,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":120,\"parent\":\"SAL-ORD-2024-00001\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Order\",\"doctype\":\"Payment Schedule\"}],\"__last_sync_on\":\"2024-09-24T06:51:36.104Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370093994311954425511": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 822,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedFunction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfunction if(integer, numeric, integer) does not exist\\nLINE 2: ...npi_qty * ((so_item_qty - so_item_delivered_qty - if(dont_re...\\n                                                             ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n\"]"
}
```
```

**Comment by VishvParikh** [comment]
Issue is resolved 
code is push in sales_order_bug branch 
and pr link 
https://github.com/8848digital/erpnext/pull/37

**Comment by aasif-patel** [comment]
@VishvParikh please raise another PR for pre-prod,

**Comment by aasif-patel** [comment]
Resolved hence closing...
