### ISSUE TITLE
Bug: Server error while creating delivery note from pick list

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#210]
### Information about bug

![image](https://github.com/user-attachments/assets/163d0afd-f7f1-49b4-a137-882877319e1f)
Not able to create Delivery Note from submitted pick list
### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Pick List/STO-PICK-2024-00002
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 1115, in create_delivery_note
    delivery_note = create_dn_with_so(sales_dict, pick_list)
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 1165, in create_dn_with_so
    delivery_note.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 253, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 29, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 194, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 457, in set_incoming_rate
    d.incoming_rate = get_incoming_rate(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/utils.py", line 282, in get_incoming_rate
    sn_obj = SerialNoValuation(sle=args, warehouse=args.get("warehouse"), item_code=args.get("item_code"))
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 493, in __init__
    self.calculate_stock_value_change()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 508, in calculate_stock_value_change
    incoming_rate = self.get_incoming_rate_from_bundle(serial_no)
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 553, in get_incoming_rate_from_bundle
    incoming_rate = query.run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ""tabSerial and Batch Bundle""
LINE 1: ...AST('15:26:41.503947' AS TIME) ORDER BY TIMESTAMP("tabSerial...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.stock.doctype.pick_list.pick_list.create_delivery_note",
		"source_name": "STO-PICK-2024-00002",
		"args": null,
		"selected_children": "{}"
	},
	"freeze": true,
	"freeze_message": "",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.make_mapped_doc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_server_messages": "[\"{\\\"message\\\": \\\"Item Price added for _Test FG Item 2 in Price List Standard Selling\\\", \\\"title\\\": \\\"Message\\\", \\\"alert\\\": 1}\"]",
	"_debug_messages": "[\"Syntax error in query:\\nSELECT \\\"tabSerial and Batch Entry\\\".\\\"incoming_rate\\\"*\\\"tabSerial and Batch Entry\\\".\\\"qty\\\" \\\"incoming_rate\\\" FROM \\\"tabSerial and Batch Bundle\\\" JOIN \\\"tabSerial and Batch Entry\\\" ON \\\"tabSerial and Batch Bundle\\\".\\\"name\\\"=\\\"tabSerial and Batch Entry\\\".\\\"parent\\\" WHERE \\\"tabSerial and Batch Bundle\\\".\\\"is_cancelled\\\"= '0' AND \\\"tabSerial and Batch Bundle\\\".\\\"docstatus\\\"= '1' AND \\\"tabSerial and Batch Entry\\\".\\\"serial_no\\\"=%(param1)s AND \\\"tabSerial and Batch Bundle\\\".\\\"type_of_transaction\\\"=%(param2)s AND \\\"tabSerial and Batch Entry\\\".\\\"qty\\\"> '0' AND \\\"tabSerial and Batch Bundle\\\".\\\"item_code\\\"=%(param3)s AND \\\"tabSerial and Batch Entry\\\".\\\"warehouse\\\"=%(param4)s AND \\\"tabSerial and Batch Bundle\\\".\\\"voucher_no\\\"<>%(param5)s AND \\\"tabSerial and Batch Bundle\\\".\\\"posting_date\\\"+\\\"tabSerial and Batch Bundle\\\".\\\"posting_time\\\"<=CAST(%(param6)s AS DATE)+CAST(%(param7)s AS TIME) ORDER BY TIMESTAMP(\\\"tabSerial and Batch Bundle\\\".\\\"posting_date\\\",\\\"tabSerial and Batch Bundle\\\".\\\"posting_time\\\") DESC LIMIT 1 {'param1': 'ABC-093', 'param2': 'Inward', 'param3': '_Test FG Item 2', 'param4': 'Stores - 8D', 'param5': 'MAT-DN-2024-00020', 'param6': '2024-10-09', 'param7': '15:26:41.503947'}\"]"
}
```

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

**Comment by shubham-DT** [comment]
@tinadn This transaction is working fine now

**Comment by tinadn** [comment]
Working fine. Hence closing.
