### ISSUE TITLE
while saving the POS Closing Entry doctype, getting the error

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#214]
### Information about bug

**Information about the bug**

- Go to the Pos Closing Entry doctype,
- Create a new Pos Closing Entry doctype and save it, then error will come

![Screenshot from 2024-10-10 11-34-02](https://github.com/user-attachments/assets/2a6e14e9-60f6-4821-ba6f-6c25ec2375e7)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/pos_closing_entry/pos_closing_entry.py", line 151, in get_pos_invoices
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "posting_date"
LINE 2:   name, timestamp(posting_date, posting_time) as "timestamp"
                          ^
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
