### ISSUE TITLE
Getting error in the pos closing entry

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#219]
### Information about bug

**information about the bug**
Open the pos closing entry, without adding any data save the document then error will be appear

![Screenshot from 2024-10-10 13-06-43](https://github.com/user-attachments/assets/9115f5bb-71f0-4fdb-91a5-c37d36af1a81)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
TypeError: get_pos_invoices() missing 2 required positional arguments: 'pos_profile' and 'user'
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
