### ISSUE TITLE
Purchase Receipt/Error on save of purchase receipt

### ISSUE THREAD

**Issue by 8848Suraj** [8848digital/erpnext#22]
### Information about bug

On save of purchase receipt
![Screenshot 2024-09-25 114242](https://github.com/user-attachments/assets/fac55c03-861a-4c98-896e-e11fe93c44eb)

### Module

stock

### Version

ERPNext: v15.34.0 (version-15)
Frappe Framework: v15.41.0 (version-15)
Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 233, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 59, in validate
    self.set_landed_cost_voucher_amount()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 212, in set_landed_cost_voucher_amount
    lc_voucher_data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabLanded Cost Item.cost_center" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select sum(applicable_charges), cost_center
                                        ^
```

**Comment by nilesh8848** [comment]
Resolved and raised PR

**Comment by aasif-patel** [comment]
Resolved, Hence Closing...
