### ISSUE TITLE
Server error on Bank Clearance while getting payment entries

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#223]
### Information about bug

![image](https://github.com/user-attachments/assets/e4f0bbd1-1ce4-4ab7-8c15-15a36e9aeff6)

### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Bank Clearance/Bank Clearance
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 330, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/bank_clearance/bank_clearance.py", line 53, in get_payment_entries
    frappe.get_attr(method_name)(
  File "apps/erpnext/erpnext/accounts/doctype/bank_clearance/bank_clearance.py", line 132, in get_payment_entries_for_bank_clearance
    journal_entries = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Journal Entry" does not exist
LINE 2:     "Journal Entry" as payment_document, t1.name as payment_...
            ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"Bank Clearance\",\"owner\":\"Administrator\",\"modified\":\"2024-09-24 02:08:13.835255\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":\"0\",\"include_reconciled_entries\":0,\"include_pos_transactions\":0,\"doctype\":\"Bank Clearance\",\"payment_entries\":[{\"docstatus\":0,\"doctype\":\"Bank Clearance Detail\",\"name\":\"new-bank-clearance-detail-vbkriejxom\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"parent\":\"Bank Clearance\",\"parentfield\":\"payment_entries\",\"parenttype\":\"Bank Clearance\",\"idx\":1,\"__unedited\":true}],\"__last_sync_on\":\"2024-10-10T09:24:46.271Z\",\"account\":\"Bank Account - 8D\",\"from_date\":\"2024-10-01\",\"to_date\":\"2024-10-31\",\"__unsaved\":1,\"account_currency\":\"INR\"}",
		"method": "get_payment_entries"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"Journal Entry\\\" does not exist\\nLINE 2:     \\\"Journal Entry\\\" as payment_document, t1.name as payment_...\\n            ^\\n\"]"
}
```

### Module

accounts

### Version

"erpnext": "15.34.0"
"frappe": "15.41.0"

### Installation method

None

**Comment by Amandeep8848** [comment]
PR: https://github.com/8848digital/erpnext/pull/226

**Comment by tinadn** [comment]
Working fine.
