### ISSUE TITLE
Chart of Accounts Importer - Server Error

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#225]
### Information about bug

![image](https://github.com/user-attachments/assets/da050747-f6de-4fc5-8cdc-b82ce7c513eb)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by pooja-pp8848** [comment]
### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Chart of Accounts Importer/Chart of Accounts Importer
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 79, in import_coa
    unset_existing_data(company)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 465, in unset_existing_data
    frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "PP2 Ltd" does not exist
LINE 1: delete from "tabAccount" where "company"="PP2 Ltd"
                                                 ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"file_name": "/private/files/COA_PP2.xlsx",
		"company": "PP2 Ltd"
	},
	"freeze": true,
	"freeze_message": "Creating Accounts...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.chart_of_accounts_importer.chart_of_accounts_importer.import_coa",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"PP2 Ltd\\\" does not exist\\nLINE 1: delete from \\\"tabAccount\\\" where \\\"company\\\"=\\\"PP2 Ltd\\\"\\n                                                 ^\\n\"]"
}
```

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/227

**Comment by tinadn** [comment]
Working fine. Hence closing.
