### ISSUE TITLE
Purchase Invoice/ On Submit of purchase invoice

### ISSUE THREAD

**Issue by 8848Suraj** [8848digital/erpnext#23]
### Information about bug

On submit of purchase invoice against a purchase order
![image](https://github.com/user-attachments/assets/5ff29f6a-399a-4199-8ccd-33de06aaae2f)

### Module

accounts

### Version

ERPNext: v15.34.0 (version-15)
Frappe Framework: v15.41.0 (version-15)
Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 784, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 817, in make_gl_entries
    make_gl_entries(
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 40, in make_gl_entries
    create_payment_ledger_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1702, in create_payment_ledger_entry
    ple.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1130, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_ledger_entry/payment_ledger_entry.py", line 177, in on_update
    update_voucher_outstanding(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1721, in update_voucher_outstanding
    voucher_outstanding = ple_query.get_voucher_outstandings(vouchers, common_filter=common_filter)
  File "apps/erpnext/erpnext/accounts/utils.py", line 2008, in get_voucher_outstandings
    self.query_for_outstanding()
  File "apps/erpnext/erpnext/accounts/utils.py", line 1971, in query_for_outstanding
    self.voucher_outstandings = self.cte_query_voucher_amount_and_outstanding.run(as_dict=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Ledger Entry.account" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: WITH vouchers AS (SELECT "account","voucher_type","voucher_n...
                                 ^
```

**Comment by 8848swa** [comment]
when we create purchase invoice through create button of purchase order getting same error
![image](https://github.com/user-attachments/assets/7ad0c277-e0d7-482a-bbae-8d6a3f14960b)
### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00002
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 369, in on_submit
    self.update_billing_status()
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 874, in update_billing_status
    update_billing_percentage(pr_doc, update_modified=update_modified)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 1059, in update_billing_percentage
    item_wise_returned_qty = get_item_wise_returned_qty(pr_doc)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 1108, in get_item_wise_returned_qty
    frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.AmbiguousColumn: column reference "modified" is ambiguous
LINE 1: ...(abs("tabPurchase Receipt Item".qty)) as qty, MAX(modified) ...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-PRE-2024-00002\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 13:03:13.641668\",\"modified\":\"2024-09-30 13:04:46.213573\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"_Test Supplier\",\"naming_series\":\"MAT-PRE-.YYYY.-\",\"supplier\":\"_Test Supplier\",\"supplier_name\":\"_Test Supplier\",\"supplier_delivery_note\":\"225\",\"posting_date\":\"2024-09-30\",\"posting_time\":\"13:04:46.273718\",\"set_posting_time\":0,\"company\":\"8848 Digital\",\"apply_putaway_rule\":0,\"is_return\":0,\"cost_center\":\"Main - 8D\",\"project\":\"PROJ-0001\",\"currency\":\"INR\",\"conversion_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"is_subcontracted\":0,\"total_qty\":7,\"total_net_weight\":0,\"base_total\":4100,\"base_net_total\":4100,\"total\":4100,\"net_total\":4100,\"tax_withholding_net_total\":4100,\"base_tax_withholding_net_total\":4100,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":4100,\"base_rounding_adjustment\":0,\"base_rounded_total\":4100,\"base_in_words\":\"\",\"grand_total\":4100,\"rounding_adjustment\":0,\"rounded_total\":4100,\"in_words\":\"\",\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"supplier_address\":\"Test Supplier-Billing\",\"address_display\":\"address line 1<br>\\naddress line 2<br>mumbai<br>\\nMaharashtra <br>400006<br>India<br>\\n<br>\\nPhone: 022-5896555<br>Email: testsupplier@gmail.com<br>\",\"shipping_address\":\"8848 Digital-Billing\",\"shipping_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"billing_address\":\"8848 Digital-Billing\",\"billing_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"tc_name\":\"_Test Terms and Conditions\",\"terms\":\"_Test Terms\",\"status\":\"Draft\",\"per_billed\":0,\"per_returned\":0,\"group_same_items\":0,\"language\":\"en\",\"is_internal_supplier\":0,\"represents_company\":\"\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Receipt\",\"pricing_rules\":[],\"items\":[{\"name\":\"eii052sqhn\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 13:03:13.641668\",\"modified\":\"2024-09-30 13:04:46.213573\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"_Test Item\",\"item_name\":\"_Test Item\",\"description\":\"_Test Item 1\",\"item_group\":\"_Test Item Group\",\"image\":\"\",\"received_qty\":5,\"qty\":5,\"rejected_qty\":0,\"uom\":\"_Test UOM\",\"stock_uom\":\"_Test UOM\",\"conversion_factor\":1,\"retain_sample\":0,\"sample_quantity\":0,\"received_stock_qty\":5,\"stock_qty\":5,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":500,\"amount\":2500,\"base_rate\":500,\"base_amount\":2500,\"stock_uom_rate\":500,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":500,\"net_amount\":2500,\"base_net_rate\":500,\"base_net_amount\":2500,\"valuation_rate\":500,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"rate_difference_with_purchase_invoice\":0,\"billed_amt\":0,\"warehouse\":\"Stores - 8D\",\"material_request\":\"MAT-MR-2024-00002\",\"purchase_order\":\"PUR-ORD-2024-00006\",\"allow_zero_valuation_rate\":0,\"return_qty_from_rejected_warehouse\":0,\"is_fixed_asset\":0,\"schedule_date\":\"2024-09-30\",\"material_request_item\":\"9gnuckf7ad\",\"purchase_order_item\":\"eie3plm9h3\",\"use_serial_batch_fields\":1,\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"expense_account\":\"Cost of Goods Sold - 8D\",\"item_tax_rate\":\"{}\",\"project\":\"PROJ-0001\",\"cost_center\":\"Main - 8D\",\"page_break\":0,\"parent\":\"MAT-PRE-2024-00002\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"doctype\":\"Purchase Receipt Item\"},{\"name\":\"eii0ai3sbs\",\"owner\":\"Administrator\",\"creation\":\"2024-09-30 13:03:13.641668\",\"modified\":\"2024-09-30 13:04:46.213573\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"has_item_scanned\":0,\"item_code\":\"_Test Item Home Desktop 100\",\"item_name\":\"_Test Item Home Desktop 100\",\"description\":\"_Test Item Home Desktop 100 3\",\"item_group\":\"_Test Item Group Desktops\",\"image\":\"\",\"received_qty\":2,\"qty\":2,\"rejected_qty\":0,\"uom\":\"_Test UOM 1\",\"stock_uom\":\"_Test UOM 1\",\"conversion_factor\":1,\"retain_sample\":0,\"sample_quantity\":0,\"received_stock_qty\":2,\"stock_qty\":2,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":800,\"amount\":1600,\"base_rate\":800,\"base_amount\":1600,\"stock_uom_rate\":800,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":800,\"net_amount\":1600,\"base_net_rate\":800,\"base_net_amount\":1600,\"valuation_rate\":800,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"rate_difference_with_purchase_invoice\":0,\"billed_amt\":0,\"warehouse\":\"Stores - 8D\",\"material_request\":\"MAT-MR-2024-00002\",\"purchase_order\":\"PUR-ORD-2024-00006\",\"allow_zero_valuation_rate\":0,\"return_qty_from_rejected_warehouse\":0,\"is_fixed_asset\":0,\"schedule_date\":\"2024-09-30\",\"material_request_item\":\"9gnuftv32n\",\"purchase_order_item\":\"eie3dlit00\",\"use_serial_batch_fields\":1,\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"expense_account\":\"Cost of Goods Sold - 8D\",\"item_tax_rate\":\"{}\",\"project\":\"PROJ-0001\",\"cost_center\":\"Main - 8D\",\"page_break\":0,\"parent\":\"MAT-PRE-2024-00002\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"doctype\":\"Purchase Receipt Item\"}],\"supplied_items\":[],\"taxes\":[],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\"},\"__last_sync_on\":\"2024-09-30T09:26:19.322Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370070139320064469151": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 9963,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "AmbiguousColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn reference \\\"modified\\\" is ambiguous\\nLINE 1: ...(abs(\\\"tabPurchase Receipt Item\\\".qty)) as qty, MAX(modified) ...\\n                                                             ^\\n\"]"
}
```

**Comment by nilesh8848** [comment]
Resolved with another fix
