### ISSUE TITLE
Prevents the system from showing the user list for project access on the website.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#232]
### Information about bug

Prevents the system from showing the list of users who should have access to the project on the website.
![image](https://github.com/user-attachments/assets/e67b5adb-c7bb-4b4b-8633-1122f777c8b3)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Project/PROJ-11-10-24-0001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/projects/doctype/project/project.py", line 462, in get_users_for_project
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Guest" does not exist
LINE 4:    and name not in ("Guest", "Administrator")
                            ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "User",
		"ignore_user_permissions": 0,
		"reference_doctype": "Project User",
		"page_length": 10,
		"query": "erpnext.projects.doctype.project.project.get_users_for_project"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"Guest\\\" does not exist\\nLINE 4:    and name not in (\\\"Guest\\\", \\\"Administrator\\\")\\n                            ^\\n\"]"
}
```
```

**Comment by Prateek8848** [comment]
https://github.com/8848digital/erpnext/pull/234

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
