### ISSUE TITLE
Syntax error in query:\nshow index from "tabItem"

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#236]
### Information about bug

test_index_creation (erpnext.stock.doctype.item.test_item.TestItem)
check if index is getting created in db

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 640, in test_index_creation
    indices = frappe.db.sql("show index from tabItem", as_dict=1)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "from"
LINE 1: show index from "tabItem"
                   ^
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
