### ISSUE TITLE
Syntax error in query:\nselect * from "tabStock Ledger Entry"  where "item_code"=%s and "warehouse"=%s\n\t\torder by timestamp(posting_date, posting_time) desc, creation desc limit 1 [\'_Test Item 2\', \'_Test Warehouse - _TC\']

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#238]
### Information about bug

test_fifo (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/test_stock_entry.py", line 66, in test_fifo
    sle = get_sle(item_code=item_code, warehouse=warehouse)[0]
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/test_stock_entry.py", line 42, in get_sle
    return frappe.db.sql(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "posting_date"
LINE 2:   order by timestamp(posting_date, posting_time) desc, creat...
```

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
