### ISSUE TITLE
Syntax error in query: to get future stock vouchers

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#239]
### Information about bug

test_closed_delivery_note (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/test_delivery_note.py", line 895, in test_closed_delivery_note
    dn.cancel()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1053, in cancel
    return self._cancel()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1036, in _cancel
    return self.save()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1133, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 501, in on_cancel
    self.repost_future_sle_and_gle()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 1262, in repost_future_sle_and_gle
    create_item_wise_repost_entries(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 1674, in create_item_wise_repost_entries
    repost_entry.submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 202, in on_submit
    repost(self)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 272, in repost
    repost_gl_entries(doc)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 360, in repost_gl_entries
    directly_dependent_transactions = _get_directly_dependent_vouchers(doc)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 392, in _get_directly_dependent_vouchers
    affected_vouchers = get_future_stock_vouchers(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 1393, in get_future_stock_vouchers
    future_stock_vouchers = frappe.db.sql(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "sle"
LINE 4:    timestamp(sle.posting_date, sle.posting_time) >= timestam...
```

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
