### ISSUE TITLE
While linking advance payment to sales invoice, after submittion showing outstanding in negative.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#240]
### Information about bug

Step - 
Create sales order
create payment entry from sales order
create sales invoice from sales order
while creating sales invoice in payment tab link advance payment 
after submission of sales invoice outstanding amount should get 0 if it is fully paid but it is showing in negative 
In payment entry outstanding amount is showing in positive. 

![image](https://github.com/user-attachments/assets/6345dfb9-4135-4a1c-91a1-982889ec684f)
![image](https://github.com/user-attachments/assets/d379285b-d784-4f7d-816d-08eb6a1c42cf)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by shubham-DT** [comment]
This issue is linked with issue 224
check once

**Comment by aasif-patel** [comment]
https://github.com/8848digital/erpnext/issues/224

**Comment by tinadn** [comment]
@shubham-DT 
![image](https://github.com/user-attachments/assets/1107ae87-e20b-444f-bad1-666db8383cbd)
### App Versions
```
{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00120
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 113, in on_submit
    self.update_advance_paid()  # advance_paid_status depends on the payment request amount
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1476, in update_advance_paid
    ).set_total_advance_paid()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1977, in set_total_advance_paid
    self.set_advance_payment_status()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1981, in set_advance_payment_status
    paid_amount = frappe.get_value(
  File "apps/frappe/frappe/__init__.py", line 2079, in get_value
    return db.get_value(*args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 515, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 619, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 892, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Request.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...SAL-ORD-2024-09481' AND "docstatus"= '1' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PAY-2024-00119\",\"owner\":\"Administrator\",\"creation\":\"2024-11-27 16:14:53.285667\",\"modified\":\"2024-11-27 16:14:53.522730\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Receive\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-11-27\",\"company\":\"PP Ltd\",\"mode_of_payment\":\"Cash\",\"party_type\":\"Customer\",\"party\":\"Ashish\",\"party_name\":\"Ashish\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"bank_account\":null,\"party_bank_account\":null,\"contact_person\":null,\"contact_email\":null,\"party_balance\":270960,\"paid_from\":\"Debtors - PP Ltd\",\"paid_from_account_type\":\"Receivable\",\"paid_from_account_currency\":\"INR\",\"paid_from_account_balance\":0,\"paid_to\":\"Cash - PP Ltd\",\"paid_to_account_type\":\"Cash\",\"paid_to_account_currency\":\"INR\",\"paid_to_account_balance\":44051,\"paid_amount\":2000,\"paid_amount_after_tax\":2000,\"source_exchange_rate\":1,\"base_paid_amount\":2000,\"base_paid_amount_after_tax\":2000,\"received_amount\":2000,\"received_amount_after_tax\":2000,\"target_exchange_rate\":1,\"base_received_amount\":2000,\"base_received_amount_after_tax\":2000,\"total_allocated_amount\":2000,\"base_total_allocated_amount\":2000,\"unallocated_amount\":0,\"difference_amount\":0,\"purchase_taxes_and_charges_template\":null,\"sales_taxes_and_charges_template\":null,\"apply_tax_withholding_amount\":0,\"tax_withholding_category\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_no\":null,\"reference_date\":\"2024-11-27\",\"clearance_date\":null,\"location\":null,\"project\":null,\"department\":null,\"purchase_invoice\":null,\"cost_center\":null,\"status\":\"Draft\",\"custom_remarks\":0,\"remarks\":\"Amount INR 2000 received from Ashish\\nAmount INR 2000 against Sales Order SAL-ORD-2024-09481\",\"base_in_words\":\"INR Two Thousand only.\",\"is_opening\":\"No\",\"letter_head\":\"PP Ltd\",\"print_heading\":null,\"bank\":null,\"bank_account_no\":null,\"payment_order\":null,\"in_words\":\"INR Two Thousand only.\",\"auto_repeat\":null,\"amended_from\":null,\"title\":\"Ashish\",\"doctype\":\"Payment Entry\",\"taxes\":[],\"references\":[{\"name\":\"bcbl2p6iha\",\"owner\":\"Administrator\",\"creation\":\"2024-11-27 16:14:53.285667\",\"modified\":\"2024-11-27 16:14:53.432186\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"reference_doctype\":\"Sales Order\",\"reference_name\":\"SAL-ORD-2024-09481\",\"due_date\":null,\"bill_no\":null,\"payment_term\":null,\"payment_term_outstanding\":0,\"account_type\":null,\"payment_type\":null,\"total_amount\":2000,\"outstanding_amount\":2000,\"allocated_amount\":2000,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"account\":\"Debtors - PP Ltd\",\"payment_request\":null,\"payment_request_outstanding\":0,\"parent\":\"ACC-PAY-2024-00119\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"doctype\":\"Payment Entry Reference\",\"__unsaved\":1}],\"deductions\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-11-27T10:44:53.742Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370052652443723185761": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 28619,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPayment Request.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...SAL-ORD-2024-09481' AND \\\"docstatus\\\"= '1' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```

**Comment by shubham-DT** [comment]
tested successfully 
we can close this issue

**Comment by tinadn** [comment]
Resolved. Hence closing.
