### ISSUE TITLE
Syntax error in query: fetch back_dated_entry in select query

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#242]
### Information about bug

test_back_dated_entry_not_allowed (erpnext.stock.doctype.stock_ledger_entry.test_stock_ledger_entry.TestStockLedgerEntry)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/test_stock_ledger_entry.py", line 428, in test_back_dated_entry_not_allowed
    stock_entry_on_today = make_stock_entry(target="_Test Warehouse - _TC", qty=10, basic_rate=100)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry_utils.py", line 194, in make_stock_entry
    s.submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 245, in on_submit
    self.update_stock_ledger()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1354, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 869, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 97, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 226, in make_entry
    sle.submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1094, in run_before_save_methods
    self.run_method("validate")
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 93, in validate
    self.validate_with_last_transaction_posting_time()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 313, in validate_with_last_transaction_posting_time
    last_transaction_time = frappe.db.sql(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: ...((posting_date || ' ' || posting_time)::timestamp)) as posti...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/test_stock_ledger_entry.py", line 453, in test_back_dated_entry_not_allowed
    frappe.db.set_single_value(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 801, in set_single_value
    frappe.db.delete(
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 1266, in delete
    return query.run(**kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
