### ISSUE TITLE
Material Request: When you click on Stop button getting an error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#25]
### Information about bug

Material request - When you click on Stop button getting an error
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
Possible source of error: erpnext (app)
![image](https://github.com/user-attachments/assets/59c5bf8b-e8b8-4432-9bff-432073a71ffd)

### Module

stock

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.41.0 (version-15)

Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Material Request/MAT-MR-2024-00002
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 407, in update_status
    material_request.update_status(status)
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 197, in update_status
    self.check_modified_date()
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 191, in check_modified_date
    date_diff = frappe.db.sql(f"""select TIMEDIFF('{mod_db[0][0]}', '{cstr(self.modified)}')""")
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function timediff(unknown, unknown) does not exist
LINE 1: select TIMEDIFF('2024-09-25 11:56:38.562703', '2024-09-25 11...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"name": "MAT-MR-2024-00002",
		"status": "Stopped"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.doctype.material_request.material_request.update_status",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedFunction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfunction timediff(unknown, unknown) does not exist\\nLINE 1: select TIMEDIFF('2024-09-25 11:56:38.562703', '2024-09-25 11...\\n               ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
Issue is resolved
PR - 47

**Comment by 8848swa** [comment]
Just checked getting same error. Pls. check.
![image](https://github.com/user-attachments/assets/33e5ca60-2d37-4724-8905-9e35766d5f12)

**Comment by shubham-DT** [comment]
please migrate the test site once again ..may be its facing the server problem like yesterday

**Comment by aasif-patel** [comment]
Resolved, Hence Closing...

**Comment by aasif-patel** [comment]
@8848swa now you can check, Don't check Opened issue again checked it once closed.
