### ISSUE TITLE
Server Error while submitting a Purchase Order 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#254]
### Information about bug

![image](https://github.com/user-attachments/assets/b501d31c-3e3b-4015-af53-05f010328fab)

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Order/new-purchase-order-xxlwgiiudf
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 198, in validate
    self.set_tax_withholding()
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 266, in set_tax_withholding
    tax_withholding_details = get_party_tax_withholding_details(self, self.tax_withholding_category)
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 142, in get_party_tax_withholding_details
    tax_amount, tax_deducted, tax_deducted_on_advances, voucher_wise_amount = get_tax_amount(
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 322, in get_tax_amount
    tax_amount = get_tds_amount(ldc, parties, inv, tax_details, vouchers)
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 514, in get_tds_amount
    supp_credit_amt = frappe.db.get_value("Purchase Invoice", invoice_filters, field) or 0.0
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPurchase Invoice.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...HERE "name" IN ('') AND "docstatus"= '1' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Order\",\"name\":\"new-purchase-order-xxlwgiiudf\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"title\":\"{supplier_name}\",\"naming_series\":\"PUR-ORD-.YYYY.-\",\"transaction_date\":\"2024-10-14\",\"company\":\"PP Ltd\",\"apply_tds\":1,\"is_subcontracted\":0,\"currency\":\"INR\",\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Order Item\",\"name\":\"new-purchase-order-item-sgdpxwtvva\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"fg_item_qty\":1,\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"apply_tds\":1,\"delivered_by_supplier\":0,\"against_blanket_order\":null,\"include_exploded_items\":0,\"is_fixed_asset\":0,\"page_break\":0,\"parent\":\"new-purchase-order-xxlwgiiudf\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Order\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"last_purchase_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":25000,\"amount\":25000,\"base_rate\":25000,\"base_amount\":25000,\"stock_uom_rate\":25000,\"net_rate\":25000,\"net_amount\":25000,\"base_net_rate\":25000,\"base_net_amount\":25000,\"actual_qty\":0,\"company_total_stock\":0,\"blanket_order_rate\":0,\"received_qty\":0,\"returned_qty\":0,\"billed_amt\":0,\"weight_per_unit\":0,\"total_weight\":0,\"item_code\":\"Professional fees\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Professional fees\",\"description\":\"Professional fees\",\"image\":\"\",\"warehouse\":null,\"income_account\":\"Sales - PP Ltd\",\"expense_account\":\"Cost of Goods Sold - PP Ltd\",\"discount_account\":null,\"provisional_expense_account\":null,\"cost_center\":\"Main - PP Ltd\",\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"transaction_date\":\"2024-10-14\",\"bom_no\":null,\"grant_commission\":1,\"item_group\":\"8848\",\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"supplier_part_no\":null,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-purchase-order-item-sgdpxwtvva\",\"schedule_date\":\"2024-10-31\"}],\"tax_withholding_net_total\":0,\"pricing_rules\":[],\"supplied_items\":[],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"payment_schedule\":[],\"status\":\"Draft\",\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"is_internal_supplier\":0,\"party_account_currency\":\"INR\",\"is_old_subcontracting_flow\":0,\"advance_paid\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"base_net_total\":25000,\"net_total\":25000,\"base_total\":25000,\"total\":25000,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":25000,\"taxes_and_charges_deducted\":0,\"taxes_and_charges_added\":0,\"base_grand_total\":25000,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":25000,\"base_rounded_total\":25000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"supplier_name\":\"KV & Associates\",\"represents_company\":\"\",\"supplier\":\"KV & Associates\",\"supplier_address\":null,\"address_display\":null,\"billing_address\":\"PP-MH-Billing\",\"billing_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"shipping_address\":\"PP-MH-Billing\",\"shipping_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"tax_category\":\"\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"payment_terms_template\":null,\"total_net_weight\":0,\"tax_withholding_category\":\"TDS 194JB\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700096123480889758641": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 9967,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPurchase Invoice.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...HERE \\\"name\\\" IN ('') AND \\\"docstatus\\\"= '1' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
