### ISSUE TITLE
Server error while submitting Purchase Invoice

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#255]
### Information about bug

![image](https://github.com/user-attachments/assets/484ca6bd-84cb-4fa5-a711-f39c32171834)

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/new-purchase-invoice-wvuhiczykn
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 261, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 32, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 56, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 258, in validate
    self.set_tax_withholding()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 1719, in set_tax_withholding
    tax_withholding_details, advance_taxes, voucher_wise_amount = get_party_tax_withholding_details(
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 142, in get_party_tax_withholding_details
    tax_amount, tax_deducted, tax_deducted_on_advances, voucher_wise_amount = get_tax_amount(
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 322, in get_tax_amount
    tax_amount = get_tds_amount(ldc, parties, inv, tax_details, vouchers)
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 514, in get_tds_amount
    supp_credit_amt = frappe.db.get_value("Purchase Invoice", invoice_filters, field) or 0.0
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPurchase Invoice.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...HERE "name" IN ('') AND "docstatus"= '1' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Invoice\",\"name\":\"new-purchase-invoice-wvuhiczykn\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"ACC-PINV-.YYYY.-\",\"company\":\"PP Ltd\",\"posting_date\":\"2024-10-14\",\"set_posting_time\":0,\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":1,\"currency\":\"INR\",\"use_transaction_date_exchange_rate\":0,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"update_stock\":0,\"is_subcontracted\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Invoice Item\",\"name\":\"new-purchase-invoice-item-vtjfmjtqwb\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"apply_tds\":1,\"use_serial_batch_fields\":1,\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"include_exploded_items\":0,\"cost_center\":\"Main - PP Ltd\",\"page_break\":0,\"parent\":\"new-purchase-invoice-wvuhiczykn\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"idx\":1,\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":25000,\"amount\":25000,\"base_rate\":25000,\"base_amount\":25000,\"stock_uom_rate\":25000,\"net_rate\":25000,\"net_amount\":25000,\"base_net_rate\":25000,\"base_net_amount\":25000,\"valuation_rate\":0,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"weight_per_unit\":0,\"total_weight\":0,\"item_name\":\"Professional fees\",\"item_group\":\"8848\",\"asset_category\":null,\"item_code\":\"Professional fees\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"description\":\"Professional fees\",\"image\":\"\",\"warehouse\":null,\"income_account\":\"Sales - PP Ltd\",\"expense_account\":\"Cost of Goods Sold - PP Ltd\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"delivered_by_supplier\":0,\"last_purchase_rate\":null,\"transaction_date\":\"2024-10-14\",\"against_blanket_order\":null,\"bom_no\":null,\"grant_commission\":1,\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"supplier_part_no\":null,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-purchase-invoice-item-vtjfmjtqwb\"}],\"tax_withholding_net_total\":0,\"taxes\":[],\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"tax_withheld_vouchers\":[],\"pricing_rules\":[],\"supplied_items\":[],\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"advances\":[],\"advance_tax\":[],\"ignore_default_payment_terms_template\":0,\"payment_schedule\":[],\"status\":\"Draft\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"on_hold\":0,\"is_internal_supplier\":0,\"represents_company\":\"\",\"is_old_subcontracting_flow\":0,\"posting_time\":\"14:51:43\",\"conversion_rate\":1,\"plc_conversion_rate\":1,\"credit_to\":\"Creditors - PP Ltd\",\"base_net_total\":25000,\"net_total\":25000,\"base_total\":25000,\"total\":25000,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":25000,\"taxes_and_charges_deducted\":0,\"taxes_and_charges_added\":0,\"base_grand_total\":25000,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":25000,\"base_rounded_total\":25000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"supplier_name\":\"KV & Associates\",\"tax_id\":null,\"supplier_group\":\"PP Ltd Suppliers\",\"supplier\":\"KV & Associates\",\"due_date\":\"2024-10-14\",\"supplier_address\":null,\"address_display\":null,\"billing_address\":\"8848 Digital-Billing\",\"billing_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"shipping_address\":\"PP - GJ-Billing\",\"shipping_address_display\":\"002<br>\\nSurat<br>\\nGujrat<br>395003<br>India<br>\\n<br>\\n\",\"tax_category\":\"\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"payment_terms_template\":null,\"tax_withholding_category\":\"TDS 194JB\",\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":25000,\"bill_no\":\"48787\",\"bill_date\":\"2024-10-01\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700180803314336400071": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 7774,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_server_messages": "[\"{\\\"message\\\": \\\"Row 1: Expense Head changed to <strong>Stock Received But Not Billed - PP Ltd</strong> as no Purchase Receipt is created against Item <strong>Professional fees</strong>.<br>This is done to handle accounting for cases when Purchase Receipt is created after Purchase Invoice\\\", \\\"title\\\": \\\"Expense Head Changed\\\"}\"]",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPurchase Invoice.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...HERE \\\"name\\\" IN ('') AND \\\"docstatus\\\"= '1' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Issue is linked with #254
