### ISSUE TITLE
Error while generating the Bank Reconciliation Statement Report

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#266]
### Information about bug

Open the Bank Reconciliation Report and refresh it, then error will be occur

![Screenshot from 2024-10-15 12-24-42](https://github.com/user-attachments/assets/94f14997-9e76-4496-be44-7ac484de6e4c)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py", line 23, in execute
    data = get_entries(filters)
  File "apps/erpnext/erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py", line 113, in get_entries
    entries += frappe.get_attr(method_name)(filters) or []
  File "apps/erpnext/erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py", line 122, in get_entries_for_bank_reconciliation_statement
    journal_entries = get_journal_entries(filters)
  File "apps/erpnext/erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py", line 134, in get_journal_entries
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Journal Entry" does not exist
LINE 1: select "Journal Entry" as payment_document, jv.posting_date,
               ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 76, in log_error
    return error_log.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 279, in insert
    self._set_defaults()
  File "apps/frappe/frappe/model/document.py", line 783, in _set_defaults
    new_doc = frappe.new_doc(self.doctype, as_dict=True)
  File "apps/frappe/frappe/__init__.py", line 1197, in new_doc
    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "apps/frappe/frappe/model/create_new.py", line 22, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "apps/frappe/frappe/model/create_new.py", line 44, in make_new_doc
    if not frappe.model.meta.is_single(doctype):
  File "apps/frappe/frappe/model/meta.py", line 727, in is_single
    return frappe.db.get_value("DocType", doctype, "issingle")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
