### ISSUE TITLE
Error while creating a new customer when assigning a lead. Lead - "CRM-LEAD-2024-00001" 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#268]
### Information about bug

![image](https://github.com/user-attachments/assets/441b9f16-0bd4-457d-ba42-470a725cbe4f)
Lead - "CRM-LEAD-2024-00001" - Use this value to reproduce the error. 

### Module

selling, CRM

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-kywoqtkpuv
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 104, in autoname
    self.name = self.get_customer_name()
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 112, in get_customer_name
    count = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedObject: type "unsigned" does not exist
LINE 1: ...alesce(MAX(CAST(SUBSTRING_INDEX(name, ' ', -1) AS UNSIGNED))...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-uwgsgdxajr\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"is_internal_customer\":0,\"companies\":[],\"language\":\"en\",\"credit_limits\":[],\"accounts\":[],\"sales_team\":[],\"so_required\":0,\"dn_required\":0,\"is_frozen\":0,\"disabled\":0,\"portal_users\":[],\"customer_name\":\"_Test Lead 4\",\"lead_name\":\"CRM-LEAD-2024-00001\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370054234707832857981": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 13064,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedObject",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ntype \\\"unsigned\\\" does not exist\\nLINE 1: ...alesce(MAX(CAST(SUBSTRING_INDEX(name, ' ', -1) AS UNSIGNED))...\\n                                                             ^\\n\"]"
}
```
```

**Comment by Prateek8848** [comment]
https://github.com/8848digital/erpnext/pull/269

**Comment by tinadn** [comment]
Working fine. Hence closing.
