### ISSUE TITLE
'Error in query:\ntype "unsigned" does not exist

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#270]
### Information about bug

Error : test_duplicate_customer (erpnext.selling.doctype.customer.test_customer.TestCustomer)

### Module

CRM

### Version

Erpnext: v15

Frappe: v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 211, in run_tests_for_doctype
    make_test_records(doctype, verbose=verbose, force=force, commit=True)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 344, in make_test_records
    make_test_records(options, verbose, force, commit=commit)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 345, in make_test_records
    make_test_records_for_doctype(options, verbose, force, commit=commit)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 399, in make_test_records_for_doctype
    frappe.local.test_objects[doctype] += make_test_objects(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 444, in make_test_objects
    d.set_new_name()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 104, in autoname
    self.name = self.get_customer_name()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 112, in get_customer_name
    count = frappe.db.sql(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedObject: type "unsigned" does not exist
LINE 1: ...alesce(MAX(CAST(SUBSTRING_INDEX(name, ' ', -1) AS UNSIGNED))...
```

**Comment by tinadn** [comment]
This issue is linked with #268
