### ISSUE TITLE
While applying filter of Order type against the Sales order in Sales Analytics Report showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#273]
### Information about bug

![image](https://github.com/user-attachments/assets/cf6cc36c-0ab5-4c4a-9248-5eb53220f170)
![image](https://github.com/user-attachments/assets/40687228-4676-4886-a647-2167f52fcd98)

### Module

selling

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Sales Analytics
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/sales_invoice_trends/sales_invoice_trends.py", line 13, in execute
    data = get_data(filters, conditions)
  File "apps/erpnext/erpnext/controllers/trends.py", line 211, in get_data
    des[j + inc] = row1[0][j]
IndexError: list index out of range

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Sales Invoice Trends",
		"filters": "{\"period\":\"Monthly\",\"based_on\":\"Customer\",\"group_by\":\"Item\",\"fiscal_year\":\"2024-2025\",\"company\":\"8848 Digital\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
