### ISSUE TITLE
Errors in Test Accounting Dimension 

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#282]
### Information about bug

**ERROR: test_dimension_against_journal_entry** (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)

======================================================================
**ERROR: test_dimension_against_sales_invoice** (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)

======================================================================
**ERROR: test_mandatory** (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
aarti@Latitude-7300:~/postgres/frappe-bench-postgres/apps/erpnext$ bench run-tests --doctype "Accounting Di
mension"
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 587, in run
    self._callSetUp()
  File "/usr/lib/python3.10/unittest/case.py", line 546, in _callSetUp
    self.setUp()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 103, in create_dimension
    dimension.insert()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py", line 82, in after_insert
    make_dimension_in_accounting_doctypes(doc=self)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py", line 111, in make_dimension_in_accounting_doctypes
    repostable_doctypes = get_allowed_types_from_settings()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/repost_accounting_ledger/repost_accounting_ledger.py", line 185, in get_allowed_types_from_settings
    for x in frappe.db.get_all(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 754, in get_all
    return frappe.get_all(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\nfor SELECT DISTINCT, ORDER BY expressions must appear in select list\nLINE 5:     order by "tabRepost Allowed Types"."modified" DESC\n                     ^\n'
E  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 587, in run
    self._callSetUp()
  File "/usr/lib/python3.10/unittest/case.py", line 546, in _callSetUp
    self.setUp()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 88, in create_dimension
    if not frappe.db.exists("Accounting Dimension", {"document_type": "Department"}):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 1123, in exists
    return self.get_value(dt, dn, ignore=True, cache=cache, order_by=None)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncurrent transaction is aborted, commands ignored until end of transaction block\n'
E  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 587, in run
    self._callSetUp()
  File "/usr/lib/python3.10/unittest/case.py", line 546, in _callSetUp
    self.setUp()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 88, in create_dimension
    if not frappe.db.exists("Accounting Dimension", {"document_type": "Department"}):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 1123, in exists
    return self.get_value(dt, dn, ignore=True, cache=cache, order_by=None)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncurrent transaction is aborted, commands ignored until end of transaction block\n'
E
======================================================================
ERROR: test_dimension_against_journal_entry (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 103, in create_dimension
    dimension.insert()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py", line 82, in after_insert
    make_dimension_in_accounting_doctypes(doc=self)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py", line 111, in make_dimension_in_accounting_doctypes
    repostable_doctypes = get_allowed_types_from_settings()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/repost_accounting_ledger/repost_accounting_ledger.py", line 185, in get_allowed_types_from_settings
    for x in frappe.db.get_all(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 754, in get_all
    return frappe.get_all(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 5:     order by "tabRepost Allowed Types"."modified" DESC
                     ^


======================================================================
ERROR: test_dimension_against_sales_invoice (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 88, in create_dimension
    if not frappe.db.exists("Accounting Dimension", {"document_type": "Department"}):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 1123, in exists
    return self.get_value(dt, dn, ignore=True, cache=cache, order_by=None)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


======================================================================
ERROR: test_mandatory (erpnext.accounts.doctype.accounting_dimension.test_accounting_dimension.TestAccountingDimension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 16, in setUp
    create_dimension()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/accounting_dimension/test_accounting_dimension.py", line 88, in create_dimension
    if not frappe.db.exists("Accounting Dimension", {"document_type": "Department"}):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 1123, in exists
    return self.get_value(dt, dn, ignore=True, cache=cache, order_by=None)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


----------------------------------------------------------------------
Ran 3 tests in 0.253s

FAILED (errors=3)
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
