### ISSUE TITLE
Report Bank Clearence Summary - error while generating Bank Clearence Summary 

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#284]
### Information about bug

go to the Bank Clearence Summary  report and refresh it, then error will show

![Screenshot from 2024-10-16 11-29-14](https://github.com/user-attachments/assets/837412eb-1af7-4204-87ee-4bbe47448099)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py", line 15, in execute
    data = get_entries(filters)
  File "apps/erpnext/erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py", line 68, in get_entries
    frappe.get_attr(method_name)(
  File "apps/erpnext/erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py", line 85, in get_entries_for_bank_clearance_summary
    journal_entries = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Journal Entry" does not exist
LINE 2:    "Journal Entry", jv.name, jv.posting_date, jv.cheque_no,
           ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 135, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 133, in __init__
    self._table_fieldnames = {df.fieldname for df in self._get_table_fields()}
  File "apps/frappe/frappe/model/base_document.py", line 345, in _get_table_fields
    return self.meta.get_table_fields()
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/model/base_document.py", line 142, in meta
    return frappe.get_meta(self.doctype)
  File "apps/frappe/frappe/__init__.py", line 1367, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 63, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 167, in load_from_db
    d = frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
