### ISSUE TITLE
Error in query:\ndate/time field value out of range

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#289]
### Information about bug

ERROR: test_prices_at_invalid_date (erpnext.stock.doctype.item_price.test_item_price.TestItemPrice)

### Module

stock

### Version

Frappe version - v15
Erpnext version - v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/doctype/item_price/test_item_price.py", line 124, in test_prices_at_invalid_date
    price = get_price_list_rate_for(args, doc.item_code)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 956, in get_price_list_rate_for
    price_list_rate = get_item_price(item_price_args, item_code)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 933, in get_item_price
    return query.run()
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/eight848-digital/postgresql/frappe-bench/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "01-15-2019"
LINE 1: ...",'')='' AND coalesce("valid_from",'2000-01-01')<='01-15-201...
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
