### ISSUE TITLE
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by Satya8848** [8848digital/erpnext#302]
### Information about bug

psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
Possible source of error: Server Script

### Module

selling

### Version

erpnext": "15.34.0",
frappe": "15.41.0",
payments": "0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
List/Sales Invoice/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 71, in execute_cmd
    return run_server_script(server_script)
  File "apps/frappe/frappe/handler.py", line 89, in run_server_script
    response = frappe.get_doc("Server Script", server_script).execute_method()
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 161, in execute_method
    return execute_api_server_script(self)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 297, in execute_api_server_script
    _globals, _locals = safe_exec(script.script, script_filename=script.name)
  File "apps/frappe/frappe/utils/safe_exec.py", line 111, in safe_exec
    exec(
  File "<serverscript>: sales_invoice", line 16, in <module>
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 271, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 71, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 329, in parse_naming_series
    part = number_generator(name, digits)
  File "apps/frappe/frappe/model/naming.py", line 381, in getseries
    current = (frappe.qb.from_(series).where(series.name == key).for_update().select("current")).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"invoice_names": "ACC-SINV-2024-31904"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/duplicate_invoices",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SerializationFailure",
	"_exc_source": "Server Script",
	"_server_messages": "[\"{\\\"message\\\": \\\"ACC-SINV-2024-31904\\\", \\\"title\\\": \\\"Message\\\"}\"]",
	"_debug_messages": "[\"Error in query:\\ncould not serialize access due to concurrent update\\n\"]"
}
```
```

**Comment by tinadn** [comment]
This issue is reolved by pr #293

**Comment by vinod-8848digital** [comment]
discussed with @Satya8848 , its fixed hence closing
