### ISSUE TITLE
While enabling check box of Show GL Balance in Accounts Receivable Summary Report Showing Error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#308]
### Information about bug

![image](https://github.com/user-attachments/assets/30557997-20f6-4453-9681-f65d175c62e4)
![image](https://github.com/user-attachments/assets/1b9f5476-f7a7-4911-8035-f48737a7a259)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Accounts Receivable Summary
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/account/account.py", line 572, in merge_account
    frappe.rename_doc("Account", old, new, merge=1, force=1)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1469, in rename_doc
    return rename_doc(
  File "apps/frappe/frappe/model/rename_doc.py", line 164, in rename_doc
    new = validate_rename(
  File "apps/frappe/frappe/model/rename_doc.py", line 359, in validate_rename
    exists = frappe.qb.from_(doctype).where(Field("name") == new).for_update().select("name").run(pluck=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"old": "Debtors - PP Ltd",
		"new": "Customer - PP Ltd"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.account.account.merge_account",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SerializationFailure",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncould not serialize access due to concurrent update\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
Issue resolved 
PR 311
