### ISSUE TITLE
While clicking on customer name - Indra in Customer Doctype showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#315]
### Information about bug

![image](https://github.com/user-attachments/assets/34d0ae9e-6faa-4c19-9e23-bc0f1c3a7b8e)

### Module

selling

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Customer/Indra
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/load.py", line 45, in getdoc
    run_onload(doc)
  File "apps/frappe/frappe/desk/form/load.py", line 351, in run_onload
    doc.run_method("onload")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 95, in onload
    self.load_dashboard_info()
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 98, in load_dashboard_info
    info = get_dashboard_info(self.doctype, self.name, self.loyalty_program)
  File "apps/erpnext/erpnext/accounts/party.py", line 788, in get_dashboard_info
    loyalty_point_details = frappe._dict(
ValueError: dictionary update sequence element #0 has length 3; 2 is required

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Customer",
		"name": "Indra"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: dictionary update sequence element #0 has length 3; 2 is required",
	"exc_type": "ValueError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by shubham-DT** [comment]
This is working fine 
please test it again
