### ISSUE TITLE
Error in Test Ledger Health

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#317]
### Information about bug

ERROR: test_debit_credit_mismatch (erpnext.accounts.doctype.ledger_health.test_ledger_health.TestLedgerHealth)

---------------------------------------------------------------------------------------------------------------------------------

ERROR: test_gl_and_pl_mismatch (erpnext.accounts.doctype.ledger_health.test_ledger_health.TestLedgerHealth)

### Module

accounts

### Version

Frappe v15
Erpnext v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
aarti@Latitude-7300:~/postgres/frappe-bench-postgres/apps/erpnext$ bench run-tests --doctype "Ledger Health"
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/ledger_health/test_ledger_health.py", line 66, in test_debit_credit_mismatch
    run_ledger_health_checks()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/utils.py", line 2128, in run_ledger_health_checks
    res = voucher_wise.execute_script_report(filters=filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 11, in execute
    data = get_data(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 51, in get_data
    gl_entries = query.run(as_dict=True)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "tabGL Entry.voucher_type" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT "voucher_type","voucher_no",SUM("debit") "debit",SUM(...\n               ^\n'
E  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/ledger_health/test_ledger_health.py", line 92, in test_gl_and_pl_mismatch
    run_ledger_health_checks()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/utils.py", line 2128, in run_ledger_health_checks
    res = voucher_wise.execute_script_report(filters=filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 11, in execute
    data = get_data(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 51, in get_data
    gl_entries = query.run(as_dict=True)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "tabGL Entry.voucher_type" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT "voucher_type","voucher_no",SUM("debit") "debit",SUM(...\n               ^\n'
E
======================================================================
ERROR: test_debit_credit_mismatch (erpnext.accounts.doctype.ledger_health.test_ledger_health.TestLedgerHealth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/ledger_health/test_ledger_health.py", line 66, in test_debit_credit_mismatch
    run_ledger_health_checks()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/utils.py", line 2128, in run_ledger_health_checks
    res = voucher_wise.execute_script_report(filters=filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 11, in execute
    data = get_data(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 51, in get_data
    gl_entries = query.run(as_dict=True)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabGL Entry.voucher_type" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "voucher_type","voucher_no",SUM("debit") "debit",SUM(...
               ^


======================================================================
ERROR: test_gl_and_pl_mismatch (erpnext.accounts.doctype.ledger_health.test_ledger_health.TestLedgerHealth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/ledger_health/test_ledger_health.py", line 92, in test_gl_and_pl_mismatch
    run_ledger_health_checks()
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/utils.py", line 2128, in run_ledger_health_checks
    res = voucher_wise.execute_script_report(filters=filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 11, in execute
    data = get_data(filters)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/report/voucher_wise_balance/voucher_wise_balance.py", line 51, in get_data
    gl_entries = query.run(as_dict=True)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabGL Entry.voucher_type" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "voucher_type","voucher_no",SUM("debit") "debit",SUM(...
               ^


----------------------------------------------------------------------
Ran 2 tests in 1.334s

FAILED (errors=2)
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing
