### ISSUE TITLE
Stock and Account Value Comparison Report showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#326]
### Information about bug

![image](https://github.com/user-attachments/assets/db220252-e124-465a-9d55-199870bde14e)

### Module

accounts, stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Stock and Account Value Comparison
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/dimension_wise_accounts_balance_report/dimension_wise_accounts_balance_report.py", line 25, in execute
    data = get_data(filters, dimension_list)
  File "apps/erpnext/erpnext/accounts/report/dimension_wise_accounts_balance_report/dimension_wise_accounts_balance_report.py", line 65, in get_data
    set_gl_entries_by_account(dimension_list, filters, account, gl_entries_by_account)
  File "apps/erpnext/erpnext/accounts/report/dimension_wise_accounts_balance_report/dimension_wise_accounts_balance_report.py", line 94, in set_gl_entries_by_account
    gl_entries = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.ProgrammingError: can't adapt type 'set'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Dimension-wise Accounts Balance Report",
		"filters": "{\"company\":\"PP Ltd\",\"fiscal_year\":\"2024-2025\",\"from_date\":\"2024-04-01\",\"to_date\":\"2025-03-31\",\"dimension\":\"Cost Center\"}",
		"ignore_prepared_report": false,
		"is_tree": true,
		"parent_field": "parent_account",
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "psycopg2.ProgrammingError: can't adapt type 'set'",
	"exc_type": "ProgrammingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncan't adapt type 'set'\"]"
}
```
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
