### ISSUE TITLE
Material Request: In material request while creation of material transfer entry through create button getting an error 

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#34]
### Information about bug

Material Request: In material request while creation of material transfer entry through create button getting an error 
![image](https://github.com/user-attachments/assets/fe883f4a-660a-4c4e-87ca-77a8b150f6a6)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (version-15)

Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Material Request/MAT-MR-2024-00005
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/utils.py", line 311, in get_incoming_rate
    in_rate = get_valuation_rate(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 1747, in get_valuation_rate
    if last_valuation_rate := frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "index"
LINE 2:   from "tabStock Ledger Entry" force index (item_warehouse)
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"item_code\":\"Test1\",\"posting_date\":\"2024-09-25\",\"posting_time\":\"14:57:37\",\"warehouse\":\"\",\"company\":\"8848 Digital\",\"qty\":1,\"voucher_type\":\"Stock Entry\",\"voucher_no\":\"new-stock-entry-detail-ygmzwwitug\",\"allow_zero_valuation\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.utils.get_incoming_rate",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect valuation_rate\\n\\t\\tfrom \\\"tabStock Ledger Entry\\\" force index (item_warehouse)\\n\\t\\twhere\\n\\t\\t\\titem_code = %s\\n\\t\\t\\tAND warehouse = %s\\n\\t\\t\\tAND valuation_rate >= '0'\\n\\t\\t\\tAND is_cancelled = '0'\\n\\t\\t\\tAND NOT (voucher_no = %s AND voucher_type = %s)\\n\\t\\torder by posting_date desc, posting_time desc, name desc limit 1 ['Test1', '', 'new-stock-entry-detail-ygmzwwitug', 'Stock Entry']\"]"
}
```
```

**Comment by shubham-DT** [comment]
Issue resolved
PR -51

**Comment by aasif-patel** [comment]
Resolved, hence closing..
