### ISSUE TITLE
When I apply the filter for tasks where the "Expected Start Date" is set, a blank popup error appears. This issue prevents me from viewing the relevant tasks.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#350]
### Information about bug

When I apply the filter for tasks where the "Expected Start Date" is set, a blank popup error appears. This issue prevents me from viewing the relevant tasks.
![image](https://github.com/user-attachments/assets/5750b620-3ce1-4e88-b4bf-1548f82d0269)

![image](https://github.com/user-attachments/assets/6aa68424-8242-4c09-9fcd-05531070ab23)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
List/Task/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 32, in get
    data = compress(execute(**args), args=args)
  File "apps/frappe/frappe/desk/reportview.py", line 78, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 233, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: ""
LINE 3:    where "tabTask"."expected_time" != ''
                                              ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Task",
		"fields": "[\"`tabTask`.`name`\",\"`tabTask`.`owner`\",\"`tabTask`.`creation`\",\"`tabTask`.`modified`\",\"`tabTask`.`modified_by`\",\"`tabTask`.`_user_tags`\",\"`tabTask`.`_comments`\",\"`tabTask`.`_assign`\",\"`tabTask`.`_liked_by`\",\"`tabTask`.`docstatus`\",\"`tabTask`.`idx`\",\"`tabTask`.`project`\",\"`tabTask`.`is_group`\",\"`tabTask`.`status`\",\"`tabTask`.`priority`\",\"`tabTask`.`is_milestone`\",\"`tabTask`.`subject`\",\"`tabTask`.`exp_start_date`\",\"`tabTask`.`exp_end_date`\",\"`tabTask`.`progress`\",\"`tabTask`.`depends_on_tasks`\",\"`tabTask`.`_seen`\",\"`tabTask`.`color`\"]",
		"filters": "[[\"Task\",\"expected_time\",\"is\",\"set\"]]",
		"order_by": "`tabTask`.`modified` desc",
		"start": 0,
		"page_length": 20,
		"view": "List",
		"group_by": null,
		"with_comment_count": 1
	},
	"freeze": false,
	"freeze_message": "Loading...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidTextRepresentation",
	"_debug_messages": "[\"Error in query:\\ninvalid input syntax for type numeric: \\\"\\\"\\nLINE 3:    where \\\"tabTask\\\".\\\"expected_time\\\" != ''\\n                                              ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
