### ISSUE TITLE
Delivery Note - Error while selecting the batch number in the add serial Nos dialog in the Delivery Note Item child table

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#379]
### Information about bug

- Go to the Delivery Note Doctype
- Fill the details, and in the item child table select the item which is batch and serial no is enabled for the item.
- In side the child table go to the Serial No / Batch section, there we are able to see a button labled as Pick Serial No / Batch No.
- Click on the button, then a dialog box will get open, at the below of the dialog box, there is a child table with Serial No and Batch No fields,
- Select batch number then error will occur

![Screenshot from 2024-10-22 14-18-46](https://github.com/user-attachments/assets/505fdd54-4884-49e8-9046-28ff61e1ee3f)
![Screenshot from 2024-10-22 14-20-52](https://github.com/user-attachments/assets/1d02dba3-0919-4cc1-b14b-7afe9fcd3ae9)
![Screenshot from 2024-10-22 14-18-08](https://github.com/user-attachments/assets/2ddaa6e7-8bbf-4817-9d5f-8a92c5a8ea62)

### Module

stock

### Version

Frappe Framework: v15.41.0 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Assets: v0.0.1 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 359, in get_batch_no
    batches = get_batches_from_stock_ledger_entries(searchfields, txt, filters, start, page_len)
  File "apps/erpnext/erpnext/controllers/queries.py", line 451, in get_batches_from_stock_ledger_entries
    return query.run(as_list=1) or []
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabBatch.manufacturing_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...k Ledger Entry"."actual_qty") "qty",CONCAT('MFG-',"tabBatch"...
```

**Comment by tinadn** [comment]
Issues resolved. Hence closing.
