### ISSUE TITLE
Cannot able to view customer 8848

### ISSUE THREAD

**Issue by aasif-patel** [8848digital/erpnext#381]
### Information about bug

goto => http://3.12.196.161/app/customer/8848 to reflect the error.

### App Versions
```
{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Customer/8848
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/load.py", line 45, in getdoc
    run_onload(doc)
  File "apps/frappe/frappe/desk/form/load.py", line 351, in run_onload
    doc.run_method("onload")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 95, in onload
    self.load_dashboard_info()
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 98, in load_dashboard_info
    info = get_dashboard_info(self.doctype, self.name, self.loyalty_program)
  File "apps/erpnext/erpnext/accounts/party.py", line 788, in get_dashboard_info
    loyalty_point_details = frappe._dict(
ValueError: dictionary update sequence element #0 has length 3; 2 is required

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Customer",
		"name": "8848"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: dictionary update sequence element #0 has length 3; 2 is required",
	"exc_type": "ValueError",
	"_exc_source": "erpnext (app)"
}
```

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

manual install

**Comment by tinadn** [comment]
Issues resolved. Hence closing.
