### ISSUE TITLE
Server Error while applying date filter in Sales Order List

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#390]
### Information about bug

![image](https://github.com/user-attachments/assets/876a537f-201d-45c2-a460-848e8b840245)

### Module

selling

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
List/Sales Order/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 32, in get
    data = compress(execute(**args), args=args)
  File "apps/frappe/frappe/desk/reportview.py", line 78, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 233, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "01"
LINE 3:    where "tabSales Order"."transaction_date" in ('01')
                                                         ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Sales Order",
		"fields": "[\"`tabSales Order`.`name`\",\"`tabSales Order`.`owner`\",\"`tabSales Order`.`creation`\",\"`tabSales Order`.`modified`\",\"`tabSales Order`.`modified_by`\",\"`tabSales Order`.`_user_tags`\",\"`tabSales Order`.`_comments`\",\"`tabSales Order`.`_assign`\",\"`tabSales Order`.`_liked_by`\",\"`tabSales Order`.`docstatus`\",\"`tabSales Order`.`idx`\",\"`tabSales Order`.`delivery_date`\",\"`tabSales Order`.`total`\",\"`tabSales Order`.`net_total`\",\"`tabSales Order`.`total_taxes_and_charges`\",\"`tabSales Order`.`grand_total`\",\"`tabSales Order`.`rounding_adjustment`\",\"`tabSales Order`.`rounded_total`\",\"`tabSales Order`.`advance_paid`\",\"`tabSales Order`.`discount_amount`\",\"`tabSales Order`.`status`\",\"`tabSales Order`.`per_delivered`\",\"`tabSales Order`.`per_billed`\",\"`tabSales Order`.`customer_name`\",\"`tabSales Order`.`base_grand_total`\",\"`tabSales Order`.`currency`\",\"`tabSales Order`.`order_type`\",\"`tabSales Order`.`skip_delivery_note`\",\"`tabSales Order`.`_seen`\",\"`tabSales Order`.`party_account_currency`\"]",
		"filters": "[[\"Sales Order\",\"transaction_date\",\"in\",[\"01\"]]]",
		"order_by": "`tabSales Order`.`modified` desc",
		"start": 0,
		"page_length": 20,
		"view": "List",
		"group_by": null,
		"with_comment_count": 1
	},
	"freeze": false,
	"freeze_message": "Loading...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidDatetimeFormat",
	"_debug_messages": "[\"Error in query:\\ninvalid input syntax for type date: \\\"01\\\"\\nLINE 3:    where \\\"tabSales Order\\\".\\\"transaction_date\\\" in ('01')\\n                                                         ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
