### ISSUE TITLE
Error in Test Budget test_monthly_budget_crossed_stop2

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#395]
### Information about bug

ERROR: test_monthly_budget_crossed_stop2 (erpnext.accounts.doctype.budget.test_budget.TestBudget)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
aarti@Latitude-7300:~/postgres/frappe-bench-post$ bench run-tests --doctype "Budget" --test  test_monthly_budget_crossed_stop2
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/test_budget.py", line 166, in test_monthly_budget_crossed_stop2
    self.assertRaises(BudgetError, jv.submit)
  File "/usr/lib/python3.10/unittest/case.py", line 738, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.10/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 175, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 187, in on_submit
    self.make_gl_entries()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 996, in make_gl_entries
    make_gl_entries(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 38, in make_gl_entries
    gl_map = process_gl_map(gl_map, merge_entries)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 171, in process_gl_map
    gl_map = distribute_gl_based_on_cost_center_allocation(gl_map, precision)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 191, in distribute_gl_based_on_cost_center_allocation
    validate_expense_against_budget(d, expense_amount=flt(d.debit, precision) - flt(d.credit, precision))
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 221, in validate_expense_against_budget
    validate_budget_records(args, budget_records, expense_amount)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 248, in validate_budget_records
    compare_expense_with_budget(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 259, in compare_expense_with_budget
    args.actual_expense, args.requested_amount, args.ordered_amount = get_actual_expense(args), 0, 0
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 455, in get_actual_expense
    lft_rgt = frappe.db.get_value(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "lft" does not exist\nLINE 1: SELECT "lft","rgt" FROM "tabProject" WHERE "name"=\'_T-Projec...\n               ^\n'
E
======================================================================
ERROR: test_monthly_budget_crossed_stop2 (erpnext.accounts.doctype.budget.test_budget.TestBudget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/test_budget.py", line 166, in test_monthly_budget_crossed_stop2
    self.assertRaises(BudgetError, jv.submit)
  File "/usr/lib/python3.10/unittest/case.py", line 738, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.10/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 175, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 187, in on_submit
    self.make_gl_entries()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 996, in make_gl_entries
    make_gl_entries(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 38, in make_gl_entries
    gl_map = process_gl_map(gl_map, merge_entries)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 171, in process_gl_map
    gl_map = distribute_gl_based_on_cost_center_allocation(gl_map, precision)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 191, in distribute_gl_based_on_cost_center_allocation
    validate_expense_against_budget(d, expense_amount=flt(d.debit, precision) - flt(d.credit, precision))
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 221, in validate_expense_against_budget
    validate_budget_records(args, budget_records, expense_amount)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 248, in validate_budget_records
    compare_expense_with_budget(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 259, in compare_expense_with_budget
    args.actual_expense, args.requested_amount, args.ordered_amount = get_actual_expense(args), 0, 0
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 455, in get_actual_expense
    lft_rgt = frappe.db.get_value(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "lft" does not exist
LINE 1: SELECT "lft","rgt" FROM "tabProject" WHERE "name"='_T-Projec...
               ^


----------------------------------------------------------------------
Ran 1 test in 0.631s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
