### ISSUE TITLE
Erro in Test Period Closing Voucher

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#400]
### Information about bug

ERROR: test_closing_balance_with_dimensions_and_test_reposting_entry (erpnext.accounts.doctype.period_closing_voucher.test_period_closing_voucher.TestPeriodClosingVoucher)

### Module

accounts

### Version

Frappe - V15
Erpnext - V15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Period Closing Voucher" --test test_closing_balance_with_dimensions_and_test_reposting_entry
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/test_period_closing_voucher.py", line 241, in test_closing_balance_with_dimensions_and_test_reposting_entry
    pcv1 = self.make_period_closing_voucher(posting_date="2021-03-31")
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/test_period_closing_voucher.py", line 337, in make_period_closing_voucher
    pcv.submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 51, in on_submit
    self.make_gl_entries(get_opening_entries=get_opening_entries)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 165, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 206, in get_gl_entries
    for acc in self.get_balances_based_on_dimensions(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 373, in get_balances_based_on_dimensions
    return query.run(as_dict=1)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "tabGL Entry.account_currency" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT "account","account_currency",SUM("debit_in_account_cu...\n                         ^\n'
E
======================================================================
ERROR: test_closing_balance_with_dimensions_and_test_reposting_entry (erpnext.accounts.doctype.period_closing_voucher.test_period_closing_voucher.TestPeriodClosingVoucher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/test_period_closing_voucher.py", line 241, in test_closing_balance_with_dimensions_and_test_reposting_entry
    pcv1 = self.make_period_closing_voucher(posting_date="2021-03-31")
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/test_period_closing_voucher.py", line 337, in make_period_closing_voucher
    pcv.submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 51, in on_submit
    self.make_gl_entries(get_opening_entries=get_opening_entries)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 165, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 206, in get_gl_entries
    for acc in self.get_balances_based_on_dimensions(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py", line 373, in get_balances_based_on_dimensions
    return query.run(as_dict=1)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabGL Entry.account_currency" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "account","account_currency",SUM("debit_in_account_cu...
                         ^


----------------------------------------------------------------------
Ran 1 test in 6.730s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
