### ISSUE TITLE
Error in test_purchase_invoice_for_is_paid_and_update_stock_gl_entry_with_perpetual_inventory

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#403]
### Information about bug

ERROR: test_purchase_invoice_for_is_paid_and_update_stock_gl_entry_with_perpetual_inventory (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Purchase Invoice" --test test_purchase_invoice_for_is_paid_and_update_stock_gl_entry_with_perpetual_inventory
'Syntax error in query:\nselect distinct sle.voucher_type, sle.voucher_no\n\t\tfrom "tabStock Ledger Entry" sle\n\t\twhere\n\t\t\ttimestamp(sle.posting_date, sle.posting_time) >= timestamp(%s, %s)\n\t\t\tand is_cancelled = \'0\'\n\t\t\t and item_code in (%s) and warehouse in (%s) and company = %s\n\t\torder by timestamp(sle.posting_date, sle.posting_time) asc, creation asc for update [datetime.date(2024, 10, 23), datetime.time(17, 37, 12, 861731), \'_Test Item\', \'Stores - TCP1\', \'_Test Company with perpetual inventory\']'
E
======================================================================
ERROR: test_purchase_invoice_for_is_paid_and_update_stock_gl_entry_with_perpetual_inventory (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 813, in test_purchase_invoice_for_is_paid_and_update_stock_gl_entry_with_perpetual_inventory
    pi = make_purchase_invoice(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 2463, in make_purchase_invoice
    pi.submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 787, in on_submit
    self.repost_future_sle_and_gle()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/controllers/stock_controller.py", line 1262, in repost_future_sle_and_gle
    create_item_wise_repost_entries(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/controllers/stock_controller.py", line 1674, in create_item_wise_repost_entries
    repost_entry.submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 202, in on_submit
    repost(self)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 272, in repost
    repost_gl_entries(doc)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 360, in repost_gl_entries
    directly_dependent_transactions = _get_directly_dependent_vouchers(doc)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 392, in _get_directly_dependent_vouchers
    affected_vouchers = get_future_stock_vouchers(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/utils.py", line 1393, in get_future_stock_vouchers
    future_stock_vouchers = frappe.db.sql(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "sle"
LINE 4:    timestamp(sle.posting_date, sle.posting_time) >= timestam...
                     ^


----------------------------------------------------------------------
Ran 1 test in 1.914s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
