### ISSUE TITLE
While applying the filter of mode of payment in Item-wise Sales Register report showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#407]
### Information about bug

![image](https://github.com/user-attachments/assets/66e4fdba-07fb-4197-81f9-4a5f538a8547)

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Item-wise Sales Register
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 20, in execute
    return _execute(filters)
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 30, in _execute
    item_list = get_items(filters, additional_table_columns, additional_conditions)
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 482, in get_items
    return query.run(as_dict=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: ..."<='2024-10-23' AND "tabSales Invoice"."name" IN () ORDER BY...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 81, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Item-wise Sales Register",
		"filters": "{\"from_date\":\"2024-09-23\",\"to_date\":\"2024-10-23\",\"company\":\"PP Ltd\",\"mode_of_payment\":\"Bank Draft\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nSELECT \\\"tabSales Invoice Item\\\".\\\"name\\\",\\\"tabSales Invoice Item\\\".\\\"parent\\\",\\\"tabSales Invoice\\\".\\\"posting_date\\\",\\\"tabSales Invoice\\\".\\\"debit_to\\\",\\\"tabSales Invoice\\\".\\\"unrealized_profit_loss_account\\\",\\\"tabSales Invoice\\\".\\\"is_internal_customer\\\",\\\"tabSales Invoice\\\".\\\"customer\\\",\\\"tabSales Invoice\\\".\\\"remarks\\\",\\\"tabSales Invoice\\\".\\\"territory\\\",\\\"tabSales Invoice\\\".\\\"company\\\",\\\"tabSales Invoice\\\".\\\"base_net_total\\\",\\\"tabSales Invoice Item\\\".\\\"project\\\",\\\"tabSales Invoice Item\\\".\\\"item_code\\\",\\\"tabSales Invoice Item\\\".\\\"description\\\",\\\"tabSales Invoice Item\\\".\\\"item_name\\\",\\\"tabSales Invoice Item\\\".\\\"item_group\\\",\\\"tabSales Invoice Item\\\".\\\"item_name\\\" \\\"si_item_name\\\",\\\"tabSales Invoice Item\\\".\\\"item_group\\\" \\\"si_item_group\\\",\\\"tabItem\\\".\\\"item_name\\\" \\\"i_item_name\\\",\\\"tabItem\\\".\\\"item_group\\\" \\\"i_item_group\\\",\\\"tabSales Invoice Item\\\".\\\"sales_order\\\",\\\"tabSales Invoice Item\\\".\\\"delivery_note\\\",\\\"tabSales Invoice Item\\\".\\\"income_account\\\",\\\"tabSales Invoice Item\\\".\\\"cost_center\\\",\\\"tabSales Invoice Item\\\".\\\"enable_deferred_revenue\\\",\\\"tabSales Invoice Item\\\".\\\"deferred_revenue_account\\\",\\\"tabSales Invoice Item\\\".\\\"stock_qty\\\",\\\"tabSales Invoice Item\\\".\\\"stock_uom\\\",\\\"tabSales Invoice Item\\\".\\\"base_net_rate\\\",\\\"tabSales Invoice Item\\\".\\\"base_net_amount\\\",\\\"tabSales Invoice\\\".\\\"customer_name\\\",\\\"tabSales Invoice\\\".\\\"customer_group\\\",\\\"tabSales Invoice Item\\\".\\\"so_detail\\\",\\\"tabSales Invoice\\\".\\\"update_stock\\\",\\\"tabSales Invoice Item\\\".\\\"uom\\\",\\\"tabSales Invoice Item\\\".\\\"qty\\\" FROM \\\"tabSales Invoice\\\" JOIN \\\"tabSales Invoice Item\\\" ON \\\"tabSales Invoice\\\".\\\"name\\\"=\\\"tabSales Invoice Item\\\".\\\"parent\\\" LEFT JOIN \\\"tabItem\\\" ON \\\"tabSales Invoice Item\\\".\\\"item_code\\\"=\\\"tabItem\\\".\\\"name\\\" WHERE \\\"tabSales Invoice\\\".\\\"docstatus\\\"= '1' AND \\\"tabSales Invoice Item\\\".\\\"parenttype\\\"=%(param1)s AND \\\"tabSales Invoice\\\".\\\"company\\\"=%(param2)s AND \\\"tabSales Invoice\\\".\\\"posting_date\\\">=%(param3)s AND \\\"tabSales Invoice\\\".\\\"posting_date\\\"<=%(param4)s AND \\\"tabSales Invoice\\\".\\\"name\\\" IN () ORDER BY \\\"tabSales Invoice\\\".\\\"posting_date\\\" DESC,\\\"tabSales Invoice Item\\\".\\\"item_group\\\" DESC {'param1': 'Sales Invoice', 'param2': 'PP Ltd', 'param3': '2024-09-23', 'param4': '2024-10-23'}\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/411

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
