### ISSUE TITLE
scheduler failed - error while executing the auto_create_fiscal_year scheduler

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#418]
### Information about bug

error while executing the auto_create_fiscal_year scheduler
![Screenshot from 2024-10-24 15-16-00](https://github.com/user-attachments/assets/43adbfb2-a3d4-4cf3-8386-dcb95b620012)

### Module

other

### Version

"assets": "0.0.1",
"erpnext": "15.34.0",
"frappe": "15.41.0",
"payments": "0.0.1"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 143, in execute
    frappe.get_attr(self.method)()
      self = <ScheduledJobType: fiscal_year.auto_create_fiscal_year>
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
      args = ()
      kwargs = {}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x74275d51fac0>
      func = <function auto_create_fiscal_year at 0x74275d51fa30>
  File "apps/erpnext/erpnext/accounts/doctype/fiscal_year/fiscal_year.py", line 137, in auto_create_fiscal_year
    for d in frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
      self = <frappe.database.postgres.database.PostgresDatabase object at 0x742760289c60>
      query = 'select name from `tabFiscal Year` where year_end_date = date_add(current_date, interval 3 day)'
      values = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 328, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable
        
      args = ()
      kwargs = {}
      __class__ = <class 'frappe.database.postgres.database.PostgresDatabase'>
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
      self = <frappe.database.postgres.database.PostgresDatabase object at 0x742760289c60>
      query = 'select name from "tabFiscal Year" where year_end_date = date_add(current_date, interval 3 day)'
      values = None
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = False
      as_iterator = False
      trace_id = None
psycopg2.errors.SyntaxError: syntax error at or near "3"
LINE 1: ...where year_end_date = date_add(current_date, interval 3 day)
                                                                 ^
```

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
