### ISSUE TITLE
While Add item name Book in items in BOM doctype it show error

### ISSUE THREAD

**Issue by rajnish8848** [8848digital/erpnext#419]
### Information about bug

![Screenshot 2024-10-24 152146](https://github.com/user-attachments/assets/752056d9-9aa0-4a9d-b1a7-b8c93569e343)

### Module

manufacturing

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 333, in run_doc_method
    response = doc.run_method(method, args)
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 403, in get_bom_material_detail
    rate = self.get_rm_rate(args)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 449, in get_rm_rate
    rate = get_bom_item_rate(arg, self)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 992, in get_bom_item_rate
    rate = get_valuation_rate(args) * (args.get("conversion_factor") or 1)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 1057, in get_valuation_rate
    item_valuation = item_valuation.run(as_dict=True)[0]
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DivisionByZero: division by zero
```

**Comment by tinadn** [comment]
Issue is resolved. But getting error while typing item code manually
![image](https://github.com/user-attachments/assets/2d9eb9d1-ed59-45b2-ab21-b1a2a330fb56)

**Comment by tinadn** [comment]
### App Versions
```
{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/BOM/new-bom-zmucstgmun
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 1437, in item_query
    barcodes = frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 236, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 5:     order by "tabItem Barcode"."modified" DESC
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "B",
		"doctype": "Item",
		"ignore_user_permissions": 0,
		"reference_doctype": "BOM",
		"page_length": 10,
		"query": "erpnext.manufacturing.doctype.bom.bom.item_query",
		"filters": "{\"is_stock_item\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidColumnReference",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfor SELECT DISTINCT, ORDER BY expressions must appear in select list\\nLINE 5:     order by \\\"tabItem Barcode\\\".\\\"modified\\\" DESC\\n                     ^\\n\"]"
}
```

**Comment by rajnish8848** [comment]
This was new issue ok i will work on it.

**Comment by aasif-patel** [comment]
Resolved hence closing
