### ISSUE TITLE
Stock Ledger - Not able to view stock ledger report due to error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#42]
### Information about bug

![image](https://github.com/user-attachments/assets/1f5cd099-f72b-4ef9-935b-f6bd9d8b7340)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Stock Ledger
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 333, in run_doc_method
    response = doc.run_method(method, args)
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1658, in get_item_details
    stock_and_rate = get_warehouse_details(args) if args.get("warehouse") else {}
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2985, in get_warehouse_details
    "basic_rate": get_incoming_rate(args),
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/utils.py", line 311, in get_incoming_rate
    in_rate = get_valuation_rate(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 1747, in get_valuation_rate
    if last_valuation_rate := frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "index"
LINE 2:   from "tabStock Ledger Entry" force index (item_warehouse)
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "Test1",
		"warehouse": "Stores - 8D",
		"expense_account": "Stock Adjustment - 8D",
		"cost_center": "Main - 8D",
		"company": "8848 Digital",
		"voucher_type": "Stock Entry",
		"voucher_no": "new-stock-entry-detail-hsoebtwrfo",
		"allow_zero_valuation": 1,
		"docs": "{\"docstatus\":0,\"doctype\":\"Stock Entry\",\"name\":\"new-stock-entry-mwjvlqeykg\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-STE-.YYYY.-\",\"purpose\":\"Material Receipt\",\"add_to_transit\":0,\"company\":\"8848 Digital\",\"posting_date\":\"2024-09-25\",\"set_posting_time\":0,\"inspection_required\":0,\"apply_putaway_rule\":0,\"from_bom\":0,\"use_multi_level_bom\":1,\"items\":[{\"docstatus\":0,\"doctype\":\"Stock Entry Detail\",\"name\":\"new-stock-entry-detail-hsoebtwrfo\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"has_item_scanned\":0,\"is_finished_item\":0,\"is_scrap_item\":0,\"retain_sample\":0,\"stock_uom\":\"Nos\",\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"use_serial_batch_fields\":1,\"cost_center\":\"Main - 8D\",\"allow_alternative_item\":0,\"parent\":\"new-stock-entry-mwjvlqeykg\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":1,\"expense_account\":\"Stock Adjustment - 8D\",\"t_warehouse\":\"Stores - 8D\",\"actual_qty\":0,\"basic_amount\":0,\"item_group\":\"Consumable\",\"item_code\":\"Test1\"}],\"additional_costs\":[],\"is_opening\":\"No\",\"is_return\":0,\"expense_account\":\"Stock Adjustment - 8D\",\"posting_time\":\"17:49:43\",\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null,\"stock_entry_type\":\"Material Receipt\",\"total_additional_costs\":0}",
		"method": "get_item_details",
		"args": "{\"item_code\":\"Test1\",\"warehouse\":\"Stores - 8D\",\"expense_account\":\"Stock Adjustment - 8D\",\"cost_center\":\"Main - 8D\",\"company\":\"8848 Digital\",\"voucher_type\":\"Stock Entry\",\"voucher_no\":\"new-stock-entry-detail-hsoebtwrfo\",\"allow_zero_valuation\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect valuation_rate\\n\\t\\tfrom \\\"tabStock Ledger Entry\\\" force index (item_warehouse)\\n\\t\\twhere\\n\\t\\t\\titem_code = %s\\n\\t\\t\\tAND warehouse = %s\\n\\t\\t\\tAND valuation_rate >= '0'\\n\\t\\t\\tAND is_cancelled = '0'\\n\\t\\t\\tAND NOT (voucher_no = %s AND voucher_type = %s)\\n\\t\\torder by posting_date desc, posting_time desc, name desc limit 1 ['Test1', 'Stores - 8D', 'new-stock-entry-detail-hsoebtwrfo', 'Stock Entry']\"]"
}
```
```

**Comment by VishvParikh** [comment]
@aasif-patel resolve the issue

**Comment by aasif-patel** [comment]
Resolved, Hence closing..
