### ISSUE TITLE
Error in test_partial_allocation_on_advance_as_liability

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#426]
### Information about bug

ERROR: test_partial_allocation_on_advance_as_liability (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)

### Module

accounts

### Version

Frappe - V15
Erpnext - V15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Invoice" --test test_partial_allocation_on_advance_as_liability
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 3697, in test_partial_allocation_on_advance_as_liability
    pr.reconcile()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 540, in reconcile
    self.reconcile_allocations()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 514, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/utils.py", line 480, in reconcile_against_document
    doc.make_advance_gl_entries(cancel=1)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1205, in make_advance_gl_entries
    make_reverse_gl_entries(gl_entries, partial_cancel=True)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 646, in make_reverse_gl_entries
    query.run()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "is_cancelled" is of type smallint but expression is of type boolean\nLINE 1: ...117\',"modified_by"=\'Administrator\',"is_cancelled"=true WHERE...\n                                                             ^\nHINT:  You will need to rewrite or cast the expression.\n'
E
======================================================================
ERROR: test_partial_allocation_on_advance_as_liability (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 3697, in test_partial_allocation_on_advance_as_liability
    pr.reconcile()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 540, in reconcile
    self.reconcile_allocations()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 514, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/utils.py", line 480, in reconcile_against_document
    doc.make_advance_gl_entries(cancel=1)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1205, in make_advance_gl_entries
    make_reverse_gl_entries(gl_entries, partial_cancel=True)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/general_ledger.py", line 646, in make_reverse_gl_entries
    query.run()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatatypeMismatch: column "is_cancelled" is of type smallint but expression is of type boolean
LINE 1: ...117',"modified_by"='Administrator',"is_cancelled"=true WHERE...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


----------------------------------------------------------------------
Ran 1 test in 2.733s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
