### ISSUE TITLE
Not able to do Stock Reconciliation getting error while saving. 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#43]
### Information about bug

![image](https://github.com/user-attachments/assets/3a1718b9-555e-4cdb-827b-6584251f29f1)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Stock Reconciliation/new-stock-reconciliation-jesnztxfnw
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 74, in validate
    self.remove_items_with_no_change()
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 454, in remove_items_with_no_change
    items = list(filter(lambda d: _changed(d), self.items))
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 454, in <lambda>
    items = list(filter(lambda d: _changed(d), self.items))
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 414, in _changed
    for dimension in get_inventory_dimensions():
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/inventory_dimension/inventory_dimension.py", line 364, in get_inventory_dimensions
    dimensions = frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 5:     order by "tabInventory Dimension"."modified" DESC
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Stock Reconciliation\",\"name\":\"new-stock-reconciliation-jesnztxfnw\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-RECO-.YYYY.-\",\"company\":\"8848 Digital\",\"purpose\":\"Stock Reconciliation\",\"posting_date\":\"2024-09-25\",\"set_posting_time\":0,\"scan_mode\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Stock Reconciliation Item\",\"name\":\"new-stock-reconciliation-item-kynqmmmvtt\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"allow_zero_valuation_rate\":0,\"use_serial_batch_fields\":1,\"reconcile_all_serial_batch\":0,\"current_qty\":0,\"parent\":\"new-stock-reconciliation-jesnztxfnw\",\"parentfield\":\"items\",\"parenttype\":\"Stock Reconciliation\",\"idx\":1,\"item_name\":\"_Test FG Item\",\"item_group\":\"_Test Item Group Desktops\",\"item_code\":\"_Test FG Item\",\"warehouse\":\"Stores - 8D\",\"qty\":10,\"valuation_rate\":500,\"current_valuation_rate\":0,\"current_amount\":0,\"amount\":5000,\"current_serial_no\":null,\"serial_no\":null,\"quantity_difference\":10,\"amount_difference\":5000}],\"expense_account\":\"Stock Adjustment - 8D\",\"cost_center\":\"Main - 8D\",\"posting_time\":\"18:23:56\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery37007499857917741221": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 3812,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidColumnReference",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfor SELECT DISTINCT, ORDER BY expressions must appear in select list\\nLINE 5:     order by \\\"tabInventory Dimension\\\".\\\"modified\\\" DESC\\n                     ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
issue resolved 
PR 119

**Comment by rushabhmaywade** [comment]
Still not able to submit the stock reconciliation from draft state.

**Comment by shubham-DT** [comment]
@rushabhmaywade cause PR is not merged 
test it once the PR is merged to pre-prod and deployed to server

**Comment by aasif-patel** [comment]
@shubham-DT PR 119 not able to solve please check it

**Comment by shubham-DT** [comment]
conflict solved 
PR - 130

**Comment by aasif-patel** [comment]
@shubham-DT please check record http://3.139.75.38/app/stock-reconciliation/MAT-RECO-2024-00002 same error while submitting

**Comment by shubham-DT** [comment]
@aasif-patel i've tried to submit the document mentioned above 
worked fine

**Comment by aasif-patel** [comment]
Resolved hence closing...
