### ISSUE TITLE
Error in test_01_unreconcile_invoice

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#438]
### Information about bug

ERROR: test_01_unreconcile_invoice (erpnext.accounts.doctype.unreconcile_payment.test_unreconcile_payment.TestUnreconcilePayment)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
ERROR: test_01_unreconcile_invoice (erpnext.accounts.doctype.unreconcile_payment.test_unreconcile_payment.TestUnreconcilePayment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/unreconcile_payment/test_unreconcile_payment.py", line 93, in test_01_unreconcile_invoice
    unreconcile.add_references()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py", line 73, in add_references
    allocations = self.get_allocations_from_payment()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py", line 50, in get_allocations_from_payment
    qb.from_(ple)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Ledger Entry.account" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "account","party_type","party","against_voucher_type"...
               ^


----------------------------------------------------------------------
Ran 1 test in 3.399s

FAILED (errors=1)




======================================================================
ERROR: test_01_unreconcile_invoice (erpnext.accounts.doctype.unreconcile_payment.test_unreconcile_payment.TestUnreconcilePayment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/unreconcile_payment/test_unreconcile_payment.py", line 101, in test_01_unreconcile_invoice
    unreconcile.save().submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/unreconcile_payment/unreconcile_payment.py", line 97, in on_submit
    frappe.db.set_value("Unreconcile Payment Entries", alloc.name, "unlinked", True)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 987, in set_value
    query.run(debug=debug)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatatypeMismatch: column "unlinked" is of type smallint but expression is of type boolean
LINE 1: ...E "tabUnreconcile Payment Entries" SET "unlinked"=true,"modi...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


----------------------------------------------------------------------
Ran 1 test in 4.290s

FAILED (errors=1)
```

**Comment by aasif-patel** [comment]
Resolved hence closing
