### ISSUE TITLE
While selecting the warehouse in Sales order showing Error 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#448]
### Information about bug

![image](https://github.com/user-attachments/assets/21ad1cf6-f4d9-472c-be8d-93d4526ec2f3)
![image](https://github.com/user-attachments/assets/68a7d6fc-46b9-42b9-8d64-38522385b472)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Order/new-sales-order-cglfizenbz
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 444, in validate_link
    filters.update({'name' : docname})
AttributeError: 'list' object has no attribute 'update'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Warehouse",
		"docname": "Stores - PP Ltd",
		"fields": "[]",
		"args": "{\"filters\":[[\"Warehouse\",\"company\",\"in\",[\"\",\"PP Ltd\"]]]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'list' object has no attribute 'update'",
	"exc_type": "AttributeError"
}
```
```

**Comment by aasif-patel** [comment]
@rushabhmaywade please check now.

**Comment by rushabhmaywade** [comment]
For sales order its working but same error encounter on Purchase receipt, purchase invoice, stock entry, delivery note and sales invoice doctype. @aasif-patel @IamSaiyyamChhetri

**Comment by IamSaiyyamChhetri** [comment]
@rushabhmaywade, 

Noted.

**Comment by rushabhmaywade** [comment]
stock reconciliation as well @IamSaiyyamChhetri

**Comment by aasif-patel** [comment]
Resolved hence closing...
