### ISSUE TITLE
Unable to create item

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#451]
### Information about bug

When creating an item with only the mandatory fields, the item group becomes empty upon saving.
![image](https://github.com/user-attachments/assets/cce757e6-2a9f-4ad3-a067-f62562c29329)
![image](https://github.com/user-attachments/assets/f4a2437f-e3d0-4744-abb5-1c7941f7cc60)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Item/new-item-vwyumnbwsj
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 444, in validate_link
    filters.update({'name' : docname})
AttributeError: 'list' object has no attribute 'update'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Item Group",
		"docname": "Consumable",
		"fields": "[]",
		"args": "{\"filters\":[[\"Item Group\",\"docstatus\",\"!=\",2]]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'list' object has no attribute 'update'",
	"exc_type": "AttributeError"
}
```
```

**Comment by IamSaiyyamChhetri** [comment]
Common issue: #448

**Comment by aasif-patel** [comment]
Resolved hence closing
