### ISSUE TITLE
Unable to create Purchase receipt for fixed asset

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#457]
### Information about bug

An error is occurring while creating a purchase receipt for a fixed asset automatic asset creation.
![image](https://github.com/user-attachments/assets/07114c73-e0c5-452b-b6de-0851275fd048)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Receipt/new-purchase-receipt-gluqpjiimg
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 444, in validate_link
    filters.update({'name' : docname})
AttributeError: 'list' object has no attribute 'update'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Item Group",
		"docname": "8848",
		"fields": "[]",
		"args": "{\"filters\":[[\"Item Group\",\"docstatus\",\"!=\",2]]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'list' object has no attribute 'update'",
	"exc_type": "AttributeError"
}
```
```

**Comment by Abhishek8848** [comment]
It's working now.
http://3.12.196.161/app/purchase-receipt/MAT-PRE-2024-00035

**Comment by IamSaiyyamChhetri** [comment]
Common Link field related issue : #448

**Comment by aasif-patel** [comment]
Resolved hence clsoing
