### ISSUE TITLE
Encountering a syntax error when searching for items with special characters, such as "HP Spectre x360 (13.3", 512GB SSD, 16GB RAM) in the Item Code field within the Item Price doctype.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#461]
### Information about bug

Encountering a syntax error when searching for items with special characters, such as "HP Spectre x360 (13.3", 512GB SSD, 16GB RAM) in the Item Code field within the Item Price doctype.

The error occurs when trying to search for an item with special characters in its name (e.g., "HP Spectre x360 (13.3", 512GB SSD, 16GB RAM"). The system’s SQL query fails to process these characters correctly, resulting in a syntax error

![image](https://github.com/user-attachments/assets/e1574608-73d1-4745-b79f-1451110885b7)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Item Price/new-item-price-jazwntfauq
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 193, in search_widget
    values = frappe.get_list(
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 236, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "GB"
LINE 1: ..."tabItem"."customer_code", (1 / nullif(strpos( 512GB SSD, 16...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "HP Spectre x360 (13.3\", 512GB SSD, 16GB RAM",
		"doctype": "Item",
		"ignore_user_permissions": 0,
		"reference_doctype": "Item Price",
		"page_length": 10
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_debug_messages": "[\"Syntax error in query:\\nselect cast(\\\"tabItem\\\".\\\"name\\\" as varchar), \\\"tabItem\\\".\\\"item_name\\\", \\\"tabItem\\\".\\\"description\\\", \\\"tabItem\\\".\\\"item_group\\\", \\\"tabItem\\\".\\\"customer_code\\\", (1 / nullif(strpos( 512GB SSD, 16GB RAM', cast(\\\"tabItem\\\".\\\"name\\\" as varchar), 'HP Spectre x360 (13.3\\\"), 0)) as \\\"_relevance\\\"\\n\\t\\t\\tfrom \\\"tabItem\\\"\\n\\t\\t\\twhere \\\"tabItem\\\".\\\"disabled\\\" != '1' and (cast(\\\"tabItem\\\".\\\"name\\\" as varchar) ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or \\\"tabItem\\\".\\\"item_name\\\" ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or \\\"tabItem\\\".\\\"item_name\\\" ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or \\\"tabItem\\\".\\\"description\\\" ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or \\\"tabItem\\\".\\\"item_group\\\" ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or \\\"tabItem\\\".\\\"customer_code\\\" ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%' or cast(\\\"tabItem\\\".\\\"name\\\" as varchar) ilike '%%HP Spectre x360 (13.3\\\", 512GB SSD, 16GB RAM%%')\\n\\t\\t\\t\\n\\t\\t\\t order by 6 desc nulls last, \\\"tabItem\\\".idx desc, \\\"tabItem\\\".\\\"modified\\\" DESC\\n\\t\\t\\tlimit 10 offset 0 \"]"
}
```
```

**Comment by bansodegaurav8848** [comment]
https://github.com/8848digital/frappe-v15/pull/31

**Comment by tinadn** [comment]
Issue Resolved. Hence Closing.
