### ISSUE TITLE
While mapping default expense account and default income account, getting this server error in item group doctype

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#464]
### Information about bug

While mapping default expense account, getting this server error in item group doctype. Default expense account is required.

![image](https://github.com/user-attachments/assets/42d965f2-fa63-4e88-931e-bae890dc865d)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Item Group/new-item-group-turoejcqsw
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 672, in get_expense_account
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "tabaccount"
LINE 1: select tabAccount.name from "tabAccount"
               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Account",
		"ignore_user_permissions": 0,
		"reference_doctype": "Item Default",
		"page_length": 10,
		"query": "erpnext.controllers.queries.get_expense_account",
		"filters": "{\"company\":\"French Connections\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedTable",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nmissing FROM-clause entry for table \\\"tabaccount\\\"\\nLINE 1: select tabAccount.name from \\\"tabAccount\\\"\\n               ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
This issue is linked to https://github.com/8848digital/frappe-v15/pull/29
hence, assigning to @IamSaiyyamChhetri

**Comment by IamSaiyyamChhetri** [comment]
- Analyse and found issue is different. 
- Overwrite sql query.

**Comment by aasif-patel** [comment]
Resolved hence closing...
