### ISSUE TITLE
An error occurs when trying to create a Sales Order from a Quotation using the "Get Items" button.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#469]
### Information about bug

![image](https://github.com/user-attachments/assets/7c00907d-f6c9-466f-a93d-8d864e950ec5)
![image](https://github.com/user-attachments/assets/ab1ebbf8-3c1a-48af-b24d-4adcc0504c2f)
![image](https://github.com/user-attachments/assets/12557890-b64f-42e8-9275-9560cf6efcac)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Order/new-sales-order-ukghhfkdaj
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/mapper.py", line 53, in map_docs
    target_doc = method(*_args)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 346, in make_sales_order
    return _make_sales_order(source_name, target_doc)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 351, in _make_sales_order
    ordered_items = frappe._dict(
ValueError: dictionary update sequence element #0 has length 3; 2 is required

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.selling.doctype.quotation.quotation.make_sales_order",
		"source_names": "[\"SAL-QTN-2024-00011\"]",
		"target_doc": "{\"docstatus\":0,\"doctype\":\"Sales Order\",\"name\":\"new-sales-order-ukghhfkdaj\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"title\":\"{customer_name}\",\"naming_series\":\"SAL-ORD-.YYYY.-\",\"order_type\":\"Sales\",\"transaction_date\":\"2024-10-29\",\"company\":\"PP Ltd\",\"skip_delivery_note\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"reserve_stock\":0,\"items\":[],\"taxes\":[],\"disable_rounded_total\":1,\"apply_discount_on\":\"Grand Total\",\"packed_items\":[],\"pricing_rules\":[],\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"payment_schedule\":[],\"status\":\"Draft\",\"delivery_status\":\"Not Delivered\",\"billing_status\":\"Not Billed\",\"sales_team\":[],\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"is_internal_customer\":0,\"party_account_currency\":\"INR\",\"advance_paid\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_address\":\"PP-MH-Billing\",\"company_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"base_net_total\":0,\"net_total\":0,\"base_total\":0,\"total\":0,\"total_qty\":0,\"rounding_adjustment\":0,\"grand_total\":0,\"base_grand_total\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":0,\"base_rounded_total\":0,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"amount_eligible_for_commission\":0,\"total_commission\":null}"
	},
	"freeze": true,
	"freeze_message": "Mapping Quotation ...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.map_docs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: dictionary update sequence element #0 has length 3; 2 is required",
	"exc_type": "ValueError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Prateek8848** [comment]
https://github.com/8848digital/erpnext/pull/491/commits/0ea5e83cc662f021f7adf9aab9e88da288493a3a

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
