### ISSUE TITLE
An error occurs when clicking on the Income Account field in the Item child table while creating a Sales Invoice.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#478]
### Information about bug

![image](https://github.com/user-attachments/assets/a9cb88ec-3c03-4193-9598-962c4e7b52f3)
![image](https://github.com/user-attachments/assets/5f665c6e-b7a6-4048-9dd7-995261ec73c4)

### Module

accounts, selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-zivnuofuuy
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 591, in get_income_account
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "tabaccount"
LINE 1: select tabAccount.name from "tabAccount"
               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "Sales ",
		"doctype": "Account",
		"ignore_user_permissions": 0,
		"reference_doctype": "Sales Invoice Item",
		"page_length": 10,
		"query": "erpnext.controllers.queries.get_income_account",
		"filters": "{\"company\":\"PP Ltd\",\"disabled\":0}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedTable",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nmissing FROM-clause entry for table \\\"tabaccount\\\"\\nLINE 1: select tabAccount.name from \\\"tabAccount\\\"\\n               ^\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
