### ISSUE TITLE
Error on Item ( Unit Test : test_add_item_barcode )

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#481]
### Information about bug

![image](https://github.com/user-attachments/assets/36c7059a-1d86-4914-9d71-3987d38de67a)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

ERROR: test_add_item_barcode (erpnext.stock.doctype.item.test_item.TestItem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 616, in test_add_item_barcode
    item_doc = frappe.get_doc("Item", item_code)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 167, in load_from_db
    d = frappe.db.get_value(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


----------------------------------------------------------------------
Ran 1 test in 0.793s

FAILED (errors=1)

**Comment by hrishikesh8848** [comment]
Same error is on Item Group, Stock Entry, Material Request, Delivery Note

**Comment by anandk-spyke-o1** [comment]
Getting another error from "show_unique_validation_message_for_postgress" method in frappe/model/base_document.py file. Removed the method in local.
![Screenshot from 2024-11-11 16-38-27](https://github.com/user-attachments/assets/b0d21df0-8e20-4938-8309-0fb876bdd9b6)

**Comment by aasif-patel** [comment]
Tested hance closed, @hrishikesh8848 other issues are there on Item please solved is Asap.
