### ISSUE TITLE
Erron in test_closed_delivery_note

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#486]
### Information about bug

ERROR: test_closed_delivery_note (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote)

### Module

selling

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Delivery Note"

test_batch_expiry_for_delivery_note (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (3.48s)
...  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/delivery_note/test_delivery_note.py", line 890, in test_closed_delivery_note
    self.assertEqual(frappe.db.get_value("Delivery Note", dn.name, "Status"), "Closed")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "Status" does not exist\nLINE 1: SELECT "Status" FROM "tabDelivery Note" WHERE "name"=\'MAT-DN...\n               ^\nHINT:  Perhaps you meant to reference the column "tabDelivery Note.status".\n'
E
test_delivery_note_bundle_with_batched_item (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (16.0s)
........
test_delivery_of_bundled_items_to_target_warehouse (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.92s)
....
test_dn_billing_status_case3 (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.01s)
.......
test_make_sales_invoice_from_dn_with_returned_qty_duplicate_items (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.15s)
...
test_partial_sales_return_batch_no_for_batched_item_in_dn (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.19s)
....
test_return_for_serialized_items (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.04s)
..
test_returned_qty_in_return_dn (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (3.37s)
..
test_sales_return_against_serial_batch_bundle (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.67s)
...
test_sales_return_for_non_bundled_items_partial (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.54s)
....
test_same_posting_date_and_posting_time (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote) (2.64s)
.....
======================================================================
ERROR: test_closed_delivery_note (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/delivery_note/test_delivery_note.py", line 890, in test_closed_delivery_note
    self.assertEqual(frappe.db.get_value("Delivery Note", dn.name, "Status"), "Closed")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Status" does not exist
LINE 1: SELECT "Status" FROM "tabDelivery Note" WHERE "name"='MAT-DN...
               ^
HINT:  Perhaps you meant to reference the column "tabDelivery Note.status".


----------------------------------------------------------------------
Ran 46 tests in 81.718s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
