### ISSUE TITLE
scheduler failed - error while executing the process_statement_of_accounts.send_auto_email scheduler

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#488]
### Information about bug

error while executing the process_statement_of_accounts.send_auto_email scheduler
![Screenshot from 2024-10-30 13-29-02-1](https://github.com/user-attachments/assets/4e4d7ed8-2135-411e-8010-4841cb4df911)

### Module

other

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 143, in execute
    frappe.get_attr(self.method)()
      self = <ScheduledJobType: process_statement_of_accounts.send_auto_email>
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
      args = ()
      kwargs = {}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x7e97bb828430>
      func = <function send_auto_email at 0x7e97bb8283a0>
  File "apps/erpnext/erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py", line 497, in send_auto_email
    selected = frappe.get_list(
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
      doctype = 'Process Statement Of Accounts'
      args = ()
      kwargs = {'filters': {'enable_auto_email': 1}, 'or_filters': {'to_date': '30-10-2024', 'posting_date': '30-10-2024'}}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
      self = <frappe.model.db_query.DatabaseQuery object at 0x7e97c0149390>
      fields = None
      filters = {'enable_auto_email': 1}
      or_filters = {'to_date': '30-10-2024', 'posting_date': '30-10-2024'}
      docstatus = None
      group_by = None
      order_by = 'KEEP_DEFAULT_ORDERING'
      limit_start = False
      limit_page_length = None
      as_list = False
      with_childnames = False
      debug = False
      ignore_permissions = False
      user = None
      with_comment_count = False
      join = 'left join'
      distinct = False
      start = None
      page_length = None
      limit = None
      ignore_ifnull = False
      save_user_settings = False
      save_user_settings_fields = False
      update = None
      add_total_row = None
      user_settings = None
      reference_doctype = None
      run = True
      strict = True
      ignore_ddl = False
      parent_doctype = None
      pluck = None
  File "apps/frappe/frappe/model/db_query.py", line 236, in build_and_run
    return frappe.db.sql(
      self = <frappe.model.db_query.DatabaseQuery object at 0x7e97c0149390>
      args = {'tables': '`tabProcess Statement Of Accounts`', 'conditions': "where `tabProcess Statement Of Accounts`.`enable_auto_email` = 1.0 and (`tabProcess Statement Of Accounts`.`to_date` = '30-10-2024' or `tabProcess Statement Of Accounts`.`posting_date` = '30-10-2024')", 'fields': 'cast(`tabProcess Statement Of Accounts`.`name` as varchar)', 'order_by': ' order by `tabProcess Statement Of Accounts`.`modified` DESC', 'group_by': '', 'limit': ''}
      query = "select cast(`tabProcess Statement Of Accounts`.`name` as varchar)\n\t\t\tfrom `tabProcess Statement Of Accounts`\n\t\t\twhere `tabProcess Statement Of Accounts`.`enable_auto_email` = 1.0 and (`tabProcess Statement Of Accounts`.`to_date` = '30-10-2024' or `tabProcess Statement Of Accounts`.`posting_date` = '30-10-2024')\n\t\t\t\n\t\t\t order by `tabProcess Statement Of Accounts`.`modified` DESC\n\t\t\t"
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
      self = <frappe.database.postgres.database.PostgresDatabase object at 0x7e97c2a891e0>
      query = "select cast(`tabProcess Statement Of Accounts`.`name` as varchar)\n\t\t\tfrom `tabProcess Statement Of Accounts`\n\t\t\twhere `tabProcess Statement Of Accounts`.`enable_auto_email` = 1.0 and (`tabProcess Statement Of Accounts`.`to_date` = '30-10-2024' or `tabProcess Statement Of Accounts`.`posting_date` = '30-10-2024')\n\t\t\t\n\t\t\t order by `tabProcess Statement Of Accounts`.`modified` DESC\n\t\t\t"
      values = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 328, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable
        
      args = ()
      kwargs = {'as_dict': True, 'debug': False, 'update': None, 'ignore_ddl': False, 'run': True}
      __class__ = <class 'frappe.database.postgres.database.PostgresDatabase'>
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
      self = <frappe.database.postgres.database.PostgresDatabase object at 0x7e97c2a891e0>
      query = 'select cast("tabProcess Statement Of Accounts"."name" as varchar)\n\t\t\tfrom "tabProcess Statement Of Accounts"\n\t\t\twhere "tabProcess Statement Of Accounts"."enable_auto_email" = \'1\' and ("tabProcess Statement Of Accounts"."to_date" = \'30-10-2024\' or "tabProcess Statement Of Accounts"."posting_date" = \'30-10-2024\')\n\t\t\t\n\t\t\t order by "tabProcess Statement Of Accounts"."modified" DESC'
      values = None
      as_dict = True
      as_list = 0
      debug = False
      ignore_ddl = False
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = False
      as_iterator = False
      trace_id = None
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "30-10-2024"
LINE 3: ...d ("tabProcess Statement Of Accounts"."to_date" = '30-10-202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
