### ISSUE TITLE
Error in test_sales_invoice_against_supplier_usd_with_dimensions

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#489]
### Information about bug

ERROR: test_sales_invoice_against_supplier_usd_with_dimensions (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)

### Module

selling

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Invoice" --test test_sales_invoice_against_supplier_usd_with_dimensions
E
======================================================================
ERROR: test_sales_invoice_against_supplier_usd_with_dimensions (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 3095, in test_sales_invoice_against_supplier_usd_with_dimensions
    customer = make_customer(customer="_Test Common Supplier USD")
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/opening_invoice_creation_tool/test_opening_invoice_creation_tool.py", line 219, in make_customer
    customer.insert(ignore_permissions=True)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 155, in validate
    if self.sales_team:
AttributeError: 'Customer' object has no attribute 'sales_team'

----------------------------------------------------------------------
Ran 1 test in 0.623s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
