### ISSUE TITLE
Material Request:  Report view Error - Items to be Requested 

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#49]
### Information about bug

Report view error
![image](https://github.com/user-attachments/assets/eea529b9-9765-4458-bd14-3c6077a40afb)

### Module

stock

### Version

erpnext": "15.34.0",
"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Items To Be Requested
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/frappe/frappe/contacts/doctype/address/address.py", line 277, in address_query
    condition += f" and {fieldname}={frappe.db.escape(value)}"
  File "apps/frappe/frappe/database/postgres/database.py", line 203, in escape
    s = s.replace("%", "%%")
AttributeError: 'int' object has no attribute 'replace'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Address",
		"ignore_user_permissions": 0,
		"reference_doctype": "Request for Quotation",
		"page_length": 10,
		"query": "frappe.contacts.doctype.address.address.address_query",
		"filters": "{\"is_your_company_address\":1,\"link_doctype\":\"Company\",\"link_name\":\"8848 Digital\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'int' object has no attribute 'replace'",
	"exc_type": "AttributeError"
}
```
```

**Comment by nilesh8848** [comment]
Already Resolved in [issue](https://github.com/8848digital/erpnext/issues/16)
