### ISSUE TITLE
Error in test_make_sales_invoice

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#497]
### Information about bug

ERROR: test_make_sales_invoice (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)

### Module

selling

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Order" --test test_make_sales_invoice
E
======================================================================
ERROR: test_make_sales_invoice (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 124, in test_make_sales_invoice
    si1 = make_sales_invoice(so.name)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 1136, in make_sales_invoice
    doclist.set_payment_schedule()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/controllers/accounts_controller.py", line 2146, in set_payment_schedule
    po_or_so, doctype, fieldname = self.get_order_details()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/controllers/accounts_controller.py", line 2215, in get_order_details
    po_or_so = self.get("items")[0].get("sales_order")
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 1.829s

FAILED (errors=1)
```

**Comment by anandk-spyke-o1** [comment]
Working fine now.
![Screenshot from 2024-11-06 12-03-26](https://github.com/user-attachments/assets/253795c3-30ef-4a93-8a56-052e13d81266)
