### ISSUE TITLE
Item Test Case (test_make_item_variant_with_numeric_values)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#498]
### Information about bug

![image](https://github.com/user-attachments/assets/b3bcd695-b8d2-41f0-b032-88035ce9583b)
![image](https://github.com/user-attachments/assets/c85c4913-19b4-4d93-841b-4e156ae7a4de)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 450, in test_make_item_variant_with_numeric_values
    variant = create_variant("_Test Numeric Template Item", {"Test Size": "Large", "Test Item Length": 1.1})
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/controllers/item_variant.py", line 220, in create_variant
    make_variant_item_code(template.item_code, template.item_name, variant)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/controllers/item_variant.py", line 380, in make_variant_item_code
    item_attribute = frappe.db.sql(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = numeric
LINE 4: ...e i.name='Test Item Length' and (v.attribute_value=1.1 or i....
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
