### ISSUE TITLE
Error in test_reserved_qty_for_partial_delivery

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#499]
### Information about bug

ERROR: test_reserved_qty_for_partial_delivery (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)

### Module

selling

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Order" --test test_reserved_qty_for_partial_delivery
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 248, in test_reserved_qty_for_partial_delivery
    so.update_status("Closed")
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 490, in update_status
    self.check_modified_date()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 485, in check_modified_date
    date_diff = frappe.db.sql(f"select TIMEDIFF('{mod_db}', '{cstr(self.modified)}')")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
"Error in query:\nfunction timediff(unknown, unknown) does not exist\nLINE 1: select TIMEDIFF('2024-10-30 17:12:56.650510', '2024-10-30 17...\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n"
E  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 130, in run
    self._tearDownPreviousClass(None, result)
  File "/usr/lib/python3.10/unittest/suite.py", line 306, in _tearDownPreviousClass
    tearDownClass()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 48, in tearDownClass
    frappe.db.set_single_value(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 801, in set_single_value
    frappe.db.delete(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 1266, in delete
    return query.run(**kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncurrent transaction is aborted, commands ignored until end of transaction block\n'
E
======================================================================
ERROR: test_reserved_qty_for_partial_delivery (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 248, in test_reserved_qty_for_partial_delivery
    so.update_status("Closed")
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 490, in update_status
    self.check_modified_date()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 485, in check_modified_date
    date_diff = frappe.db.sql(f"select TIMEDIFF('{mod_db}', '{cstr(self.modified)}')")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function timediff(unknown, unknown) does not exist
LINE 1: select TIMEDIFF('2024-10-30 17:12:56.650510', '2024-10-30 17...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


======================================================================
ERROR: tearDownClass (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 48, in tearDownClass
    frappe.db.set_single_value(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 801, in set_single_value
    frappe.db.delete(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 1266, in delete
    return query.run(**kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


----------------------------------------------------------------------
Ran 1 test in 2.996s

FAILED (errors=2)
```

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
