### ISSUE TITLE
"Cheques and Deposits Incorrectly cleared" report error 

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#5]
### Information about bug

Trying to load the Cheques and Deposits Incorrectly cleared report then throwing an error 
![Screenshot from 2024-09-04 12-28-23](https://github.com/user-attachments/assets/9699c920-2e25-4163-9202-f967d6687103)

### Module

other

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.40.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.40.0"
}
```
### Route
```
query-report/Cheques and Deposits Incorrectly cleared
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/cheques_and_deposits_incorrectly_cleared/cheques_and_deposits_incorrectly_cleared.py", line 12, in execute
    data = build_data(filters)
  File "apps/erpnext/erpnext/accounts/report/cheques_and_deposits_incorrectly_cleared/cheques_and_deposits_incorrectly_cleared.py", line 59, in build_data
    vouchers = get_amounts_not_reflected_in_system_for_bank_reconciliation_statement(filters)
  File "apps/erpnext/erpnext/accounts/report/cheques_and_deposits_incorrectly_cleared/cheques_and_deposits_incorrectly_cleared.py", line 100, in get_amounts_not_reflected_in_system_for_bank_reconciliation_statement
    qb.from_(pe)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function if(boolean, numeric, numeric) does not exist
LINE 1: SELECT 'Payment Entry' "doctype","name",IF("paid_from"='Bank...
                                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 81, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Cheques and Deposits Incorrectly cleared",
		"filters": "{\"company\":\"Satya Tech\",\"account\":\"Bank Account - ST\",\"report_date\":\"2024-09-04\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfunction if(boolean, numeric, numeric) does not exist\\nLINE 1: SELECT 'Payment Entry' \\\"doctype\\\",\\\"name\\\",IF(\\\"paid_from\\\"='Bank...\\n                                                ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by shyamrathod12** [comment]
resolve the issues
PostgreSQL use Case not if 
def get_amounts_not_reflected_in_system_for_bank_reconciliation_statement(filters):
	payments = (
		qb.from_(pe)
		.select(
			doctype_name.as_("doctype"),
			pe.name,
			ifelse(pe.paid_from.eq(filters.account), pe.paid_amount, pe.received_amount).as_("amount"),
			pe.payment_type,
			pe.party_type,
			pe.posting_date,
			pe.clearance_date,
		)
		.where(
			pe.docstatus.eq(1)
			& (pe.paid_from.eq(filters.account) | pe.paid_to.eq(filters.account))
			& pe.posting_date.gt(filters.report_date)
			& pe.clearance_date.lte(filters.report_date)
		)
		.run(as_dict=1)
	) 
     replace ifelse with case 
     	payments = (
    qb.from_(pe)
    .select(
        doctype_name.as_("doctype"),
        pe.name,
        (Case()
            .when(pe.paid_from.eq(filters.account), pe.paid_amount)
            .else_(pe.received_amount)
        ).as_("amount"),
        pe.payment_type,
        pe.party_type,
        pe.posting_date,
        pe.clearance_date,
    )
    .where(
        pe.docstatus.eq(1)
        & (pe.paid_from.eq(filters.account) | pe.paid_to.eq(filters.account))
        & pe.posting_date.gt(filters.report_date)
        & pe.clearance_date.lte(filters.report_date)
    )
    .run(as_dict=1)
)

**Comment by aasif-patel** [comment]
@shyamrathod12 this issue is not resolved, still getting the same error, hence re-opening it..

![image](https://github.com/user-attachments/assets/4e4b6466-6509-44eb-8893-d9b05fd1e20b)

**Comment by VishvParikh** [comment]
@aasif-patel issue is resolved 
please merge it and close it

**Comment by aasif-patel** [comment]
Resolved hence closing...
