### ISSUE TITLE
Purchase Order: Test Case Issue test_advance_paid_upon_payment_entry_cancellation 

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#501]
### Information about bug

ERROR: test_advance_paid_upon_payment_entry_cancellation (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 843, in test_advance_paid_upon_payment_entry_cancellation
    pe.submit()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1094, in run_before_save_methods
    self.run_method("validate")
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 94, in validate
    self.validate_allocated_amount()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 229, in validate_allocated_amount
    self.validate_allocated_amount_with_latest_data()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 298, in validate_allocated_amount_with_latest_data
    frappe.throw(
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "/home/chintan/postgres-issue/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Purchase Order PUR-ORD-2024-00037 has already been fully paid.

### Module

other

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Function get_outstanding_reference_documents() in Payment Entry is returning []
```

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/583

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
