### ISSUE TITLE
Purchase Invoice

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#504]
### Information about bug

======================================================================
ERROR: test_offsetting_entries_for_accounting_dimensions (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 1977, in test_offsetting_entries_for_accounting_dimensions
    check_gl_entries(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 2334, in check_gl_entries
    doc.assertEqual(expected_gle[i][0], gle.account)
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 4.997s

FAILED (errors=1)

### Module

other

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

**Comment by bansodegaurav8848** [comment]
https://github.com/8848digital/erpnext/pull/505

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
