### ISSUE TITLE
Purchase Receipt Test Case: test_purchase_receipt_provisional_accounting

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#506]
### Information about bug

bench --site test run-tests --doctype "Purchase Receipt" --test test_purchase_receipt_provisional_accounting
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py", line 2087, in test_purchase_receipt_provisional_accounting
    amount = frappe.db.get_value("GL Entry", {"docstatus": 1, "voucher_no": pr.name}, ["sum(debit)"])
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "tabGL Entry.modified" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: ...1\' AND "voucher_no"=\'MAT-PRE-2024-00055\' ORDER BY "modified"...\n                                                             ^\n'
E
======================================================================
ERROR: test_purchase_receipt_provisional_accounting (erpnext.stock.doctype.purchase_receipt.test_purchase_receipt.TestPurchaseReceipt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py", line 2087, in test_purchase_receipt_provisional_accounting
    amount = frappe.db.get_value("GL Entry", {"docstatus": 1, "voucher_no": pr.name}, ["sum(debit)"])
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabGL Entry.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...1' AND "voucher_no"='MAT-PRE-2024-00055' ORDER BY "modified"...
                                                             ^

----------------------------------------------------------------------
Ran 1 test in 1.849s

FAILED (errors=1)

### Module

other

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/507

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
