### ISSUE TITLE
After clicking on Finish button and create, system shows server error in work order doctype for stock entry type "Manufacture"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#512]
### Information about bug

After clicking on Finish button and create, system shows server error in work order doctype for stock entry type "Manufacture"
If individual stock entry created for type "Manufacturing", system maps BOM but doesnot map Work Order.

![image](https://github.com/user-attachments/assets/b9796298-0b5a-49b2-b4b0-d56e8e6ee7ab)

### Module

manufacturing

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Work Order/MFG-WO-2024-00010
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1412, in make_stock_entry
    stock_entry.get_items()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1867, in get_items
    self.set_scrap_items()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1874, in set_scrap_items
    scrap_item_dict = self.get_bom_scrap_material(self.fg_completed_qty)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2051, in get_bom_scrap_material
    get_bom_items_as_dict(
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 1163, in get_bom_items_as_dict
    query = query.format(
KeyError: 'rate_field'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"work_order_id": "MFG-WO-2024-00010",
		"purpose": "Manufacture",
		"qty": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.manufacturing.doctype.work_order.work_order.make_stock_entry",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "KeyError: 'rate_field'",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
