### ISSUE TITLE
When getting items from "Expired Batches" in stock entry doctype, system shows server error.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#517]
### Information about bug

When getting items from "Expired Batches" in stock entry doctype, system shows server error.

![image](https://github.com/user-attachments/assets/eaf7ba58-aab2-4b60-998c-fb93ad350615)

![image](https://github.com/user-attachments/assets/70945e13-eef8-4aa9-83b8-bb20211faee2)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Stock Entry/new-stock-entry-bwwinvlnwq
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2956, in get_expired_batch_items
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "b.item" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select b.item, sum(sle.actual_qty) as qty, sle.batch_no, sle...
               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.doctype.stock_entry.stock_entry.get_expired_batch_items",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"b.item\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: select b.item, sum(sle.actual_qty) as qty, sle.batch_no, sle...\\n               ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
Issue resolved

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
