### ISSUE TITLE
ERROR: test_reposting_for_depedent_warehouse (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#519]
### Information about bug

ERROR: test_reposting_for_depedent_warehouse (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/test_stock_entry.py", line 1549, in test_reposting_for_depedent_warehouse
    doc = frappe.get_doc("Repost Item Valuation", repost_name)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Repost Item Valuation None not found
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
