### ISSUE TITLE
Opportunity- Not able to create Quotation form Opportunity doctype showing error 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#52]
### Information about bug

![image](https://github.com/user-attachments/assets/0443877c-2cdb-4b78-9cae-32da0ec56669)

![image](https://github.com/user-attachments/assets/939fab6c-9686-48d8-b7bf-699f9646b54a)

### Module

CRM

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Opportunity/CRM-OPP-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 396, in make_quotation
    target_doc.run_method("set_missing_values")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 50, in set_missing_values
    self.set_missing_lead_customer_details(for_validate=for_validate)
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 96, in set_missing_lead_customer_details
    get_lead_details(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 458, in get_lead_details
    taxes_and_charges = set_taxes(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/party.py", line 691, in set_taxes
    args.update(get_party_details(party, party_type))
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/tax_rule/tax_rule.py", line 150, in get_party_details
    billing_address_name = get_default_address(party_type, party)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/contacts/doctype/address/address.py", line 148, in get_default_address
    addresses = frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatatypeMismatch: COALESCE types character varying and integer cannot be matched
LINE 3: ...Lead' and coalesce("tabDynamic Link"."link_name", 0) = '0' a...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.crm.doctype.lead.lead.make_quotation",
		"source_name": "_T-Lead-00005",
		"args": null,
		"selected_children": "{}"
	},
	"freeze": true,
	"freeze_message": "",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.make_mapped_doc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "DatatypeMismatch",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nCOALESCE types character varying and integer cannot be matched\\nLINE 3: ...Lead' and coalesce(\\\"tabDynamic Link\\\".\\\"link_name\\\", 0) = '0' a...\\n                                                             ^\\n\"]"
}
```
```

**Comment by VishvParikh** [comment]
@aasif-patel issue is resolved and pr is link 
please merge it and check it

**Comment by aasif-patel** [comment]
Resolved hence closing...
