### ISSUE TITLE
ERROR: test_variant_work_order (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#520]
### Information about bug

ERROR: test_variant_work_order (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/test_stock_entry.py", line 933, in test_variant_work_order
    stock_entry = frappe.get_doc(make_stock_entry(work_order.name, "Manufacture", 1))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1412, in make_stock_entry
    stock_entry.get_items()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1867, in get_items
    self.set_scrap_items()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1874, in set_scrap_items
    scrap_item_dict = self.get_bom_scrap_material(self.fg_completed_qty)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2051, in get_bom_scrap_material
    get_bom_items_as_dict(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 1163, in get_bom_items_as_dict
    query = query.format(
KeyError: 'rate_field'
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
