### ISSUE TITLE
ERROR: test_get_items (erpnext.stock.doctype.stock_reconciliation.test_stock_reconciliation.TestStockReconciliation)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#521]
### Information about bug

ERROR: test_get_items (erpnext.stock.doctype.stock_reconciliation.test_stock_reconciliation.TestStockReconciliation)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/test_stock_reconciliation.py", line 147, in test_get_items
    items = get_items("_Test Warehouse Group 1 - _TC", nowdate(), nowtime(), "_Test Company")
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 1102, in get_items
    items = get_items_for_stock_reco(warehouse, company)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 1178, in get_items_for_stock_reco
    items += frappe.db.sql(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "id.default_warehouse" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:    i.name as item_code, i.item_name, id.default_warehouse as...
```

**Comment by tinadn** [comment]
issue resolve. Hence Closing.
