### ISSUE TITLE
In the Stock Reconciliation Doctype, when we select a warehouse and click "Fetch Items" to load all items from that warehouse, an error appears.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#522]
### Information about bug

In the Stock Reconciliation Doctype, when we select a warehouse and click "Update" to load all items from that warehouse, an error appears. But it allow us to fetch single item if we particularly mention  item code.
![image](https://github.com/user-attachments/assets/22dc3fea-094e-44d7-b94b-0ed59d20201e)

![image](https://github.com/user-attachments/assets/fe11a92c-e745-45b0-af0c-4d659422aa7f)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Stock Reconciliation/new-stock-reconciliation-dbusxbrrdb
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 1102, in get_items
    items = get_items_for_stock_reco(warehouse, company)
  File "apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 1178, in get_items_for_stock_reco
    items += frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "id.default_warehouse" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:    i.name as item_code, i.item_name, id.default_warehouse as...
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"warehouse": "Stores - FC",
		"posting_date": "2024-10-31",
		"posting_time": "18:32:51",
		"company": "French Connections",
		"ignore_empty_stock": 0
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.doctype.stock_reconciliation.stock_reconciliation.get_items",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"id.default_warehouse\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 2:    i.name as item_code, i.item_name, id.default_warehouse as...\\n                                             ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
@Purvi8848 this issue  is linked with 521 and now resolved 
please have a look

**Comment by shubham-DT** [comment]
This is working fine now

**Comment by tinadn** [comment]
Resolved. Hence closing.
