### ISSUE TITLE
Error in test_so_back_updated_from_wo_via_mr

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#525]
### Information about bug

ERROR: test_so_back_updated_from_wo_via_mr (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
SO -> MR (Manufacture) -> WO. Test if WO Qty is updated in SO.

### Module

selling

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Order" --test test_so_back_updated_from_wo_via_mr
E
======================================================================
ERROR: test_so_back_updated_from_wo_via_mr (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
SO -> MR (Manufacture) -> WO. Test if WO Qty is updated in SO.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 1694, in test_so_back_updated_from_wo_via_mr
    se = frappe.get_doc(make_se_from_wo(wo.name, "Manufacture", 2))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1412, in make_stock_entry
    stock_entry.get_items()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1867, in get_items
    self.set_scrap_items()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1874, in set_scrap_items
    scrap_item_dict = self.get_bom_scrap_material(self.fg_completed_qty)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2051, in get_bom_scrap_material
    get_bom_items_as_dict(
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 1163, in get_bom_items_as_dict
    query = query.format(
KeyError: 'rate_field'

----------------------------------------------------------------------
Ran 1 test in 4.629s

FAILED (errors=1)
```

**Comment by sibikumarkuppusamy** [comment]
https://github.com/8848digital/erpnext/pull/540

**Comment by tinadn** [comment]
Resolved. Hence Closing.
