### ISSUE TITLE
Accounting: Unable to submit Payment entry getting Server Error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#54]
### Information about bug

Unable to submit Payment entry getting Server Error
![image](https://github.com/user-attachments/assets/f8c16de6-dd40-4182-881b-bea29febc42e)

### Module

accounts

### Version

"erpnext": "15.34.0",
"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 104, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1112, in make_gl_entries
    make_gl_entries(gl_entries, cancel=cancel, adv_adj=adv_adj)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 47, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 382, in save_entries
    validate_against_pcv(is_opening, gl_map[0]["posting_date"], gl_map[0]["company"])
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 707, in validate_against_pcv
    last_pcv_date = frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPeriod Closing Voucher.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...tatus"= '1' AND "company"='8848 Digital' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PAY-2024-00001\",\"owner\":\"Administrator\",\"creation\":\"2024-09-27 12:34:41.575946\",\"modified\":\"2024-09-27 12:35:08.982296\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Receive\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-09-27\",\"company\":\"8848 Digital\",\"mode_of_payment\":\"Wire Transfer\",\"party_type\":\"Supplier\",\"party\":\"_Test Supplier\",\"party_name\":\"_Test Supplier\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"party_balance\":0,\"paid_from\":\"Creditors - 8D\",\"paid_from_account_type\":\"Payable\",\"paid_from_account_currency\":\"INR\",\"paid_from_account_balance\":0,\"paid_to\":\"Bank Account - 8D\",\"paid_to_account_type\":\"Bank\",\"paid_to_account_currency\":\"INR\",\"paid_to_account_balance\":0,\"paid_amount\":50000,\"paid_amount_after_tax\":50000,\"source_exchange_rate\":1,\"base_paid_amount\":50000,\"base_paid_amount_after_tax\":50000,\"received_amount\":50000,\"received_amount_after_tax\":50000,\"target_exchange_rate\":1,\"base_received_amount\":50000,\"base_received_amount_after_tax\":50000,\"total_allocated_amount\":0,\"base_total_allocated_amount\":0,\"unallocated_amount\":50000,\"difference_amount\":0,\"apply_tax_withholding_amount\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_no\":\"IP00025536\",\"reference_date\":\"2024-09-27\",\"status\":\"Draft\",\"custom_remarks\":0,\"remarks\":\"Amount INR 50000 received from _Test Supplier\\nTransaction reference no IP00025536 dated 2024-09-27\",\"base_in_words\":\"INR Fifty Thousand only.\",\"is_opening\":\"No\",\"in_words\":\"INR Fifty Thousand only.\",\"title\":\"_Test Supplier\",\"doctype\":\"Payment Entry\",\"deductions\":[],\"references\":[],\"taxes\":[],\"__onload\":{\"make_payment_via_journal_entry\":0}}",
		"action": "Submit"
	},
	"btn": {
		"jQuery37009508446769997031": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 3269,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPeriod Closing Voucher.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...tatus\\\"= '1' AND \\\"company\\\"='8848 Digital' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
This issue is working fine 
tested on test server

**Comment by shubham-DT** [comment]
@8848swa can you please retest it ....if still you are facing the same issue, let me know the use case

**Comment by 8848swa** [comment]
Yes it's working properly now. Hence closed.
