### ISSUE TITLE
Purchase Invoice Test Case: test_repost_accounting_entries 

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#541]
### Information about bug

FAIL: test_repost_accounting_entries (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 2017, in test_repost_accounting_entries
    check_gl_entries(self, pi.name, expected_gle, nowdate())
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 2347, in check_gl_entries
    doc.assertEqual(expected_gle[i][0], gle.account)
AssertionError: '_Test Account Cost for Goods Sold - _TC' != 'Creditors - _TC'
- _Test Account Cost for Goods Sold - _TC
+ Creditors - _TC

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pi_test_cases_issues)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/542

**Comment by tinadn** [comment]
Resolved. Hence Closing.
