### ISSUE TITLE
Error on Work Order on click Finish

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#556]
### Information about bug

![image](https://github.com/user-attachments/assets/cb71ed51-3b83-442d-a218-5dcb65379b13)

### Module

manufacturing

### Version

Frappe - V15
Erpnext - V15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Work Order/MFG-WO-2024-00010
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1412, in make_stock_entry
    stock_entry.get_items()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1867, in get_items
    self.set_scrap_items()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1874, in set_scrap_items
    scrap_item_dict = self.get_bom_scrap_material(self.fg_completed_qty)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2061, in get_bom_scrap_material
    for row in self.get_scrap_items_from_job_card():
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2096, in get_scrap_items_from_job_card
    scrap_items = (
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabJob Card Scrap Item.item_name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ... "stock_qty","tabJob Card Scrap Item"."item_code","tabJob Ca...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"work_order_id": "MFG-WO-2024-00010",
		"purpose": "Manufacture",
		"qty": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.manufacturing.doctype.work_order.work_order.make_stock_entry",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabJob Card Scrap Item.item_name\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ... \\\"stock_qty\\\",\\\"tabJob Card Scrap Item\\\".\\\"item_code\\\",\\\"tabJob Ca...\\n                                                             ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
Issue resolved

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
