### ISSUE TITLE
Error in test 'test_01_basic_functions' in Repost Accounting Ledger - float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#557]
### Information about bug

test_01_basic_functions (erpnext.accounts.doctype.repost_accounting_ledger.test_repost_accounting_ledger.TestRepostAccountingLedger)

### Module

accounts

### Version

ERPNext: v15.34.0

Frappe Framework: v15.41.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Repost Accounting Ledger" --test test_01_basic_functions
E
======================================================================
ERROR: test_01_basic_functions (erpnext.accounts.doctype.repost_accounting_ledger.test_repost_accounting_ledger.TestRepostAccountingLedger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/repost_accounting_ledger/test_repost_accounting_ledger.py", line 62, in test_01_basic_functions
    pe = get_payment_entry(si.doctype, si.name)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2248, in get_payment_entry
    if float(amount_to_be_paid) < 1:
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by tinadn** [comment]
Issue Resolved. Hence Closing.
