### ISSUE TITLE
Stock entry: Material Transfer entry unable to submit it getting server error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#56]
### Information about bug

Material Transfer entry unable to submit it getting server error
Pls. refer MAT-STE-2024-00003
![image](https://github.com/user-attachments/assets/eb2f2e8c-e95f-449a-8b29-5fbe14377426)

### Module

stock

### Version

"erpnext": "15.34.0",
"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Stock Entry/MAT-STE-2024-00003
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    """Submit the document. Sets `docstatus` = 1, then saves."""
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    self.docstatus = DocStatus.submitted()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    """Wrapper for _save"""
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.update_children()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    fn.__name__ = str(method)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    composed = compose(f, *hooks)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    def runner(self, method, *args, **kwargs):
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    if method in self.__dict__ or callable(method_object):
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 245, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1354, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 869, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 75, in make_sl_entries
    future_sle_exists(args, sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1549, in future_sle_exists
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "index"
LINE 2:   from "tabStock Ledger Entry" force index (item_warehouse)
                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-STE-2024-00003\",\"owner\":\"Administrator\",\"creation\":\"2024-09-26 18:41:51.494078\",\"modified\":\"2024-09-27 12:40:58.570106\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-STE-.YYYY.-\",\"stock_entry_type\":\"Material Transfer\",\"purpose\":\"Material Transfer\",\"add_to_transit\":0,\"company\":\"8848 Digital\",\"posting_date\":\"2024-09-27\",\"posting_time\":\"12:40:58.598668\",\"set_posting_time\":0,\"inspection_required\":0,\"apply_putaway_rule\":0,\"from_bom\":0,\"use_multi_level_bom\":1,\"fg_completed_qty\":0,\"process_loss_percentage\":0,\"process_loss_qty\":0,\"from_warehouse\":\"Stores - 8D\",\"to_warehouse\":\"Work In Progress - 8D\",\"total_outgoing_value\":0,\"total_incoming_value\":0,\"value_difference\":0,\"total_additional_costs\":0,\"is_opening\":\"No\",\"per_transferred\":0,\"total_amount\":0,\"is_return\":0,\"doctype\":\"Stock Entry\",\"additional_costs\":[],\"items\":[{\"name\":\"b9vb10vd22\",\"owner\":\"Administrator\",\"creation\":\"2024-09-26 18:41:51.494078\",\"modified\":\"2024-09-27 12:40:58.570106\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":\"11111111\",\"has_item_scanned\":0,\"s_warehouse\":\"Stores - 8D\",\"t_warehouse\":\"Work In Progress - 8D\",\"item_code\":\"Test1\",\"item_name\":\"Test1\",\"is_finished_item\":0,\"is_scrap_item\":0,\"description\":\"Test1\",\"item_group\":\"Consumable\",\"qty\":1,\"transfer_qty\":1,\"retain_sample\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0,\"additional_cost\":0,\"valuation_rate\":0,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":0,\"use_serial_batch_fields\":1,\"expense_account\":\"Cost of Goods Sold - 8D\",\"cost_center\":\"Main - 8D\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"material_request\":\"MAT-MR-2024-00005\",\"material_request_item\":\"cq1s4mbpbc\",\"parent\":\"MAT-STE-2024-00003\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\"}],\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370075135387024966921": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 997,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect item_code, warehouse, count(name) as total_row\\n\\t\\tfrom \\\"tabStock Ledger Entry\\\" force index (item_warehouse)\\n\\t\\twhere\\n\\t\\t\\t(warehouse = 'Stores - 8D'\\n\\t\\t\\t\\tand item_code in ('Test1') or warehouse = 'Work In Progress - 8D'\\n\\t\\t\\t\\tand item_code in ('Test1'))\\n\\t\\t\\tand timestamp(posting_date, posting_time)\\n\\t\\t\\t\\t>= timestamp(%(posting_date)s, %(posting_time)s)\\n\\t\\t\\tand voucher_no != %(voucher_no)s\\n\\t\\t\\tand is_cancelled = '0'\\n\\t\\tGROUP BY\\n\\t\\t\\titem_code, warehouse {'voucher_type': 'Stock Entry', 'voucher_no': 'MAT-STE-2024-00003', 'posting_date': '2024-09-27', 'posting_time': '12:41:01.304359'}\"]"
}
```
```

**Comment by shubham-DT** [comment]
@8848swa may be this issue is duplicate issue ... i've fixed it for an old issue 
working fine

**Comment by 8848swa** [comment]
Yes working properly. Hence, Closed.
