### ISSUE TITLE
ERROR: test_use_serial_and_batch_fields (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#561]
### Information about bug

ERROR: test_use_serial_and_batch_fields (erpnext.stock.doctype.stock_entry.test_stock_entry.TestStockEntry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 559, in get_incoming_rate_from_bundle
    posting_time = datetime.strptime(posting_time_str, "%H:%M:%S").time()
TypeError: strptime() argument 1 must be str, not datetime.time

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/test_stock_entry.py", line 1731, in test_use_serial_and_batch_fields
    se1 = make_stock_entry(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry_utils.py", line 192, in make_stock_entry
    s.insert()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 233, in validate
    self.calculate_rate_and_amount()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 762, in calculate_rate_and_amount
    self.set_basic_rate(reset_outgoing_rate, raise_error_if_no_rate)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 777, in set_basic_rate
    outgoing_items_cost = self.set_rate_for_outgoing_items(reset_outgoing_rate, raise_error_if_no_rate)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 839, in set_rate_for_outgoing_items
    rate = get_incoming_rate(args, raise_error_if_no_rate)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/utils.py", line 282, in get_incoming_rate
    sn_obj = SerialNoValuation(sle=args, warehouse=args.get("warehouse"), item_code=args.get("item_code"))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 494, in __init__
    self.calculate_stock_value_change()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 509, in calculate_stock_value_change
    incoming_rate = self.get_incoming_rate_from_bundle(serial_no)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 573, in get_incoming_rate_from_bundle
    frappe.log_error(f"Error fetching incoming rate for serial {serial_no}: {str(e)}", "get_incoming_rate_from_bundle")
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/error.py", line 76, in log_error
    return error_log.insert(ignore_permissions=True)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 292, in insert
    self._validate()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 578, in _validate
    self._validate_length()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 976, in _validate_length
    self.throw_length_exceeded_error(df, max_length, value)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 1013, in throw_length_exceeded_error
    frappe.throw(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.CharacterLengthExceededError: Error Log t5uo9i0dn9: 'Title' (Error fetching incoming rate for serial Test Use Serial and Batch Item SN Item - SN 001: strptime() argument 1 must be str, not datetime.time) will get truncated, as max characters allowed is 140
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
