### ISSUE TITLE
Purchase Invoice Test Cases Issue

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#572]
### Information about bug

bench --site test run-tests --doctype "Purchase Invoice"

test_adjust_incoming_rate (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (3.03s)
......................
test_offsetting_entries_for_accounting_dimensions (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (4.66s)
.....
test_provisional_accounting_entry (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (3.09s)
.
test_provisional_accounting_entry_for_over_billing (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (3.44s)
.
test_provisional_accounting_entry_for_partial_billing (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (2.15s)
.F....................
test_purchase_invoice_without_supplier_group (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (3.77s)
.
test_rejected_serial_no (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice) (2.45s)
.........
======================================================================
FAIL: test_purchase_invoice_advance_taxes (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 1557, in test_purchase_invoice_advance_taxes
    self.assertEqual(expected_gle[i][0], gle.account)
AssertionError: '_Test Account Cost for Goods Sold - _TC' != 'Creditors - _TC'
- _Test Account Cost for Goods Sold - _TC
+ Creditors - _TC

----------------------------------------------------------------------
Ran 61 tests in 50.127s

FAILED (failures=1)

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pi_test_cases_issues)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/571

**Comment by pallavi238848** [comment]
@tinadn , do you have any info on this?

**Comment by tinadn** [comment]
@pallavi238848 These were standard cases from erpnext
