### ISSUE TITLE
After selecting the work order in the stock entry for the stock entry type "Material Transfer for Manufacture",& "Manufacture" the BOM, finished goods quantity, and items in the child table are not being fetched.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#582]
### Information about bug

After selecting the work order in the stock entry for the stock entry type "Material Transfer for Manufacture",& "Manufacture" the BOM, finished goods quantity, and items in the child table are not being fetched.

![image](https://github.com/user-attachments/assets/101bbeb7-29af-4543-aa14-91e30fec56fc)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Purvi8848** [comment]
Facing same issue for stock entry type "Material Consumption for Manufacturing" & "Disassemble" in stock entry doctype

**Comment by anandk-spyke-o1** [comment]
Error traceback 
### App Versions
```
{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Stock Entry/new-stock-entry-cxrzgpyunm
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 460, in validate_link
    values.name = frappe.db.get_value(doctype, filters, cache=True)
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 590, in get_values
    out = self._get_value_for_many_names(
  File "apps/frappe/frappe/database/database.py", line 909, in _get_value_for_many_names
    return frappe.qb.get_query(
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "`tabWork Order`.produced_qty"
LINE 1: ... "tabWork Order" WHERE "docstatus"= '1' AND "qty">'`tabWork ...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Work Order",
		"docname": "MFG-WO-2024-00007",
		"fields": "[]",
		"args": "{\"filters\":[[\"Work Order\",\"docstatus\",\"=\",1],[\"Work Order\",\"qty\",\">\",\"`tabWork Order`.produced_qty\"],[\"Work Order\",\"company\",\"=\",\"PP Ltd\"]]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidTextRepresentation",
	"_debug_messages": "[\"Error in query:\\ninvalid input syntax for type numeric: \\\"`tabWork Order`.produced_qty\\\"\\nLINE 1: ... \\\"tabWork Order\\\" WHERE \\\"docstatus\\\"= '1' AND \\\"qty\\\">'`tabWork ...\\n                                                             ^\\n\"]"
}
```
![Screenshot from 2024-11-11 17-48-48](https://github.com/user-attachments/assets/739ebd98-bc6b-455a-be42-8308926ffdb1)

**Comment by tinadn** [comment]
Resolved. Hence closing.
