### ISSUE TITLE
AttributeError: 'GLEntry' object has no attribute 'reconciled_amount'

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#587]
### Information about bug

ERROR: test_item_type_field_change (erpnext.stock.doctype.item.test_item.TestItem)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 798, in test_item_type_field_change
    transaction = transaction_creator(item.name)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 790, in <lambda>
    lambda i: make_purchase_invoice(item_code=i, update_stock=1),
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 2493, in make_purchase_invoice
    pi.submit()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 769, in on_submit
    self.make_gl_entries()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 802, in make_gl_entries
    make_gl_entries(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/general_ledger.py", line 47, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/general_ledger.py", line 386, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/general_ledger.py", line 397, in make_entry
    gle.submit()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 99, in after_insert
    if self.reconciled_amount:
AttributeError: 'GLEntry' object has no attribute 'reconciled_amount'
```

**Comment by hrishikesh8848** [comment]
Creating "reconciled_amount" and "unreconciled_amount" fields fixed it
![image](https://github.com/user-attachments/assets/af89db7d-b85e-423a-b643-7dc0c11db443)

**Comment by Abhishek8848** [comment]
It's working fine.
![image](https://github.com/user-attachments/assets/5eba9110-a2fd-42fa-a669-592ff06a218c)

**Comment by tinadn** [comment]
Working fine. hence closing.
