### ISSUE TITLE
Error in test_credit_limit_on_so_reopning

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/erpnext#590]
### Information about bug

ERROR: test_credit_limit_on_so_reopning (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)

### Module

selling

### Version

Frappe - v15
Erpnext - V15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Order" --test test_credit_limit_on_so_reopning
CUSTOMER _Test Customer Credit
E
======================================================================
ERROR: test_credit_limit_on_so_reopning (erpnext.selling.doctype.sales_order.test_sales_order.TestSalesOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/test_sales_order.py", line 2105, in test_credit_limit_on_so_reopning
    so1.save().submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 396, in on_submit
    self.check_credit_limit()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 465, in check_credit_limit
    check_credit_limit(self.customer, self.company)
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 566, in check_credit_limit
    frappe.msgprint(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Credit limit has been crossed for customer _Test Customer Credit (5400.0/4500.0)Please contact any of the following users to extend the credit limits for _Test Customer Credit: Satya (satya@8848digital.com)

----------------------------------------------------------------------
Ran 1 test in 1.981s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Working fine.
