### ISSUE TITLE
Error on Item ( Unit Test : test_update_is_stock_item )

### ISSUE THREAD

**Issue by anandk-spyke-o1** [8848digital/erpnext#592]
### Information about bug

![Screenshot from 2024-11-11 14-25-21](https://github.com/user-attachments/assets/de50b734-82b2-4e9f-8205-d484b59a424f)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Item" --test test_update_is_stock_item
E
======================================================================
ERROR: test_update_is_stock_item (erpnext.stock.doctype.item.test_item.TestItem.test_update_is_stock_item)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anand/postgress-new/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 827, in test_update_is_stock_item
    item.save()
  File "/home/anand/postgress-new/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anand/postgress-new/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 387, in _save
    self.db_update()
  File "/home/anand/postgress-new/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 638, in db_update
    self.show_unique_validation_message_for_postgress()
  File "/home/anand/postgress-new/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 619, in show_unique_validation_message_for_postgress
    raise frappe.DuplicateEntryError(self.doctype, self.name)
frappe.exceptions.DuplicateEntryError: ('Item', '7aade883c9fae3e9')

----------------------------------------------------------------------
Ran 1 test in 0.448s

FAILED (errors=1)
```

**Comment by anandk-spyke-o1** [comment]
Cause of error is this code in base_document.py 
Made the required change in local and tested , working fine.

![Screenshot from 2024-11-11 16-44-05](https://github.com/user-attachments/assets/71797a23-bcca-4296-b74f-f4c30951811d)
