### ISSUE TITLE
AttributeError: 'datetime.date' object has no attribute 'nodes_'

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#594]
### Information about bug

ERROR: test_stock_reco_for_serialized_item (erpnext.stock.doctype.stock_reconciliation.test_stock_reconciliation.TestStockReconciliation)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/test_stock_reconciliation.py", line 179, in test_stock_reco_for_serialized_item
    valuation_rate = get_incoming_rate(args)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/utils.py", line 255, in get_incoming_rate
    sn_obj = SerialNoValuation(
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 493, in __init__
    self.calculate_stock_value_change()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 508, in calculate_stock_value_change
    incoming_rate = self.get_incoming_rate_from_bundle(serial_no)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 551, in get_incoming_rate_from_bundle
    query = query.where(timestamp_condition)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/utils.py", line 50, in _copy
    result = func(self_copy, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/dialects.py", line 470, in where
    return super().where(criterion)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/utils.py", line 50, in _copy
    result = func(self_copy, *args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/queries.py", line 930, in where
    if not self._validate_table(criterion):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/queries.py", line 1155, in _validate_table
    for field in term.fields_():
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/terms.py", line 57, in fields_
    return set(self.find_(Field))
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/terms.py", line 37, in find_
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/terms.py", line 37, in <listcomp>
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/terms.py", line 742, in nodes_
    yield from self.right.nodes_()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/env/lib/python3.10/site-packages/pypika/terms.py", line 1017, in nodes_
    yield from self.left.nodes_()
AttributeError: 'datetime.date' object has no attribute 'nodes_'
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
