### ISSUE TITLE
System shows error when creating a Purchase Invoice linked to a Subcontract Receipt or within the purchase cycle. However, when creating a standalone Purchase Invoice or one with the 'Update Stock' option, the error does not occur.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#604]
### Information about bug

System shows error when creating a Purchase Invoice linked to a Subcontract Receipt or within the purchase cycle. However, when creating a standalone Purchase Invoice or one with the 'Update Stock' option, the error does not occur.
![image](https://github.com/user-attachments/assets/525fd17f-aa16-49bc-a7ee-630243c3fd6b)

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/new-purchase-invoice-prvlvkfsew
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 18, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 209, in __init__
    super().__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 98, in __init__
    super().__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 135, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 134, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 184, in update
    self.set(key, value, as_value=ignore_children)
  File "apps/frappe/frappe/model/base_document.py", line 236, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 294, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 262, in append
    ret_value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 311, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PINV-.YYYY.-\",\"supplier\":\"Bella Vita\",\"supplier_name\":\"Bella Vita\",\"company\":\"French Connections\",\"posting_date\":\"2024-11-12\",\"posting_time\":\"12:59:51.661620\",\"set_posting_time\":0,\"due_date\":\"2024-11-12\",\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"use_transaction_date_exchange_rate\":0,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"set_warehouse\":\"Stores - FC\",\"is_subcontracted\":0,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":100,\"base_net_total\":100,\"total\":100,\"net_total\":100,\"tax_withholding_net_total\":100,\"base_tax_withholding_net_total\":100,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":100,\"base_rounding_adjustment\":0,\"base_rounded_total\":100,\"base_in_words\":\"\",\"grand_total\":100,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":100,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":100,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"contact_person\":\"Bella Vita-Bella Vita\",\"contact_display\":\"Bella Vita\",\"contact_mobile\":\"98984984\",\"contact_email\":\"\",\"shipping_address\":\"FC Address-Billing\",\"shipping_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"billing_address\":\"FC Address-Billing\",\"billing_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"ignore_default_payment_terms_template\":0,\"status\":\"Draft\",\"per_received\":0,\"credit_to\":\"Creditors - FC\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"letter_head\":\"8848 Digital\",\"group_same_items\":0,\"language\":\"en\",\"on_hold\":0,\"is_internal_supplier\":0,\"supplier_group\":\"PP Ltd Suppliers\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Invoice\",\"advance_tax\":[],\"advances\":[],\"items\":[{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Book\",\"item_name\":\"Book\",\"description\":\"Book\",\"item_group\":\"Consumable\",\"image\":\"\",\"received_qty\":1,\"qty\":1,\"rejected_qty\":0,\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":100,\"amount\":100,\"base_rate\":100,\"base_amount\":100,\"stock_uom_rate\":0,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":100,\"net_amount\":100,\"base_net_rate\":100,\"base_net_amount\":100,\"valuation_rate\":0,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"warehouse\":\"Stores - FC\",\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Received But Not Billed - FC\",\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{}\",\"include_exploded_items\":0,\"purchase_order\":\"PUR-ORD-2024-09748\",\"po_detail\":\"s97d1j9nu7\",\"purchase_receipt\":\"MAT-PRE-2024-06897\",\"pr_detail\":\"s9ei9374ev\",\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"Main - FC\",\"page_break\":0,\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Invoice Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-purchase-invoice-prvlvkfsew\",\"name\":\"new-purchase-invoice-item-pxjpzupcmk\"}],\"payment_discount_terms\":[],\"payment_schedule\":\"[]\",\"pricing_rules\":[],\"supplied_items\":[],\"tax_withheld_vouchers\":[],\"taxes\":[],\"__islocal\":1,\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\",\"supplier_tds\":null,\"enable_apply_tds\":false,\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-purchase-invoice-prvlvkfsew\",\"__last_sync_on\":\"2024-11-12T07:29:50.561Z\",\"change_amount\":0,\"base_change_amount\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370054367966062558431": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 19784,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'str' object does not support item assignment",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by sibikumarkuppusamy** [comment]
Now it's Working Fine.

**Comment by tinadn** [comment]
Working fine. Hence closing.
