### ISSUE TITLE
While selecting the opening entry in POS closing entry showing error 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#607]
### Information about bug

![image](https://github.com/user-attachments/assets/2c02e787-6b83-48cf-8a5f-1bb3876dbf66)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/POS Closing Entry/new-pos-closing-entry-nifzkjkqtl
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 460, in validate_link
    values.name = frappe.db.get_value(doctype, filters, cache=True)
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "user" does not exist
LINE 1: SELECT "name" FROM "tabPOS Profile" WHERE "user"='Administra...
                                                  ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "POS Profile",
		"docname": "pune",
		"fields": "[]",
		"args": "{\"filters\":{\"user\":\"Administrator\"}}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"user\\\" does not exist\\nLINE 1: SELECT \\\"name\\\" FROM \\\"tabPOS Profile\\\" WHERE \\\"user\\\"='Administra...\\n                                                  ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing
