### ISSUE TITLE
Unable to save and submit Stock Entry

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#611]
### Information about bug

Unable to save and submit Stock Entry for any stock entry type
![image](https://github.com/user-attachments/assets/c118f2b1-aec0-41f2-80b0-8ce41ddcbcb0)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Stock Entry/new-stock-entry-sksyhxuhsa
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1094, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 202, in validate
    self.validate_item()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 396, in validate_item
    "project": self.project,
AttributeError: 'StockEntry' object has no attribute 'project'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-STE-2024-14367\",\"owner\":\"Administrator\",\"creation\":\"2024-11-12 16:44:06.745736\",\"modified\":\"2024-11-12 16:44:06.745736\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-STE-.YYYY.-\",\"stock_entry_type\":\"Material Transfer\",\"purpose\":\"Material Transfer\",\"add_to_transit\":1,\"company\":\"French Connections\",\"posting_date\":\"2024-11-12\",\"posting_time\":\"16:44:07.102300\",\"set_posting_time\":0,\"inspection_required\":0,\"apply_putaway_rule\":0,\"from_bom\":0,\"use_multi_level_bom\":1,\"fg_completed_qty\":0,\"process_loss_percentage\":0,\"process_loss_qty\":0,\"to_warehouse\":\"\",\"total_outgoing_value\":50,\"total_incoming_value\":50,\"value_difference\":0,\"total_additional_costs\":0,\"letter_head\":\"8848 Digital\",\"is_opening\":\"No\",\"per_transferred\":0,\"total_amount\":50,\"is_return\":0,\"doctype\":\"Stock Entry\",\"items\":[{\"name\":\"0d7m3jf1ro\",\"owner\":\"Administrator\",\"creation\":\"2024-11-12 16:44:06.745736\",\"modified\":\"2024-11-12 16:44:06.745736\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"s_warehouse\":\"Stores - FC\",\"t_warehouse\":\"Goods In Transit - FC\",\"item_code\":\"Item 8\",\"item_name\":\"Item 8\",\"is_finished_item\":0,\"is_scrap_item\":0,\"description\":\"Item 8\",\"item_group\":\"Sports wear\",\"qty\":5,\"transfer_qty\":5,\"retain_sample\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":10,\"additional_cost\":0,\"valuation_rate\":10,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":50,\"amount\":50,\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Adjustment - FC\",\"cost_center\":\"Main - FC\",\"actual_qty\":9,\"transferred_qty\":0,\"allow_alternative_item\":0,\"parent\":\"MAT-STE-2024-14367\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\"},{\"name\":\"0d7mvd1ttr\",\"owner\":\"Administrator\",\"creation\":\"2024-11-12 16:44:06.745736\",\"modified\":\"2024-11-12 16:44:06.745736\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"has_item_scanned\":0,\"s_warehouse\":\"Finished Goods - FC\",\"t_warehouse\":\"Goods In Transit - FC\",\"item_code\":\"Custom Metal Gear Set\",\"item_name\":\"Custom Metal Gear Set\",\"is_finished_item\":0,\"is_scrap_item\":0,\"description\":\"Custom Metal Gear Set\",\"item_group\":\"Finish Product\",\"qty\":1,\"transfer_qty\":1,\"retain_sample\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0,\"additional_cost\":0,\"valuation_rate\":0,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":0,\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Adjustment - FC\",\"cost_center\":\"Main - FC\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"parent\":\"MAT-STE-2024-14367\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\"}],\"additional_costs\":[],\"__last_sync_on\":\"2024-11-12T11:18:03.239Z\",\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370018259410547891131": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4318,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'StockEntry' object has no attribute 'project'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Abhishek8848** [comment]
@Purvi8848 its working now .
http://3.138.223.54/app/stock-entry/MAT-STE-2024-14367

**Comment by tinadn** [comment]
Working fine.
