### ISSUE TITLE
Server error while Creation of Material Issue from Material Request upon selection of a warehouse 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#625]
### Information about bug

Encountering with the following error while selecting a Warehouse for material issue 

![image](https://github.com/user-attachments/assets/7195759c-fb0c-407a-9ed1-31d91826eff8)

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Stock Entry/new-stock-entry-pydtemquds
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 465, in validate_link
    values.name = frappe.db.get_value(doctype, filters, cache=True)
  File "apps/frappe/frappe/database/database.py", line 515, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 593, in get_values
    out = self._get_value_for_many_names(
  File "apps/frappe/frappe/database/database.py", line 912, in _get_value_for_many_names
    return frappe.qb.get_query(
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type smallint: "No"
LINE 1: ...arehouse" WHERE "company"='PP Ltd' AND "is_group"='No' AND "...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Warehouse",
		"docname": "Finished Goods - PP Ltd",
		"fields": "[]",
		"args": "{\"filters\":[[\"Warehouse\",\"company\",\"=\",\"PP Ltd\"],[\"Warehouse\",\"is_group\",\"=\",\"No\"],[\"Warehouse\",\"name\",\"!=\",\"Sample Warehouse - FC\"]]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidTextRepresentation",
	"_debug_messages": "[\"Error in query:\\ninvalid input syntax for type smallint: \\\"No\\\"\\nLINE 1: ...arehouse\\\" WHERE \\\"company\\\"='PP Ltd' AND \\\"is_group\\\"='No' AND \\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by anandk-spyke-o1** [comment]
Common with #582

**Comment by tinadn** [comment]
Resolved. Hence closing.
