### ISSUE TITLE
Server Error while creation of Purchase Invoice via - Material Request >>- Purchase Order >>- Purchase Invoice

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#626]
### Information about bug

![image](https://github.com/user-attachments/assets/3a097c05-d319-4963-b9fa-792a6729235f)

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/new-purchase-invoice-fmzrpgmpst
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 18, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 208, in __init__
    super().__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 98, in __init__
    super().__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 135, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 134, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 184, in update
    self.set(key, value, as_value=ignore_children)
  File "apps/frappe/frappe/model/base_document.py", line 236, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 294, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 262, in append
    ret_value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 311, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"naming_series\":\"ACC-PINV-.YYYY.-\",\"supplier\":\"Moms Co\",\"supplier_name\":\"Moms Co\",\"company\":\"PP Ltd\",\"posting_date\":\"2024-11-13\",\"posting_time\":\"18:22:36.541725\",\"set_posting_time\":0,\"due_date\":\"2024-11-13\",\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"use_transaction_date_exchange_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"set_warehouse\":\"Finished Goods - PP Ltd\",\"is_subcontracted\":0,\"total_qty\":20,\"total_net_weight\":0,\"base_total\":9000,\"base_net_total\":9000,\"total\":9000,\"net_total\":9000,\"tax_withholding_net_total\":9000,\"base_tax_withholding_net_total\":9000,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":9000,\"base_rounding_adjustment\":0,\"base_rounded_total\":9000,\"base_in_words\":\"\",\"grand_total\":9000,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":9000,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":9000,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"contact_person\":\"Moms Co-Moms Co\",\"contact_display\":\"Moms Co\",\"contact_mobile\":\"85955569\",\"contact_email\":\"\",\"shipping_address\":\"PP - GJ-Billing\",\"shipping_address_display\":\"002<br>\\nSurat<br>\\nGujrat<br>395003<br>India<br>\\n<br>\\n\",\"billing_address\":\"PP - GJ-Billing\",\"billing_address_display\":\"002<br>\\nSurat<br>\\nGujrat<br>395003<br>India<br>\\n<br>\\n\",\"ignore_default_payment_terms_template\":0,\"status\":\"Draft\",\"per_received\":0,\"credit_to\":\"Creditors - PP Ltd\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"language\":\"en\",\"on_hold\":0,\"is_internal_supplier\":0,\"supplier_group\":\"PP Ltd Suppliers\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Invoice\",\"supplied_items\":[],\"items\":[{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Pillow - PP\",\"item_name\":\"Pillow - PP\",\"description\":\"Pillow - PP\",\"item_group\":\"Home Essentials PP\",\"image\":\"\",\"received_qty\":0,\"qty\":20,\"rejected_qty\":0,\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"stock_qty\":20,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":450,\"amount\":9000,\"base_rate\":450,\"base_amount\":9000,\"stock_uom_rate\":0,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":450,\"net_amount\":9000,\"base_net_rate\":450,\"base_net_amount\":9000,\"valuation_rate\":0,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"warehouse\":\"Finished Goods - PP Ltd\",\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Received But Not Billed - PP Ltd\",\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{}\",\"include_exploded_items\":0,\"purchase_order\":\"PUR-ORD-2024-09883\",\"po_detail\":\"siis0kjr8e\",\"material_request\":\"MAT-MR-2024-03826-1\",\"material_request_item\":\"s2n4of5703\",\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"Main - PP Ltd\",\"page_break\":0,\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Invoice Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-purchase-invoice-fmzrpgmpst\",\"name\":\"new-purchase-invoice-item-pwbnherpfk\"}],\"tax_withheld_vouchers\":[],\"payment_schedule\":\"[]\",\"advances\":[],\"payment_discount_terms\":[],\"pricing_rules\":[],\"taxes\":[],\"advance_tax\":[],\"__islocal\":1,\"__onload\":{\"enable_apply_tds\":false,\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-purchase-invoice-fmzrpgmpst\",\"__last_sync_on\":\"2024-11-13T12:52:36.835Z\",\"change_amount\":0,\"base_change_amount\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery37007587521278314441": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 11546,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'str' object does not support item assignment",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by sibikumarkuppusamy** [comment]
Now it's Working Fine.

**Comment by shubham-DT** [comment]
working fine
please close the issue

**Comment by tinadn** [comment]
Working fine. Hence closing.
