### ISSUE TITLE
Unable to create Dunning Document through Sales Invoice and Dunning DocType, Getting pop-up message saying server error !

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#627]
### Information about bug

Unable to create Dunning Document Through Sales Invoice, Getting server error

<img width="881" alt="image" src="https://github.com/user-attachments/assets/ac848b6d-9d41-4d99-83ab-9f8e39d31c5a">

Unable to create Dunning Document Through Dunning DocType, Getting server error
<img width="916" alt="image" src="https://github.com/user-attachments/assets/27a680bf-f96c-4097-8114-287f3bf72d47">

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (develop)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Error
IndexError: list index out of range
Possible source of error: erpnext (app)

### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2024-38162
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2626, in create_dunning
    return get_mapped_doc(
  File "apps/frappe/frappe/model/mapper.py", line 155, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2622, in postprocess_dunning
    target.overdue_payments[0].outstanding = source.get("outstanding_amount")
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.accounts.doctype.sales_invoice.sales_invoice.create_dunning",
		"source_name": "ACC-SINV-2024-38162",
		"args": null,
		"selected_children": "{}"
	},
	"freeze": true,
	"freeze_message": "",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.make_mapped_doc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by sibikumarkuppusamy** [comment]
Now it's working Fine. But there are 2 other issues in validate.


Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/dunning/dunning.py", line 74, in validate
    self.validate_totals()
  File "apps/erpnext/erpnext/accounts/doctype/dunning/dunning.py", line 101, in validate_totals
    self.dunning_amount = self.total_interest + self.dunning_fee
TypeError: unsupported operand type(s) for +: 'float' and 'str'



Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/dunning/dunning.py", line 73, in validate
    self.validate_overdue_payments()
  File "apps/erpnext/erpnext/accounts/doctype/dunning/dunning.py", line 92, in validate_overdue_payments
    daily_interest = self.rate_of_interest / 100 / 365
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by tinadn** [comment]
Resolved. Hence closing.
