### ISSUE TITLE
CRM Report - Not able to view Opportunity Summary by Sales Stage Report

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#63]
### Information about bug

![image](https://github.com/user-attachments/assets/5fbabdde-5951-46d3-9cd3-2eeb962174fb)

### Module

CRM

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Opportunity Summary by Sales Stage
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/crm/report/sales_pipeline_analytics/sales_pipeline_analytics.py", line 17, in execute
    return SalesPipelineAnalytics(filters).run()
  File "apps/erpnext/erpnext/crm/report/sales_pipeline_analytics/sales_pipeline_analytics.py", line 34, in run
    self.get_data()
  File "apps/erpnext/erpnext/crm/report/sales_pipeline_analytics/sales_pipeline_analytics.py", line 105, in get_data
    self.query_result = frappe.db.get_list(
  File "apps/frappe/frappe/database/database.py", line 758, in get_list
    return frappe.get_list(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function monthname(date) does not exist
LINE 1: ...sign" as opportunity_owner, count(name) as count, monthname(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 226, in run
    frappe.log_error("Report Error")
  File "apps/frappe/frappe/utils/error.py", line 76, in log_error
    return error_log.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 279, in insert
    self._set_defaults()
  File "apps/frappe/frappe/model/document.py", line 783, in _set_defaults
    new_doc = frappe.new_doc(self.doctype, as_dict=True)
  File "apps/frappe/frappe/__init__.py", line 1197, in new_doc
    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "apps/frappe/frappe/model/create_new.py", line 22, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "apps/frappe/frappe/model/create_new.py", line 44, in make_new_doc
    if not frappe.model.meta.is_single(doctype):
  File "apps/frappe/frappe/model/meta.py", line 727, in is_single
    return frappe.db.get_value("DocType", doctype, "issingle")
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Sales Pipeline Analytics",
		"filters": "{\"pipeline_by\":\"Owner\",\"from_date\":\"2024-09-01\",\"to_date\":\"2024-09-30\",\"range\":\"Monthly\",\"based_on\":\"Number\",\"company\":\"8848 Digital\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfunction monthname(date) does not exist\\nLINE 1: ...sign\\\" as opportunity_owner, count(name) as count, monthname(...\\n                                                             ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by VishvParikh** [comment]
@aasif-patel  issue is resolved please check it and close it

**Comment by aasif-patel** [comment]
Resolved hence closing...
