### ISSUE TITLE
ERROR: test_add_item_barcode (erpnext.stock.doctype.item.test_item.TestItem)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#637]
### Information about bug

frappe.exceptions.DuplicateEntryError: ('Item Barcode', '9ghbgpldgg')

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 615, in test_add_item_barcode
    self.assertRaises(frappe.UniqueValidationError, item_doc.save)
  File "/usr/lib/python3.10/unittest/case.py", line 738, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.10/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 389, in _save
    self.update_children()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 421, in update_children
    self.update_child_table(df.fieldname, df)
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 453, in update_child_table
    d.db_update()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 639, in db_update
    self.show_unique_validation_message_for_postgress()
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/frappe/frappe/model/base_document.py", line 619, in show_unique_validation_message_for_postgress
    raise frappe.DuplicateEntryError(self.doctype, self.name)
frappe.exceptions.DuplicateEntryError: ('Item Barcode', '9ghbgpldgg')
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
