### ISSUE TITLE
purchase invoice - getting error whille cancelling the purchase invoice

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#653]
### Information about bug

go to the purchase invoice
opne any submitted document and cancel it, then error will raise

https://github.com/user-attachments/assets/b8f6ef42-d0b9-4bac-96e0-25fb4536fa0a

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/linked_with.py", line 374, in cancel_all_linked_docs
    linked_doc.cancel()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1053, in cancel
    return self._cancel()
  File "apps/frappe/frappe/model/document.py", line 1036, in _cancel
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1133, in run_post_save_methods
    self.run_method("on_cancel")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 1494, in on_cancel
    self.make_gl_entries_on_cancel()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 878, in make_gl_entries_on_cancel
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 762, in make_gl_entries
    make_reverse_gl_entries(voucher_type=self.doctype, voucher_no=self.name)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 609, in make_reverse_gl_entries
    create_payment_ledger_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1770, in create_payment_ledger_entry
    delink_original_entry(ple, partial_cancel=partial_cancel)
  File "apps/erpnext/erpnext/accounts/utils.py", line 1842, in delink_original_entry
    query.run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatatypeMismatch: column "delinked" is of type smallint but expression is of type boolean
LINE 1: UPDATE "tabPayment Ledger Entry" SET "delinked"=true,"modifi...
                                                        ^
HINT:  You will need to rewrite or cast the expression.
```

**Comment by vinod-8848digital** [comment]
same issue exists in sales invoice also

**Comment by tinadn** [comment]
Resolved. Hence closing.
