### ISSUE TITLE
Not able to create sales order showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#685]
### Information about bug

![image](https://github.com/user-attachments/assets/6c9e8182-955f-4ce7-af77-08f21488604b)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.35.1",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Order/new-sales-order-doalbgjhch
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/projects/projects/projects/customizations/sales_order/sales_order.py", line 8, in validate
    validate_proj_cust(self)
  File "apps/projects/projects/projects/customizations/sales_order/doc_events/utility_functions.py", line 6, in validate_proj_cust
    if self.project and self.customer_name:
AttributeError: 'SalesOrder' object has no attribute 'project'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Order\",\"name\":\"new-sales-order-doalbgjhch\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"title\":\"{customer_name}\",\"naming_series\":\"SAL-ORD-.YYYY.-\",\"order_type\":\"Sales\",\"transaction_date\":\"2024-11-21\",\"company\":\"PP Ltd\",\"skip_delivery_note\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"reserve_stock\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Order Item\",\"name\":\"new-sales-order-item-ewgeqyzers\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"item_group\":\"_Test Item Group\",\"stock_uom\":\"Nos\",\"stock_reserved_qty\":0,\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"against_blanket_order\":null,\"page_break\":0,\"parent\":\"new-sales-order-doalbgjhch\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":3000,\"amount\":3000,\"base_rate\":3000,\"base_amount\":3000,\"stock_uom_rate\":3000,\"net_rate\":3000,\"net_amount\":3000,\"base_net_rate\":3000,\"base_net_amount\":3000,\"billed_amt\":0,\"valuation_rate\":2997.03,\"gross_profit\":2.97,\"weight_per_unit\":0,\"total_weight\":0,\"blanket_order_rate\":0,\"projected_qty\":3547,\"actual_qty\":3737,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"delivery_date\":\"2024-11-21\",\"warehouse\":\"Stores - PP Ltd\",\"item_code\":\"CPU\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"CPU\",\"description\":\"CPU\",\"image\":\"\",\"income_account\":\"Sales - PP Ltd\",\"expense_account\":\"Cost of Goods Sold - PP Ltd\",\"discount_account\":null,\"provisional_expense_account\":null,\"cost_center\":\"Main - PP Ltd\",\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"is_fixed_asset\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-11-21\",\"bom_no\":null,\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"reserved_qty\":191,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-sales-order-item-ewgeqyzers\"}],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"packed_items\":[],\"pricing_rules\":[],\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"payment_schedule\":[],\"status\":\"Draft\",\"delivery_status\":\"Not Delivered\",\"billing_status\":\"Not Billed\",\"group_same_items\":0,\"is_internal_customer\":0,\"party_account_currency\":\"INR\",\"advance_paid\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_address\":\"PP-MH-Billing\",\"company_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"letter_head\":\"PP Ltd\",\"base_net_total\":3000,\"net_total\":3000,\"base_total\":3000,\"total\":3000,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":3000,\"base_grand_total\":3000,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":3000,\"base_rounded_total\":3000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"tax_id\":null,\"customer_name\":\"Ashish\",\"represents_company\":null,\"customer\":\"Ashish\",\"customer_address\":\"Pune East-Shipping\",\"address_display\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"shipping_address_name\":\"Pune East-Shipping\",\"shipping_address\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"tax_category\":\"In-State\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"contact_phone\":null,\"language\":\"en\",\"payment_terms_template\":null,\"delivery_date\":\"2024-11-21\",\"set_warehouse\":\"Stores - PP Ltd\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370089393650161763571": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 6068,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'SalesOrder' object has no attribute 'project'",
	"exc_type": "AttributeError",
	"_exc_source": "projects (app)"
}
```
```

**Comment by rushabhmaywade** [comment]
Same issue encounter while creating delivery note as well

**Comment by vinod-8848digital** [comment]
@sibikumarkuppusamy this is coming from the project seperation from erpnext, I am already working on this

**Comment by rushabhmaywade** [comment]
@vinod-8848digital, Same issue encounter while creating sales invoice as well

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
