### ISSUE TITLE
While submitting sales invoice, system shows this issue "AttributeError: 'super' object has no attribute 'get_gl_entries' Possible source of error: assets (app)"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#690]
### Information about bug

While submitting sales invoice, system shows this issue "AttributeError: 'super' object has no attribute 'get_gl_entries' Possible source of error: assets (app)"

![image](https://github.com/user-attachments/assets/d8c1dca8-b676-4725-a3c6-e7681128e406)

### Module

selling

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.35.1",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2024-44895
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 407, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1050, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1097, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "apps/assets/assets/assets/customizations/accounts/sales_invoice/sales_invoice.py", line 7, in make_item_gl_entries
    make_item_gl_entries(self, gl_entries)
  File "apps/assets/assets/assets/customizations/accounts/sales_invoice/override.py", line 119, in make_item_gl_entries
    gl_entries += super(StockController, self).get_gl_entries()
AttributeError: 'super' object has no attribute 'get_gl_entries'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-SINV-2024-44895\",\"owner\":\"Administrator\",\"creation\":\"2024-11-21 16:01:07.139145\",\"modified\":\"2024-11-21 16:01:07.139145\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Krishna\",\"naming_series\":\"ACC-SINV-.YYYY.-\",\"customer\":\"Krishna\",\"customer_name\":\"Krishna\",\"tax_id\":null,\"company\":\"French Connections\",\"company_tax_id\":null,\"posting_date\":\"2024-11-21\",\"posting_time\":\"16:01:07.335451\",\"set_posting_time\":0,\"due_date\":\"2024-11-21\",\"is_pos\":0,\"pos_profile\":null,\"is_consolidated\":0,\"is_return\":0,\"return_against\":null,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"amended_from\":null,\"location\":null,\"cost_center\":\"Main - FC\",\"project\":null,\"department\":null,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"scan_barcode\":null,\"update_stock\":1,\"set_warehouse\":\"Stores - FC\",\"set_target_warehouse\":null,\"total_qty\":50,\"total_net_weight\":0,\"base_total\":12500,\"base_net_total\":12500,\"total\":12500,\"net_total\":12500,\"exempt_from_sales_tax\":0,\"tax_category\":\"\",\"taxes_and_charges\":null,\"shipping_rule\":null,\"incoterm\":null,\"named_place\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":12500,\"base_rounding_adjustment\":0,\"base_rounded_total\":12500,\"base_in_words\":\"\",\"grand_total\":12500,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":12500,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":12500,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_account\":null,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":null,\"total_billing_hours\":0,\"total_billing_amount\":0,\"cash_bank_account\":null,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"account_for_change_amount\":null,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"write_off_account\":null,\"write_off_cost_center\":null,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"loyalty_program\":\"new year\",\"loyalty_redemption_account\":null,\"loyalty_redemption_cost_center\":null,\"customer_address\":\"Krishna Billing Address-Billing\",\"address_display\":\"D-13, M.I.D.C. Industrial Area, Thermax Limited<br>\\nR.D.Aga Road, Chinchwad<br>Pune<br>\\nMaharashtra<br>411019<br>India<br>\\n<br>\\n\",\"contact_person\":null,\"contact_display\":null,\"contact_mobile\":null,\"contact_email\":null,\"territory\":\"All Territories\",\"shipping_address_name\":null,\"shipping_address\":null,\"dispatch_address_name\":null,\"dispatch_address\":null,\"company_address\":\"FC Address-Billing\",\"company_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"payment_term\":null,\"discount_due_date\":null,\"ignore_default_payment_terms_template\":0,\"payment_terms_template\":null,\"tc_name\":null,\"terms\":null,\"po_no\":\"\",\"po_date\":null,\"debit_to\":\"Debtors - FC\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"unrealized_profit_loss_account\":null,\"against_income_account\":\"Sales - FC\",\"sales_partner\":null,\"amount_eligible_for_commission\":12500,\"commission_rate\":0,\"total_commission\":0,\"letter_head\":\"8848 Digital\",\"group_same_items\":0,\"select_print_heading\":null,\"language\":\"en\",\"subscription\":null,\"from_date\":null,\"auto_repeat\":null,\"to_date\":null,\"status\":\"Draft\",\"inter_company_invoice_reference\":null,\"campaign\":null,\"represents_company\":null,\"source\":null,\"customer_group\":\"Commercial\",\"is_internal_customer\":0,\"is_discounted\":0,\"remarks\":null,\"doctype\":\"Sales Invoice\",\"taxes\":[],\"advances\":[],\"payment_discount_terms\":[],\"payment_schedule\":[{\"name\":\"ctpi6pigf2\",\"owner\":\"Administrator\",\"creation\":\"2024-11-21 16:01:07.434486\",\"modified\":\"2024-11-21 16:01:07.434486\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"payment_term\":null,\"description\":null,\"due_date\":\"2024-11-21\",\"mode_of_payment\":null,\"invoice_portion\":100,\"discount_type\":null,\"discount_date\":null,\"discount\":0,\"payment_amount\":12500,\"outstanding\":12500,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":12500,\"parent\":\"ACC-SINV-2024-44895\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\"}],\"sales_team\":[],\"payments\":[],\"pricing_rules\":[],\"timesheets\":[],\"packed_items\":[],\"items\":[{\"name\":\"ctpfj28u23\",\"owner\":\"Administrator\",\"creation\":\"2024-11-21 16:01:07.139145\",\"modified\":\"2024-11-21 16:01:07.139145\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"item_code\":\"ZX2030\",\"item_name\":\"ZX2030\",\"customer_item_code\":null,\"description\":\"ZX2030\",\"item_group\":\"Electronics\",\"brand\":null,\"image\":\"\",\"qty\":50,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":50,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":250,\"amount\":12500,\"item_tax_template\":null,\"base_rate\":250,\"base_amount\":12500,\"pricing_rules\":\"\",\"stock_uom_rate\":250,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":250,\"net_amount\":12500,\"base_net_rate\":250,\"base_net_amount\":12500,\"delivered_by_supplier\":0,\"income_account\":\"Sales - FC\",\"is_fixed_asset\":0,\"asset\":null,\"finance_book\":null,\"expense_account\":\"Cost of Goods Sold - FC\",\"discount_account\":null,\"deferred_revenue_account\":null,\"service_stop_date\":null,\"enable_deferred_revenue\":0,\"service_start_date\":null,\"service_end_date\":null,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":null,\"warehouse\":\"Stores - FC\",\"target_warehouse\":null,\"quality_inspection\":null,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":100,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":1020,\"serial_no\":null,\"batch_no\":null,\"sales_order\":null,\"so_detail\":null,\"sales_invoice_item\":null,\"delivery_note\":null,\"dn_detail\":null,\"delivered_qty\":0,\"purchase_order\":null,\"purchase_order_item\":null,\"location\":null,\"cost_center\":\"Main - FC\",\"project\":null,\"department\":null,\"page_break\":0,\"parent\":\"ACC-SINV-2024-44895\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\",\"__unsaved\":1}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-11-21T10:31:06.831Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700214163713173345821": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 10703,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'super' object has no attribute 'get_gl_entries'",
	"exc_type": "AttributeError",
	"_exc_source": "assets (app)"
}
```
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
