### ISSUE TITLE
Unable to create supplier

### ISSUE THREAD

**Issue by MohitJ640** [8848digital/erpnext#702]
### Information about bug

When I try to create a supplier, it gives me this error:
![image](https://github.com/user-attachments/assets/5e58d788-03ba-4d60-be98-de813751df07)

### Module

buying

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.35.1",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Supplier/new-supplier-nwkzffjodn
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 103, in on_update
    self.create_primary_contact()
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 182, in create_primary_contact
    from erpnext.selling.doctype.customer.customer import make_contact
ImportError: cannot import name 'make_contact' from 'erpnext.selling.doctype.customer.customer' (apps/erpnext/erpnext/selling/doctype/customer/customer.py)

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Supplier\",\"name\":\"new-supplier-nwkzffjodn\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"mohit@8848digital.com\",\"naming_series\":\"SUP-.YYYY.-\",\"country\":\"India\",\"supplier_type\":\"Company\",\"is_transporter\":0,\"is_internal_supplier\":0,\"companies\":[],\"language\":\"en\",\"accounts\":[],\"allow_purchase_invoice_creation_without_purchase_order\":0,\"allow_purchase_invoice_creation_without_purchase_receipt\":0,\"is_frozen\":0,\"disabled\":0,\"warn_rfqs\":0,\"warn_pos\":0,\"prevent_rfqs\":0,\"prevent_pos\":0,\"on_hold\":0,\"hold_type\":\"\",\"portal_users\":[],\"represents_company\":\"\",\"supplier_name\":\"Conway Ltd\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370042029800593026171": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 5746,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ImportError: cannot import name 'make_contact' from 'erpnext.selling.doctype.customer.customer' (apps/erpnext/erpnext/selling/doctype/customer/customer.py)",
	"exc_type": "ImportError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing..
