### ISSUE TITLE
When attempting to save a Delivery Note, the system displays the following server error: "AttributeError: 'DeliveryNote' object has no attribute 'project'. Possible source of error: projects (app)."

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#716]
### Information about bug

When attempting to save a Delivery Note, the system displays the following server error:
"AttributeError: 'DeliveryNote' object has no attribute 'project'. Possible source of error: projects (app)."
![image](https://github.com/user-attachments/assets/a999e28d-357c-4cb0-b2a3-473025df9821)

### Module

selling, projects

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.35.1",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Delivery Note/new-delivery-note-lwsbvhznfc
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/projects/projects/projects/customizations/delivery_note/delivery_note.py", line 8, in validate
    validate_proj_cust(self)
  File "apps/projects/projects/projects/customizations/delivery_note/doc_events/utility_functions.py", line 7, in validate_proj_cust
    if self.project and self.customer:
AttributeError: 'DeliveryNote' object has no attribute 'project'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Delivery Note\",\"name\":\"new-delivery-note-lwsbvhznfc\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-DN-.YYYY.-\",\"posting_date\":\"2024-11-25\",\"set_posting_time\":0,\"company\":\"French Connections\",\"is_return\":0,\"issue_credit_note\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Delivery Note Item\",\"name\":\"new-delivery-note-item-gspfvmqych\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"has_item_scanned\":0,\"item_group\":\"Raw Material\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"allow_zero_valuation_rate\":0,\"use_serial_batch_fields\":0,\"packed_qty\":0,\"cost_center\":\"Main - FC\",\"page_break\":0,\"parent\":\"new-delivery-note-lwsbvhznfc\",\"parentfield\":\"items\",\"parenttype\":\"Delivery Note\",\"idx\":1,\"qty\":10,\"conversion_factor\":1,\"stock_qty\":10,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":10,\"amount\":100,\"base_rate\":10,\"base_amount\":100,\"stock_uom_rate\":10,\"net_rate\":10,\"net_amount\":100,\"base_net_rate\":10,\"base_net_amount\":100,\"billed_amt\":0,\"incoming_rate\":0,\"weight_per_unit\":0,\"total_weight\":0,\"actual_batch_qty\":0,\"actual_qty\":-200,\"installed_qty\":0,\"received_qty\":0,\"warehouse\":\"Stores - FC\",\"item_code\":\"Nail\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Nail\",\"description\":\"<div><p>Wooden Plank</p></div>\",\"image\":\"\",\"income_account\":\"Sales - FC\",\"expense_account\":\"Cost of Goods Sold - FC\",\"discount_account\":\"Discount Account - FC\",\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"update_stock\":0,\"delivered_by_supplier\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-11-25\",\"against_blanket_order\":null,\"bom_no\":null,\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"projected_qty\":-200,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-delivery-note-item-gspfvmqych\"}],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"packed_items\":[],\"pricing_rules\":[],\"status\":\"Draft\",\"lr_date\":\"2024-11-25\",\"sales_team\":[],\"print_without_amount\":0,\"group_same_items\":0,\"is_internal_customer\":0,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"conversion_rate\":1,\"plc_conversion_rate\":1,\"posting_time\":\"12:45:20\",\"base_net_total\":100,\"net_total\":100,\"base_total\":100,\"total\":100,\"total_qty\":10,\"rounding_adjustment\":0,\"grand_total\":100,\"base_grand_total\":100,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":100,\"base_rounded_total\":100,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"amount_eligible_for_commission\":100,\"total_commission\":null,\"tax_id\":null,\"customer_name\":\"Ashish\",\"represents_company\":null,\"customer\":\"Ashish\",\"customer_address\":\"Pune East-Shipping\",\"address_display\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"shipping_address_name\":\"Pune East-Shipping\",\"shipping_address\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"company_address\":\"8848 Digital-Billing\",\"company_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"tax_category\":\"In-State\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"letter_head\":\"8848 Digital\",\"set_warehouse\":\"Stores - FC\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370088611420755110861": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 7496,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'DeliveryNote' object has no attribute 'project'",
	"exc_type": "AttributeError",
	"_exc_source": "projects (app)"
}
```
```

**Comment by vinod-8848digital** [comment]
@Purvi8848 now delivery note is able to create, save and submit also

![Screenshot from 2024-11-25 16-03-57](https://github.com/user-attachments/assets/bf0d6070-3cb9-4627-8320-0d485b6aec05)
![Screenshot from 2024-11-25 16-02-11](https://github.com/user-attachments/assets/b90c040c-7a89-4c5e-b7cd-7e81618726d7)

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
