### ISSUE TITLE
While Creating payment entry showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#724]
### Information about bug

![image](https://github.com/user-attachments/assets/82972d36-cadb-476f-a99a-9d34234d13b0)

### Module

accounts, selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00107
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 96, in validate
    self.validate_allocated_amount()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 253, in validate_allocated_amount
    self.validate_allocated_amount_with_latest_data()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 303, in validate_allocated_amount_with_latest_data
    latest_references = get_outstanding_reference_documents(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2165, in get_outstanding_reference_documents
    negative_outstanding_invoices = get_negative_outstanding_invoices(
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2423, in get_negative_outstanding_invoices
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Sales Invoice" does not exist
LINE 2:    "Sales Invoice" as voucher_type, name as voucher_no, debi...
           ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Receive\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-11-26\",\"company\":\"PP Ltd\",\"party_type\":\"Customer\",\"party\":\"Indra\",\"party_name\":\"Indra\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"party_balance\":19750,\"paid_from\":\"Debtors - PP Ltd\",\"paid_from_account_currency\":\"INR\",\"paid_from_account_balance\":0,\"paid_to\":\"Cash - PP Ltd\",\"paid_to_account_currency\":\"INR\",\"paid_to_account_balance\":76051,\"paid_amount\":3000,\"paid_amount_after_tax\":0,\"source_exchange_rate\":1,\"base_paid_amount\":3000,\"base_paid_amount_after_tax\":0,\"received_amount\":3000,\"received_amount_after_tax\":0,\"target_exchange_rate\":1,\"base_received_amount\":3000,\"base_received_amount_after_tax\":0,\"total_allocated_amount\":3000,\"base_total_allocated_amount\":3000,\"unallocated_amount\":0,\"difference_amount\":0,\"apply_tax_withholding_amount\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_date\":\"2024-11-26\",\"status\":\"Draft\",\"custom_remarks\":0,\"is_opening\":\"No\",\"letter_head\":\"PP Ltd\",\"doctype\":\"Payment Entry\",\"taxes\":[],\"deductions\":[],\"references\":[{\"modified\":\"2024-11-26 12:04:34.326268\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"reference_doctype\":\"Sales Invoice\",\"reference_name\":\"ACC-SINV-2024-46537\",\"due_date\":\"2024-11-26\",\"payment_term_outstanding\":0,\"total_amount\":3000,\"outstanding_amount\":3000,\"allocated_amount\":3000,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"account\":\"Debtors - PP Ltd\",\"payment_request_outstanding\":0,\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"doctype\":\"Payment Entry Reference\",\"__islocal\":1,\"parent\":\"new-payment-entry-jcrjgncmbb\",\"name\":\"new-payment-entry-reference-qottisknkj\"}],\"__islocal\":1,\"__unsaved\":1,\"name\":\"new-payment-entry-jcrjgncmbb\",\"__last_sync_on\":\"2024-11-26T06:34:34.517Z\",\"mode_of_payment\":\"Cash\",\"paid_to_account_type\":\"Cash\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370015869698888373551": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 14544,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"Sales Invoice\\\" does not exist\\nLINE 2:    \\\"Sales Invoice\\\" as voucher_type, name as voucher_no, debi...\\n           ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
