### ISSUE TITLE
Server error while saving Purchase Receipt

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#741]
### Information about bug

![image](https://github.com/user-attachments/assets/8d00143f-03ab-44d3-9eb1-b5ac055d8e7a)

### Module

buying

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Receipt/new-purchase-receipt-apxbubywkx
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 271, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 71, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 329, in parse_naming_series
    part = number_generator(name, digits)
  File "apps/frappe/frappe/model/naming.py", line 381, in getseries
    current = (frappe.qb.from_(series).where(series.name == key).for_update().select("current")).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Receipt\",\"name\":\"new-purchase-receipt-apxbubywkx\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-PRE-.YYYY.-\",\"posting_date\":\"2024-11-27\",\"set_posting_time\":0,\"company\":\"PP Ltd\",\"apply_putaway_rule\":0,\"is_return\":0,\"currency\":\"INR\",\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"is_subcontracted\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Receipt Item\",\"name\":\"new-purchase-receipt-item-ztwnaqjmhw\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"has_item_scanned\":0,\"item_group\":\"Sports wear\",\"received_qty\":12,\"stock_uom\":\"Nos\",\"retain_sample\":0,\"margin_type\":\"\",\"is_free_item\":0,\"apply_tds\":1,\"is_fixed_asset\":0,\"allow_zero_valuation_rate\":0,\"return_qty_from_rejected_warehouse\":0,\"has_batch_no\":1,\"has_serial_no\":0,\"use_serial_batch_fields\":0,\"include_exploded_items\":0,\"cost_center\":\"Main - PP Ltd\",\"page_break\":0,\"parent\":\"new-purchase-receipt-apxbubywkx\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"idx\":1,\"qty\":10,\"rejected_qty\":2,\"conversion_factor\":1,\"received_stock_qty\":12,\"stock_qty\":10,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":350,\"amount\":3500,\"base_rate\":350,\"base_amount\":3500,\"stock_uom_rate\":350,\"net_rate\":350,\"net_amount\":3500,\"base_net_rate\":350,\"base_net_amount\":3500,\"valuation_rate\":0,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"rate_difference_with_purchase_invoice\":0,\"billed_amt\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Finished Goods - PP Ltd\",\"brand\":null,\"sample_quantity\":0,\"asset_category\":null,\"item_code\":\"Item 8\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Item 8\",\"description\":\"Item 8\",\"image\":\"\",\"income_account\":\"Sales - PP Ltd\",\"expense_account\":\"Cost of Goods Sold - PP Ltd\",\"discount_account\":null,\"provisional_expense_account\":null,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"delivered_by_supplier\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-11-27\",\"against_blanket_order\":null,\"bom_no\":null,\"grant_commission\":1,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"supplier_part_no\":null,\"projected_qty\":0,\"actual_qty\":0,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-purchase-receipt-item-ztwnaqjmhw\",\"rejected_warehouse\":\"Goods In Transit - PP Ltd\"}],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"pricing_rules\":[],\"supplied_items\":[],\"status\":\"Draft\",\"group_same_items\":0,\"is_internal_supplier\":0,\"is_old_subcontracting_flow\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"posting_time\":\"10:57:53\",\"letter_head\":\"PP Ltd\",\"base_net_total\":3500,\"net_total\":3500,\"base_total\":3500,\"total\":3500,\"total_qty\":10,\"rounding_adjustment\":0,\"grand_total\":3500,\"taxes_and_charges_deducted\":0,\"taxes_and_charges_added\":0,\"base_grand_total\":3500,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":3500,\"base_rounded_total\":3500,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"supplier_name\":\"Bella Vita\",\"represents_company\":\"\",\"supplier\":\"Bella Vita\",\"supplier_address\":null,\"address_display\":null,\"billing_address\":\"FC Address-Billing\",\"billing_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"shipping_address\":\"PP - GJ-Billing\",\"shipping_address_display\":\"002<br>\\nSurat<br>\\nGujrat<br>395003<br>India<br>\\n<br>\\n\",\"tax_category\":\"\",\"contact_person\":\"Bella Vita-Bella Vita\",\"contact_display\":\"Bella Vita\",\"contact_email\":\"\",\"contact_mobile\":\"98984984\",\"language\":\"en\",\"set_warehouse\":\"Finished Goods - PP Ltd\",\"total_net_weight\":0,\"rejected_warehouse\":\"Goods In Transit - PP Ltd\",\"supplier_delivery_note\":\"589\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700098824099512186741": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 10358,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SerializationFailure",
	"_debug_messages": "[\"Error in query:\\ncould not serialize access due to concurrent update\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
