### ISSUE TITLE
Server Error while data import of Purchase Receipt

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#743]
### Information about bug

While trying to import 700 records of similar category, 1 record resulted into failure having the traceback as mentioned in 'Relevant log output/ Stack trace/ Full error message 

![image](https://github.com/user-attachments/assets/0536f338-78f5-4b49-a8b9-560c0b8383eb)

![image](https://github.com/user-attachments/assets/89572e7e-eeb9-46cf-bc8e-3a3ed99b7f01)

### Module

buying

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 149, in import_data
    doc = self.process_doc(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 251, in process_doc
    return self.insert_record(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 270, in insert_record
    new_doc.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 271, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 71, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 329, in parse_naming_series
    part = number_generator(name, digits)
  File "apps/frappe/frappe/model/naming.py", line 381, in getseries
    current = (frappe.qb.from_(series).where(series.name == key).for_update().select("current")).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
```

**Comment by pooja-pp8848** [comment]
Issue resolved hence closing.

![image](https://github.com/user-attachments/assets/ea898050-5f1d-467a-aa88-b985cb5f0304)
