### ISSUE TITLE
Payment Entry Creation

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#745]
### Information about bug

3.1.	While creating a Payment Entry from Purchase invoice this Error appeared. & When we try to create a payment entry and try to fetch the Purchase invoice No same Error shows. 
![image](https://github.com/user-attachments/assets/75f0948a-c080-4e92-85d8-21b27f463233)

### Module

accounts

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.36.2",
	"frappe": "15.41.0"
}
```
### Route
```
Form/Payment Entry/new-payment-entry-obkfygrlqu
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2165, in get_outstanding_reference_documents
    negative_outstanding_invoices = get_negative_outstanding_invoices(
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2423, in get_negative_outstanding_invoices
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Purchase Invoice" does not exist
LINE 2:    "Purchase Invoice" as voucher_type, name as voucher_no, c...
           ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"posting_date\":\"2024-11-27\",\"company\":\"PP Ltd\",\"party_type\":\"Supplier\",\"payment_type\":\"Pay\",\"party\":\"Bella Vita\",\"party_account\":\"Creditors - PP Ltd\",\"from_posting_date\":\"2024-10-28\",\"to_posting_date\":\"2024-11-27\",\"outstanding_amt_greater_than\":0,\"outstanding_amt_less_than\":0,\"allocate_payment_amount\":1,\"get_outstanding_invoices\":true}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_outstanding_reference_documents",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"Purchase Invoice\\\" does not exist\\nLINE 2:    \\\"Purchase Invoice\\\" as voucher_type, name as voucher_no, c...\\n           ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
