### ISSUE TITLE
Sales person creation getting server error 

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#75]
### Information about bug

Sales person creation getting server error 
![image](https://github.com/user-attachments/assets/55a3eeb9-fe54-47b5-a861-00d71f1e1680)

### Module

selling

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Person/new-sales-person-mroowiakqy
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 42, in savedocs
    run_onload(doc)
  File "apps/frappe/frappe/desk/form/load.py", line 351, in run_onload
    doc.run_method("onload")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 54, in onload
    self.load_dashboard_info()
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 60, in load_dashboard_info
    frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabSales Team.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...' AND "sales_person"='Test Sales_person' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Person\",\"name\":\"new-sales-person-mroowiakqy\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"is_group\":0,\"enabled\":1,\"targets\":[],\"sales_person_name\":\"Test Sales_person\",\"parent_sales_person\":\"Sales Team\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700380334052732447471": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 547,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabSales Team.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...' AND \\\"sales_person\\\"='Test Sales_person' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by aasif-patel** [comment]
@tinadn now we can save the SP, but onload this error occurs please check...

![image](https://github.com/user-attachments/assets/3a4b4548-12f3-4d06-bd83-07aba98071da)


### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Person/Test
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 299, in get_open_count
    out["timeline_data"] = module.get_timeline_data(doctype, name)
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 126, in get_timeline_data
    sales_order_activity = _fetch_activity("Sales Order", "transaction_date")
  File "apps/erpnext/erpnext/setup/doctype/sales_person/sales_person.py", line 123, in _fetch_activity
    .run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "("
LINE 1: ...D "tabSales Order"."transaction_date">CURRENT_DATE()-INTERVA...
                                                             ^


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Sales Person",
		"name": "Test",
		"items": "[\"Sales Order\",\"Delivery Note\",\"Sales Invoice\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nSELECT EXTRACT(epoch FROM \\\"tabSales Order\\\".\\\"transaction_date\\\"),COUNT(*) FROM \\\"tabSales Order\\\" JOIN \\\"tabSales Team\\\" ON \\\"tabSales Order\\\".\\\"name\\\"=\\\"tabSales Team\\\".\\\"parent\\\" WHERE \\\"tabSales Team\\\".\\\"sales_person\\\"=%(param1)s AND \\\"tabSales Order\\\".\\\"transaction_date\\\">CURRENT_DATE()-INTERVAL '1 YEAR' GROUP BY \\\"tabSales Order\\\".\\\"transaction_date\\\" {'param1': 'Test'}\"]"
}
```

**Comment by tinadn** [comment]
Working fine. Hence closing
