### ISSUE TITLE
Payment Entry for Multi Currency

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#764]
### Information about bug

While creating a Payment entry of Multi currency Purchase invoice and change the Exchange rate this Error is showing. 
![image](https://github.com/user-attachments/assets/71ae15bc-ddb1-4356-9189-a777876521ae)

### Module

accounts

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.36.2",
	"frappe": "15.41.0"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00104
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1317, in show_accounting_ledger_preview
    gl_columns, gl_data = get_accounting_ledger_preview(doc, filters)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1362, in get_accounting_ledger_preview
    doc.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1161, in make_gl_entries
    self.make_exchange_gain_loss_journal()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1471, in make_exchange_gain_loss_journal
    je = create_gain_loss_journal(
  File "apps/erpnext/erpnext/accounts/utils.py", line 2213, in create_gain_loss_journal
    journal_entry.submit()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 174, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 186, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 985, in make_gl_entries
    gl_map = self.build_gl_map()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 972, in build_gl_map
    "project": d.project,
AttributeError: 'JournalEntryAccount' object has no attribute 'project'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"company": "PP Ltd",
		"doctype": "Payment Entry",
		"docname": "ACC-PAY-2024-00104"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.controllers.stock_controller.show_accounting_ledger_preview",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'JournalEntryAccount' object has no attribute 'project'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
