### ISSUE TITLE
Error while Submitting Purchase Receipt.

### ISSUE THREAD

**Issue by aasif-patel** [8848digital/erpnext#77]
### Information about bug

When hit Submit button following error occurs 
![image](https://github.com/user-attachments/assets/5dd528e0-443e-42fa-bc20-2088cd55aec6)

### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Receipt/MAT-PRE-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 369, in on_submit
    self.update_billing_status()
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 874, in update_billing_status
    update_billing_percentage(pr_doc, update_modified=update_modified)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 1059, in update_billing_percentage
    item_wise_returned_qty = get_item_wise_returned_qty(pr_doc)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 1108, in get_item_wise_returned_qty
    frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.AmbiguousColumn: column reference "modified" is ambiguous
LINE 1: ...(abs("tabPurchase Receipt Item".qty)) as qty, MAX(modified) ...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-PRE-2024-00001\",\"owner\":\"Administrator\",\"creation\":\"2024-09-27 16:55:23.888240\",\"modified\":\"2024-09-27 16:55:23.888240\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"_Test Supplier 1\",\"naming_series\":\"MAT-PRE-.YYYY.-\",\"supplier\":\"_Test Supplier 1\",\"supplier_name\":\"_Test Supplier 1\",\"supplier_delivery_note\":null,\"subcontracting_receipt\":null,\"posting_date\":\"2024-09-27\",\"posting_time\":\"16:55:23.926980\",\"set_posting_time\":0,\"company\":\"8848 Digital\",\"apply_putaway_rule\":0,\"is_return\":0,\"return_against\":null,\"cost_center\":null,\"project\":null,\"currency\":\"INR\",\"conversion_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"scan_barcode\":null,\"set_warehouse\":null,\"set_from_warehouse\":null,\"rejected_warehouse\":null,\"is_subcontracted\":0,\"supplier_warehouse\":null,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":4562,\"base_net_total\":4562,\"total\":4562,\"net_total\":4562,\"tax_withholding_net_total\":4562,\"base_tax_withholding_net_total\":4562,\"tax_category\":\"\",\"taxes_and_charges\":null,\"shipping_rule\":null,\"incoterm\":null,\"named_place\":null,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":4562,\"base_rounding_adjustment\":0,\"base_rounded_total\":4562,\"base_in_words\":\"\",\"grand_total\":4562,\"rounding_adjustment\":0,\"rounded_total\":4562,\"in_words\":\"\",\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":null,\"supplier_address\":null,\"address_display\":null,\"contact_person\":null,\"contact_display\":null,\"contact_mobile\":null,\"contact_email\":null,\"shipping_address\":null,\"shipping_address_display\":null,\"billing_address\":null,\"billing_address_display\":null,\"tc_name\":null,\"terms\":null,\"status\":\"Draft\",\"per_billed\":0,\"per_returned\":0,\"auto_repeat\":null,\"letter_head\":null,\"group_same_items\":0,\"select_print_heading\":null,\"language\":\"en\",\"transporter_name\":null,\"lr_no\":null,\"lr_date\":null,\"instructions\":null,\"is_internal_supplier\":0,\"represents_company\":\"\",\"inter_company_reference\":null,\"remarks\":null,\"range\":null,\"amended_from\":null,\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Receipt\",\"pricing_rules\":[],\"supplied_items\":[],\"taxes\":[],\"items\":[{\"name\":\"3nb7qf1t6h\",\"owner\":\"Administrator\",\"creation\":\"2024-09-27 16:55:23.888240\",\"modified\":\"2024-09-27 16:55:23.888240\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"item_code\":\"_Test FG Item\",\"product_bundle\":null,\"supplier_part_no\":null,\"item_name\":\"_Test FG Item\",\"description\":\"_Test FG Item 6\",\"brand\":null,\"item_group\":\"_Test Item Group Desktops\",\"image\":\"\",\"received_qty\":1,\"qty\":1,\"rejected_qty\":0,\"uom\":\"_Test UOM\",\"stock_uom\":\"_Test UOM\",\"conversion_factor\":1,\"retain_sample\":0,\"sample_quantity\":0,\"received_stock_qty\":0,\"stock_qty\":1,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":4562,\"amount\":4562,\"base_rate\":4562,\"base_amount\":4562,\"pricing_rules\":\"\",\"stock_uom_rate\":4562,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":4562,\"net_amount\":4562,\"item_tax_template\":null,\"base_net_rate\":4562,\"base_net_amount\":4562,\"valuation_rate\":4562,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"rate_difference_with_purchase_invoice\":0,\"billed_amt\":0,\"warehouse\":\"Stores - 8D\",\"rejected_warehouse\":null,\"from_warehouse\":null,\"material_request\":null,\"purchase_order\":null,\"purchase_invoice\":null,\"allow_zero_valuation_rate\":0,\"return_qty_from_rejected_warehouse\":0,\"is_fixed_asset\":0,\"asset_location\":null,\"asset_category\":null,\"schedule_date\":null,\"quality_inspection\":null,\"material_request_item\":null,\"purchase_order_item\":null,\"purchase_invoice_item\":null,\"purchase_receipt_item\":null,\"delivery_note_item\":null,\"putaway_rule\":null,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":1,\"rejected_serial_and_batch_bundle\":null,\"serial_no\":null,\"rejected_serial_no\":null,\"batch_no\":null,\"include_exploded_items\":0,\"bom\":null,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"expense_account\":\"Cost of Goods Sold - 8D\",\"item_tax_rate\":\"{}\",\"wip_composite_asset\":null,\"provisional_expense_account\":null,\"project\":null,\"cost_center\":\"Main - 8D\",\"page_break\":0,\"sales_order\":null,\"sales_order_item\":null,\"subcontracting_receipt_item\":null,\"parent\":\"MAT-PRE-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"doctype\":\"Purchase Receipt Item\",\"__unsaved\":1}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\"},\"__last_sync_on\":\"2024-09-27T11:25:24.354Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370076511976898900351": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4196,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "AmbiguousColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn reference \\\"modified\\\" is ambiguous\\nLINE 1: ...(abs(\\\"tabPurchase Receipt Item\\\".qty)) as qty, MAX(modified) ...\\n                                                             ^\\n\"]"
}
```

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

manual install

**Comment by aasif-patel** [comment]
@nilesh8848 please check item with batch number

**Comment by nilesh8848** [comment]
https://github.com/8848digital/erpnext/pull/143

**Comment by aasif-patel** [comment]
Resolved hence closing...
