### ISSUE TITLE
While creating sales order, systems shows this server error "Possible source of error: india_compliance (app)"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#780]
### Information about bug

While creating sales order, systems shows this server error "Possible source of error: india_compliance (app)"
![image](https://github.com/user-attachments/assets/d1a42e5c-1355-4e12-bf88-f0685f916faf)

### Module

selling

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

India Compliance: v15.14.2 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"india_compliance": "15.14.2",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Order/new-sales-order-sliqtwsbol
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/party.py", line 74, in get_party_details
    return _get_party_details(
  File "apps/erpnext/erpnext/accounts/party.py", line 122, in _get_party_details
    party_address, shipping_address = set_address_details(
  File "apps/erpnext/erpnext/accounts/party.py", line 263, in set_address_details
    get_regional_address_details(party_details, doctype, company)
  File "apps/erpnext/erpnext/__init__.py", line 150, in caller
    return frappe.get_attr(overrides[function_path][-1])(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 912, in update_party_details
    get_gst_details(party_details, doctype, company, update_place_of_supply=True)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1005, in get_gst_details
    else get_place_of_supply(party_details, doctype)
  File "apps/india_compliance/india_compliance/gst_india/utils/__init__.py", line 417, in get_place_of_supply
    gst_state_number, gst_state = frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 515, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 619, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 892, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "gst_state_number" does not exist
LINE 1: SELECT "gst_state_number","gst_state" FROM "tabAddress" WHER...
               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"party": "Indra",
		"party_type": "Customer",
		"price_list": "Standard Selling",
		"posting_date": "2024-12-02",
		"fetch_payment_terms_template": 1,
		"company_address": "PP-MH-Billing",
		"currency": "INR",
		"company": "PP Ltd",
		"doctype": "Sales Order"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.party.get_party_details",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "india_compliance (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"gst_state_number\\\" does not exist\\nLINE 1: SELECT \\\"gst_state_number\\\",\\\"gst_state\\\" FROM \\\"tabAddress\\\" WHER...\\n               ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
