### ISSUE TITLE
While creating Item, system gives this server error "AttributeError: 'Item' object has no attribute 'gst_hsn_code' Possible source of error: india_compliance (app)"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#781]
### Information about bug

While creating Item, system gives this server error "AttributeError: 'Item' object has no attribute 'gst_hsn_code' Possible source of error: india_compliance (app)"
![image](https://github.com/user-attachments/assets/84523fc9-e7ea-4b40-a752-a624af13ae11)

### Module

stock

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

India Compliance: v15.14.2 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"india_compliance": "15.14.2",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Item/new-item-dosemyczza
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 10, in validate
    validate_hsn_code(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 30, in validate_hsn_code
    _validate_hsn_code(doc.gst_hsn_code)
AttributeError: 'Item' object has no attribute 'gst_hsn_code'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Item\",\"name\":\"new-item-dosemyczza\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"STO-ITEM-.YYYY.-\",\"item_group\":\"Raw Material\",\"stock_uom\":\"Nos\",\"disabled\":0,\"allow_alternative_item\":0,\"is_stock_item\":1,\"has_variants\":0,\"is_fixed_asset\":0,\"auto_create_assets\":0,\"is_grouped_asset\":0,\"uoms\":[],\"end_of_life\":\"2099-12-31\",\"default_material_request_type\":\"Purchase\",\"valuation_method\":\"FIFO\",\"allow_negative_stock\":0,\"barcodes\":[],\"reorder_levels\":[],\"has_batch_no\":0,\"create_new_batch\":0,\"has_expiry_date\":0,\"retain_sample\":0,\"has_serial_no\":0,\"variant_based_on\":\"Item Attribute\",\"attributes\":[],\"enable_deferred_expense\":0,\"enable_deferred_revenue\":0,\"item_defaults\":[],\"min_order_qty\":0,\"is_purchase_item\":1,\"is_customer_provided_item\":0,\"delivered_by_supplier\":0,\"supplier_items\":[],\"country_of_origin\":\"India\",\"grant_commission\":1,\"is_sales_item\":1,\"customer_items\":[],\"taxes\":[],\"inspection_required_before_purchase\":0,\"inspection_required_before_delivery\":0,\"include_item_in_manufacturing\":1,\"is_sub_contracted_item\":0,\"item_code\":\"ITM-014\",\"item_name\":\"ITM-014\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370074370584397848381": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 861,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'Item' object has no attribute 'gst_hsn_code'",
	"exc_type": "AttributeError",
	"_exc_source": "india_compliance (app)"
}
```
```

**Comment by anandk-spyke-o1** [comment]
Resolved
