### ISSUE TITLE
Error on submission of payment entry

### ISSUE THREAD

**Issue by shubham-DT** [8848digital/erpnext#784]
### Information about bug

Geeting server error when submitting Payment Entry created from Sales Order

![Uploading Screenshot from 2024-12-02 15-59-28.png…]()

### Module

accounts

### Version

Frappe - pre-prod
Erpnext - pre-prod

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00133
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 113, in on_submit
    self.update_advance_paid()  # advance_paid_status depends on the payment request amount
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1476, in update_advance_paid
    ).set_total_advance_paid()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1977, in set_total_advance_paid
    self.set_advance_payment_status()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1981, in set_advance_payment_status
    paid_amount = frappe.get_value(
  File "apps/frappe/frappe/__init__.py", line 2079, in get_value
    return db.get_value(*args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 515, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 619, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 892, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Request.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...SAL-ORD-2024-11503' AND "docstatus"= '1' ORDER BY "modified"...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PAY-2024-00133\",\"owner\":\"Administrator\",\"creation\":\"2024-12-02 15:59:03.315870\",\"modified\":\"2024-12-02 15:59:03.624513\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Receive\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-12-02\",\"company\":\"PP Ltd\",\"mode_of_payment\":\"Cash\",\"party_type\":\"Customer\",\"party\":\"Ashish\",\"party_name\":\"Ashish\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"bank_account\":null,\"party_bank_account\":null,\"contact_person\":null,\"contact_email\":null,\"party_balance\":318860,\"paid_from\":\"Debtors - PP Ltd\",\"paid_from_account_type\":\"Receivable\",\"paid_from_account_currency\":\"INR\",\"paid_from_account_balance\":0,\"paid_to\":\"Cash - PP Ltd\",\"paid_to_account_type\":\"Cash\",\"paid_to_account_currency\":\"INR\",\"paid_to_account_balance\":13432.75,\"paid_amount\":3000,\"paid_amount_after_tax\":3000,\"source_exchange_rate\":1,\"base_paid_amount\":3000,\"base_paid_amount_after_tax\":3000,\"received_amount\":3000,\"received_amount_after_tax\":3000,\"target_exchange_rate\":1,\"base_received_amount\":3000,\"base_received_amount_after_tax\":3000,\"total_allocated_amount\":3000,\"base_total_allocated_amount\":3000,\"unallocated_amount\":0,\"difference_amount\":0,\"purchase_taxes_and_charges_template\":null,\"sales_taxes_and_charges_template\":null,\"apply_tax_withholding_amount\":0,\"tax_withholding_category\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_no\":null,\"reference_date\":\"2024-12-02\",\"clearance_date\":null,\"location\":null,\"project\":null,\"department\":null,\"purchase_invoice\":null,\"cost_center\":null,\"status\":\"Draft\",\"custom_remarks\":0,\"remarks\":\"Amount INR 3000 received from Ashish\\nAmount INR 3000 against Sales Order SAL-ORD-2024-11503\",\"base_in_words\":\"INR Three Thousand only.\",\"is_opening\":\"No\",\"letter_head\":\"PP Ltd\",\"print_heading\":null,\"bank\":null,\"bank_account_no\":null,\"payment_order\":null,\"in_words\":\"INR Three Thousand only.\",\"auto_repeat\":null,\"amended_from\":null,\"title\":\"Ashish\",\"doctype\":\"Payment Entry\",\"references\":[{\"name\":\"etqpoo413q\",\"owner\":\"Administrator\",\"creation\":\"2024-12-02 15:59:03.315870\",\"modified\":\"2024-12-02 15:59:03.483771\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"reference_doctype\":\"Sales Order\",\"reference_name\":\"SAL-ORD-2024-11503\",\"due_date\":null,\"bill_no\":null,\"payment_term\":null,\"payment_term_outstanding\":0,\"account_type\":null,\"payment_type\":null,\"total_amount\":3000,\"outstanding_amount\":3000,\"allocated_amount\":3000,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"account\":\"Debtors - PP Ltd\",\"payment_request\":null,\"payment_request_outstanding\":0,\"parent\":\"ACC-PAY-2024-00133\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"doctype\":\"Payment Entry Reference\",\"__unsaved\":1}],\"deductions\":[],\"taxes\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-12-02T10:29:03.879Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700339737929964081251": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 2486,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPayment Request.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...SAL-ORD-2024-11503' AND \\\"docstatus\\\"= '1' ORDER BY \\\"modified\\\"...\\n                                                             ^\\n\"]"
}
```
```

**Comment by shubham-DT** [comment]
working fine now 
close the issue

**Comment by tinadn** [comment]
Resolved. Hence closing.
