### ISSUE TITLE
Submitting of Sales order 

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#786]
### Information about bug

When we create Sales Order from Quotation and Enable Reserve Stock Check Box this Error is Shown
![image](https://github.com/user-attachments/assets/5f4cd573-409a-482b-8eb3-3b5d2e8eb955)

### Module

selling

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.36.2",
	"frappe": "15.41.0"
}
```
### Route
```
Form/Sales Order/SAL-ORD-2024-09455-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 384, in on_submit
    self.create_stock_reservation_entries()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 689, in create_stock_reservation_entries
    create_stock_reservation_entries(
  File "apps/erpnext/erpnext/stock/doctype/stock_reservation_entry/stock_reservation_entry.py", line 1053, in create_stock_reservation_entries_for_so_items
    sre.project = sales_order.project
AttributeError: 'SalesOrder' object has no attribute 'project'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"SAL-ORD-2024-09455\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":0,\"title\":\"{customer_name}\",\"naming_series\":\"SAL-ORD-.YYYY.-\",\"customer\":\"Shyam Lal Jain\",\"customer_name\":\"Shyam Lal Jain\",\"order_type\":\"Sales\",\"transaction_date\":\"2024-11-20\",\"delivery_date\":\"2024-12-10\",\"company\":\"PP Ltd\",\"skip_delivery_note\":0,\"currency\":\"USD\",\"conversion_rate\":62.9,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"set_warehouse\":\"Stores - PP Ltd\",\"reserve_stock\":1,\"total_qty\":200,\"total_net_weight\":0,\"base_total\":350667.5,\"base_net_total\":350667.5,\"total\":5575,\"net_total\":5575,\"tax_category\":\"\",\"exempt_from_sales_tax\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":350667.5,\"base_rounding_adjustment\":0,\"base_rounded_total\":350667.5,\"base_in_words\":\"\",\"grand_total\":5575,\"rounding_adjustment\":0,\"rounded_total\":5575,\"in_words\":\"\",\"advance_paid\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"customer_address\":\"Shyam Lal Jain-Billing\",\"address_display\":\"Add Line 1<br>\\nAdd Line 2<br>USA, \",\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"company_address\":\"PP-MH-Billing\",\"company_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"status\":\"Draft\",\"delivery_status\":\"Not Delivered\",\"per_delivered\":0,\"per_billed\":0,\"per_picked\":0,\"billing_status\":\"Not Billed\",\"loyalty_points\":0,\"loyalty_amount\":0,\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"language\":\"en\",\"is_internal_customer\":0,\"doctype\":\"Sales Order\",\"taxes\":[],\"payment_schedule\":[{\"name\":\"fmmn4lc1u5\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":1,\"due_date\":\"2024-12-15\",\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount\":0,\"payment_amount\":5575,\"outstanding\":5575,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":350667.5,\"parent\":\"SAL-ORD-2024-09455\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Order\",\"doctype\":\"Payment Schedule\",\"__unsaved\":1}],\"pricing_rules\":[],\"packed_items\":[],\"items\":[{\"name\":\"fmmnp28ofp\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Plastic Bottle 1Ltr\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"delivery_date\":\"2024-12-10\",\"item_name\":\"Plastic Bottle 1Ltr\",\"description\":\"Plastic Bottle\",\"item_group\":\"Istiyaq\",\"image\":\"\",\"qty\":50,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":50,\"stock_reserved_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":5,\"amount\":250,\"base_rate\":314.5,\"base_amount\":15725,\"stock_uom_rate\":5,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":5,\"net_amount\":250,\"base_net_rate\":314.5,\"base_net_amount\":15725,\"billed_amt\":0,\"valuation_rate\":29.1,\"gross_profit\":-1205,\"delivered_by_supplier\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - PP Ltd\",\"prevdoc_docname\":\"SAL-QTN-2024-00172\",\"quotation_item\":\"fltvscfg04\",\"against_blanket_order\":0,\"blanket_order_rate\":0,\"projected_qty\":509,\"actual_qty\":410,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"page_break\":0,\"item_tax_rate\":\"{}\",\"transaction_date\":\"2024-11-20\",\"parent\":\"SAL-ORD-2024-09455\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"doctype\":\"Sales Order Item\",\"__unsaved\":1},{\"name\":\"fmmnqaob9b\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":2,\"item_code\":\"Plastic Bottle 2Ltr\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"delivery_date\":\"2024-12-10\",\"item_name\":\"Plastic Bottle 2Ltr\",\"description\":\"Plastic Bottle\",\"item_group\":\"Istiyaq\",\"image\":\"\",\"qty\":50,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":50,\"stock_reserved_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":10,\"amount\":500,\"base_rate\":629,\"base_amount\":31450,\"stock_uom_rate\":10,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":10,\"net_amount\":500,\"base_net_rate\":629,\"base_net_amount\":31450,\"billed_amt\":0,\"valuation_rate\":46.29,\"gross_profit\":-1814.5,\"delivered_by_supplier\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - PP Ltd\",\"prevdoc_docname\":\"SAL-QTN-2024-00172\",\"quotation_item\":\"fltvcmlth3\",\"against_blanket_order\":0,\"blanket_order_rate\":0,\"projected_qty\":509,\"actual_qty\":410,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"page_break\":0,\"item_tax_rate\":\"{}\",\"transaction_date\":\"2024-11-20\",\"parent\":\"SAL-ORD-2024-09455\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"doctype\":\"Sales Order Item\",\"__unsaved\":1},{\"name\":\"fmmndi6gka\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":3,\"item_code\":\"Tiffin Box 2 Pcs Steel\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"delivery_date\":\"2024-12-10\",\"item_name\":\"Tiffin Box 2 Pcs Steel\",\"description\":\"Plastic Bottle\",\"item_group\":\"Istiyaq\",\"image\":\"\",\"qty\":45,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":45,\"stock_reserved_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":40,\"amount\":1800,\"base_rate\":2516,\"base_amount\":113220,\"stock_uom_rate\":40,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":40,\"net_amount\":1800,\"base_net_rate\":2516,\"base_net_amount\":113220,\"billed_amt\":0,\"valuation_rate\":448.35,\"gross_profit\":-18375.75,\"delivered_by_supplier\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - PP Ltd\",\"prevdoc_docname\":\"SAL-QTN-2024-00172\",\"quotation_item\":\"fltvcj1lir\",\"against_blanket_order\":0,\"blanket_order_rate\":0,\"projected_qty\":609,\"actual_qty\":510,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"page_break\":0,\"item_tax_rate\":\"{}\",\"transaction_date\":\"2024-11-20\",\"parent\":\"SAL-ORD-2024-09455\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"doctype\":\"Sales Order Item\",\"__unsaved\":1},{\"name\":\"fmmn395kc0\",\"owner\":\"istiyaq@8848digital.com\",\"creation\":\"2024-12-02 16:41:30.287995\",\"modified\":\"2024-12-02 16:49:38.405864\",\"modified_by\":\"istiyaq@8848digital.com\",\"docstatus\":0,\"idx\":4,\"item_code\":\"Tiffin Box 3 Pcs Steel\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"delivery_date\":\"2024-12-10\",\"item_name\":\"Tiffin Box 3 Pcs Steel\",\"description\":\"Plastic Bottle\",\"item_group\":\"Istiyaq\",\"image\":\"\",\"qty\":55,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":55,\"stock_reserved_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":55,\"amount\":3025,\"base_rate\":3459.5,\"base_amount\":190272.5,\"stock_uom_rate\":55,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":55,\"net_amount\":3025,\"base_net_rate\":3459.5,\"base_net_amount\":190272.5,\"billed_amt\":0,\"valuation_rate\":333.95,\"gross_profit\":-15342.25,\"delivered_by_supplier\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - PP Ltd\",\"prevdoc_docname\":\"SAL-QTN-2024-00172\",\"quotation_item\":\"fltvcmqn82\",\"against_blanket_order\":0,\"blanket_order_rate\":0,\"projected_qty\":409,\"actual_qty\":310,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"page_break\":0,\"item_tax_rate\":\"{}\",\"transaction_date\":\"2024-11-20\",\"parent\":\"SAL-ORD-2024-09455\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"doctype\":\"Sales Order Item\",\"__unsaved\":1}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"has_unreserved_stock\":true}}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370016093038911441251": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 53160,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'SalesOrder' object has no attribute 'project'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Execution time: 0.00 sec\", \"SELECT item_code,sum(qty) \\n\\t\\t\\t\\tFROM \\\"tabSales Order Item\\\" \\n\\t\\t\\t\\tWHERE prevdoc_docname = 'SAL-QTN-2024-00172' and docstatus = '1'\\n\\t\\t\\t\\tGroup BY item_code;\"]"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
