### ISSUE TITLE
Server error while creating company (https://apnaclub-postgresv15.8848digitalerp.com)

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#788]
### App Versions
```
{
	"apnaklub_mobile_app": "0.0.1",
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"india_compliance": "15.14.2",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
setup-wizard/0
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/setup/doctype/company/company.py", line 240, in on_update
    self.create_default_warehouses()
  File "apps/erpnext/erpnext/setup/doctype/company/company.py", line 298, in create_default_warehouses
    warehouse.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1092, in run_before_save_methods
    self.run_method("before_save")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/apnaklub_mobile_app/apnaklub_mobile_app/apnaklub_mobile_app/doc_events/warehouse.py", line 6, in before_save
    custom_cost_center = frappe.db.get_value("Warehouse", doc.parent_warehouse, "custom_cost_center")
  File "apps/frappe/frappe/database/database.py", line 515, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 619, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 892, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "custom_cost_center" does not exist
LINE 1: SELECT "custom_cost_center" FROM "tabWarehouse" WHERE "name"...
               ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 61, in setup_complete
    return process_setup_stages(stages, args)
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 81, in process_setup_stages
    task.get("fn")(task.get("args"))
  File "apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 55, in setup_company
    fixtures.install_company(args)
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 421, in install_company
    make_records(records)
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 426, in make_records
    frappe.db.rollback(save_point=savepoint)
  File "apps/frappe/frappe/database/database.py", line 1050, in rollback
    self.sql(f"rollback to savepoint {save_point}")
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidSavepointSpecification: savepoint "setup_fixtures_creation" does not exist


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"language\":\"English\",\"country\":\"India\",\"timezone\":\"Asia/Kolkata\",\"currency\":\"INR\",\"company_name\":\"ABCD\",\"company_abbr\":\"AB\",\"default_gst_rate\":\"18.0\",\"chart_of_accounts\":\"India - Chart of Accounts\",\"fy_start_date\":\"2024-04-01\",\"fy_end_date\":\"2025-03-31\",\"setup_demo\":1,\"enable_audit_trail\":0}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete",
	"request_id": null
}
```
### Response Data
```
{
	"setup_wizard_failure_message": "Failed to setup company",
	"exception": "",
	"exc_type": "InvalidSavepointSpecification",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"custom_cost_center\\\" does not exist\\nLINE 1: SELECT \\\"custom_cost_center\\\" FROM \\\"tabWarehouse\\\" WHERE \\\"name\\\"...\\n               ^\\n\", \"Error in query:\\nsavepoint \\\"setup_fixtures_creation\\\" does not exist\\n\"]"
}
```

### Module

other

### Version

.

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Resolved. Hence closing.
