### ISSUE TITLE
While Job card creation getting server error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#79]
### Information about bug

While Job card creation getting server error
![image](https://github.com/user-attachments/assets/c43b8b97-134d-442c-8599-29ef434dd897)

### Module

manufacturing

### Version

	"erpnext": "15.34.0",
	"frappe": "15.41.0",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Job Card/new-job-card-lwvjmzktpv
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 1109, in get_operations
    return frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 5:     order by idx asc
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Operation",
		"ignore_user_permissions": 0,
		"reference_doctype": "Job Card",
		"page_length": 10,
		"query": "erpnext.manufacturing.doctype.job_card.job_card.get_operations",
		"filters": "{\"work_order\":\"_T-Work Order-00001\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InvalidColumnReference",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nfor SELECT DISTINCT, ORDER BY expressions must appear in select list\\nLINE 5:     order by idx asc\\n                     ^\\n\"]"
}
```
```

**Comment by tohidmalik002** [comment]
PR raised https://github.com/8848digital/erpnext/pull/124

**Comment by aasif-patel** [comment]
@8848swa please PR merged please check and close this if resolved.

**Comment by 8848swa** [comment]
Created one job card successfully. but unable to submit it. Please check.

![image](https://github.com/user-attachments/assets/ff1c2874-ffe3-4212-b187-849a81918e28)
### App Versions
```
{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Job Card/PO-JOB00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 664, in on_submit
    self.update_work_order()
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 761, in update_work_order
    data = self.get_current_operation_data()
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 843, in get_current_operation_data
    return frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2064, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabJob Card.modified" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabJob Card"."modified" DESC
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"PO-JOB00001\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 15:41:24.477932\",\"modified\":\"2024-10-01 15:41:51.772306\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"PO-JOB.#####\",\"work_order\":\"_T-Work Order-00001\",\"bom_no\":\"BOM-_Test FG Item-001\",\"production_item\":\"_Test FG Item\",\"posting_date\":\"2024-10-01\",\"company\":\"_Test Company\",\"for_quantity\":10,\"total_completed_qty\":10,\"process_loss_qty\":0,\"expected_start_date\":\"2024-09-27 11:58:13.762902\",\"time_required\":200,\"expected_end_date\":\"2024-09-27 15:18:13.762902\",\"actual_start_date\":\"2024-10-01 15:41:38\",\"total_time_in_mins\":0.10002,\"actual_end_date\":\"2024-10-01 15:41:44\",\"operation\":\"Test Operation\",\"wip_warehouse\":\"_Test Warehouse - _TC\",\"workstation\":\"_Test Workstation 1\",\"is_corrective_job_card\":0,\"hour_rate\":100,\"item_name\":\"_Test FG Item\",\"transferred_qty\":0,\"requested_qty\":0,\"status\":\"Work In Progress\",\"operation_id\":\"bqus3s0acl\",\"sequence_id\":0,\"job_started\":0,\"current_time\":0,\"doctype\":\"Job Card\",\"employee\":[{\"name\":\"br6h6ecdpt\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 15:41:24.477932\",\"modified\":\"2024-10-01 15:41:51.772306\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"employee\":\"HR-EMP-00001\",\"time_in_mins\":0,\"completed_qty\":0,\"parent\":\"PO-JOB00001\",\"parentfield\":\"employee\",\"parenttype\":\"Job Card\",\"doctype\":\"Job Card Time Log\"}],\"time_logs\":[{\"name\":\"br6h7dv7s1\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 15:41:24.477932\",\"modified\":\"2024-10-01 15:41:51.772306\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"employee\":\"HR-EMP-00001\",\"from_time\":\"2024-10-01 15:41:38\",\"to_time\":\"2024-10-01 15:41:44\",\"time_in_mins\":0.10002,\"completed_qty\":10,\"parent\":\"PO-JOB00001\",\"parentfield\":\"time_logs\",\"parenttype\":\"Job Card\",\"doctype\":\"Job Card Time Log\"}],\"sub_operations\":[],\"items\":[],\"scheduled_time_logs\":[{\"name\":\"bqvs862fhh\",\"owner\":\"Administrator\",\"creation\":\"2024-10-01 15:41:24.477932\",\"modified\":\"2024-10-01 15:41:51.772306\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"from_time\":\"2024-09-27 11:58:13.762902\",\"to_time\":\"2024-09-27 15:18:13.762902\",\"time_in_mins\":200,\"parent\":\"PO-JOB00001\",\"parentfield\":\"scheduled_time_logs\",\"parenttype\":\"Job Card\",\"doctype\":\"Job Card Scheduled Time\"}],\"scrap_items\":[],\"__onload\":{\"job_card_excess_transfer\":0,\"work_order_closed\":false,\"has_stock_entry\":null},\"__last_sync_on\":\"2024-10-01T10:11:46.380Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370070815872892810261": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 5482,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabJob Card.modified\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 5:     order by \\\"tabJob Card\\\".\\\"modified\\\" DESC\\n                     ^\\n\"]"
}
```

**Comment by tohidmalik002** [comment]
PR Raised: https://github.com/8848digital/erpnext/pull/155

**Comment by aasif-patel** [comment]
Resolved hence closing...
