### ISSUE TITLE
Web page error: The Address and Issue records do not load when clicked.

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#8]
### Information about bug

When I click on the Issue and Address records, the page does not load.
![Screenshot from 2024-09-04 18-11-32](https://github.com/user-attachments/assets/0bbe2069-a3b5-499b-b756-f6d01f4b6b06)

### Module

other

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.40.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
SyntaxError: Unexpected token '<', "<html>
  <"... is not valid JSON
    at JSON.parse (<anonymous>)
    at frappe.request.report_error (request.js:528:18)
    at 500 (request.js:224:20)
    at Object.<anonymous> (request.js:356:6)
    at I (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at en (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
```

**Comment by VishvParikh** [comment]
Issue is resolved 
some wrong data in in the address webform 
fieldname: condition_json 

the wrong data present in the condition_json in the address webfrom

**Comment by aasif-patel** [comment]
Traceback for the issue

> request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/website/doctype/web_form/web_form.py", line 120, in on_update
    path = export_module_json(self, self.is_standard, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 36, in export_module_json
    export_to_files(record_list=[[doc.doctype, doc.name]], record_module=module, create_init=is_standard)
  File "apps/frappe/frappe/modules/export_file.py", line 26, in export_to_files
    write_document_file(
  File "apps/frappe/frappe/modules/export_file.py", line 35, in write_document_file
    doc_export = doc.as_dict(no_nulls=True)
  File "apps/frappe/frappe/model/base_document.py", line 469, in as_dict
    doc = self.get_valid_dict(convert_dates_to_str=convert_dates_to_str, ignore_nulls=no_nulls)
  File "apps/frappe/frappe/model/base_document.py", line 382, in get_valid_dict
    frappe.throw(_("Value for {0} cannot be a list").format(_(df.label, context=df.parent)))
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Value for Condition JSON cannot be a list

**Comment by aasif-patel** [comment]
Same code same data perfectly working on version 15 with Mariadb.

**Comment by tinadn** [comment]
Resolved. Hence closing.
