### ISSUE TITLE
There was an issue while migrating the DocType: Web Form

### ISSUE THREAD

**Issue by 8848jay** [8848digital/erpnext#809]
### Information about bug

![Screenshot 2024-12-06 143923](https://github.com/user-attachments/assets/7589af4f-bcc3-4e58-9f85-e02ef08f7334)

### Module

other

### Version

ERPNext: v15.36.2 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
There was an issue while migrating the DocType: Web Form

Queued rebuilding of search index for site1

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/commands/site.py", line 660, in migrate
    SiteMigration(
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/migrate.py", line 186, in run
    self.run_schema_updates()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/migrate.py", line 52, in wrapper
    raise e
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/migrate.py", line 44, in wrapper
    ret = method(*args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/migrate.py", line 120, in run_schema_updates
    frappe.model.sync.sync_all()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/sync.py", line 43, in sync_all
    sync_for(app, force, reset_permissions=reset_permissions)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/modules/import_file.py", line 239, in import_doc
    doc.insert()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 511, in on_update
    raise e
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 508, in on_update
    frappe.db.updatedb(self.name, Meta(self))
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 428, in updatedb
    db_table.sync()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/schema.py", line 44, in sync
    self.alter()
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/postgres/schema.py", line 159, in alter
    raise e
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/postgres/schema.py", line 140, in alter
    frappe.db.sql(final_alter_query)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/frappe/frappe-bench-postgres/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatatypeMismatch: column "condition_json" cannot be cast automatically to type json
HINT:  You might need to specify "USING condition_json::json".

**Comment by tinadn** [comment]
Resolved. Hence closing.
