### ISSUE TITLE
While mapping default expense account and default income account, facing this error "HINT: Perhaps you meant to reference the table alias "account". Possible source of error: erpnext (app)" This issue arises only when using my user ID, whereas the error does not occur when using others user ID.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#818]
### Information about bug

While mapping default expense account and default income account, facing this error "HINT: Perhaps you meant to reference the table alias "account". Possible source of error: erpnext (app)" This issue arises only when using my user ID, whereas the error does not occur when using others user ID.

![image](https://github.com/user-attachments/assets/cd6d6dec-60b3-44d3-ab7f-083690683e75)

### Module

stock

### Version

ERPNext: v15.38.4 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Item/new-item-pmaldbbeno
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 676, in get_expense_account
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: invalid reference to FROM-clause entry for table "tabAccount"
LINE 8: ...t.company = 'French Connections'  and (((coalesce("tabAccoun...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "account".


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Account",
		"ignore_user_permissions": 0,
		"reference_doctype": "Item Default",
		"page_length": 10,
		"query": "erpnext.controllers.queries.get_expense_account",
		"filters": "{\"company\":\"French Connections\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedTable",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ninvalid reference to FROM-clause entry for table \\\"tabAccount\\\"\\nLINE 8: ...t.company = 'French Connections'  and (((coalesce(\\\"tabAccoun...\\n                                                             ^\\nHINT:  Perhaps you meant to reference the table alias \\\"account\\\".\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
