### ISSUE TITLE
While submitting Purchase Receipt, systems shows this error, "TypeError: unsupported operand type(s) for &: 'int' and 'Field' Possible source of error: erpnext (app)"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#824]
### Information about bug

While submitting Purchase Receipt, systems shows this error, "TypeError: unsupported operand type(s) for &: 'int' and 'Field' Possible source of error: erpnext (app)"

![image](https://github.com/user-attachments/assets/16d3ab87-10fa-4986-bfec-a847add67a59)

### Module

stock

### Version

ERPNext: v15.38.4 (pre-prod)

Frappe Framework: v15.45.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.45.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Receipt/MAT-PRE-2024-14261
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1778, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 361, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 135, in make_gl_entries
    make_gl_entries(gl_entries, from_repost=from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 38, in make_gl_entries
    validate_disabled_accounts(gl_map)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 125, in validate_disabled_accounts
    .where(Account.name.isin(accounts) & Account.disabled == 1 & Account.is_group == 1 & Account.company == gl_map[0].company)
TypeError: unsupported operand type(s) for &: 'int' and 'Field'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"MAT-PRE-2024-14261\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-11 11:25:32.594859\",\"modified\":\"2024-12-11 11:25:32.594859\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":0,\"title\":\"Moms Co\",\"naming_series\":\"MAT-PRE-.YYYY.-\",\"supplier\":\"Moms Co\",\"supplier_name\":\"Moms Co\",\"posting_date\":\"2024-12-11\",\"posting_time\":\"11:25:32.637519\",\"set_posting_time\":0,\"company\":\"French Connections\",\"apply_putaway_rule\":0,\"is_return\":0,\"cost_center\":\"Main - FC\",\"currency\":\"INR\",\"conversion_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"set_warehouse\":\"Stores - FC\",\"is_subcontracted\":0,\"total_qty\":100,\"total_net_weight\":0,\"base_total\":1000,\"base_net_total\":1000,\"total\":1000,\"net_total\":1000,\"tax_withholding_net_total\":1000,\"base_tax_withholding_net_total\":1000,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":1000,\"base_rounding_adjustment\":0,\"base_rounded_total\":1000,\"base_in_words\":\"\",\"grand_total\":1000,\"rounding_adjustment\":0,\"rounded_total\":1000,\"in_words\":\"\",\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"contact_person\":\"Moms Co-Moms Co\",\"contact_display\":\"Moms Co\",\"contact_mobile\":\"85955569\",\"contact_email\":\"\",\"shipping_address\":\"FC Address-Billing\",\"shipping_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"billing_address\":\"FC Address-Billing\",\"billing_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"status\":\"Draft\",\"per_billed\":0,\"per_returned\":0,\"letter_head\":\"8848 Digital\",\"group_same_items\":0,\"language\":\"en\",\"is_internal_supplier\":0,\"represents_company\":\"\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Receipt\",\"supplied_items\":[],\"pricing_rules\":[],\"taxes\":[],\"items\":[{\"name\":\"n7aepg7lvl\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-11 11:25:32.594859\",\"modified\":\"2024-12-11 11:25:32.594859\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"Item to test Landed Cost Voucher 2\",\"item_name\":\"Item to test Landed Cost Voucher 2\",\"description\":\"Item to test Landed Cost Voucher\",\"item_group\":\"Raw Material\",\"image\":\"\",\"received_qty\":100,\"qty\":100,\"rejected_qty\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"conversion_factor\":1,\"retain_sample\":0,\"sample_quantity\":0,\"received_stock_qty\":100,\"stock_qty\":100,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":10,\"amount\":1000,\"base_rate\":10,\"base_amount\":1000,\"pricing_rules\":\"\",\"stock_uom_rate\":10,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":10,\"net_amount\":1000,\"base_net_rate\":10,\"base_net_amount\":1000,\"valuation_rate\":10,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"rate_difference_with_purchase_invoice\":0,\"billed_amt\":0,\"warehouse\":\"Stores - FC\",\"is_fixed_asset\":0,\"allow_zero_valuation_rate\":0,\"return_qty_from_rejected_warehouse\":0,\"has_batch_no\":0,\"has_serial_no\":0,\"use_serial_batch_fields\":1,\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"expense_account\":\"Cost of Goods Sold - FC\",\"item_tax_rate\":\"{}\",\"cost_center\":\"Main - FC\",\"page_break\":0,\"parent\":\"MAT-PRE-2024-14261\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"doctype\":\"Purchase Receipt Item\"}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\"},\"__last_sync_on\":\"2024-12-11T06:24:02.552Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery37009174924519210011": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 401,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: unsupported operand type(s) for &: 'int' and 'Field'",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Fajjf** [comment]
Hello @Purvi8848  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Purvi8848** [comment]
Facing same issue in stock entry doctype.
![image](https://github.com/user-attachments/assets/c7df8a1c-27fb-4552-aeb1-056fc402a5dd)

**Comment by tinadn** [comment]
Resolved. Hence closing.
