### ISSUE TITLE
While submitting Purchase Invoice Facing this issue "^ Possible source of error: erpnext (app)"

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#827]
### Information about bug

While submitting Purchase Invoice Facing this issue "^ Possible source of error: erpnext (app)"
![image](https://github.com/user-attachments/assets/6c8304b8-d28a-418a-b272-f817a6d47d7f)

### Module

buying

### Version

ERPNext: v15.38.4 (pre-prod)

Frappe Framework: v15.45.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.45.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-25574
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1778, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 714, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 748, in make_gl_entries
    make_gl_entries(
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 42, in make_gl_entries
    create_payment_ledger_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1814, in create_payment_ledger_entry
    ple.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1130, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_ledger_entry/payment_ledger_entry.py", line 177, in on_update
    update_voucher_outstanding(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1833, in update_voucher_outstanding
    voucher_outstanding = ple_query.get_voucher_outstandings(vouchers, common_filter=common_filter)
  File "apps/erpnext/erpnext/accounts/utils.py", line 2137, in get_voucher_outstandings
    self.query_for_outstanding()
  File "apps/erpnext/erpnext/accounts/utils.py", line 2100, in query_for_outstanding
    self.voucher_outstandings = self.cte_query_voucher_amount_and_outstanding.run(as_dict=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Ledger Entry.remarks" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...n_account_currency") "amount_in_account_currency","remarks" ...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PINV-2024-25573\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-12 11:40:38.032820\",\"modified\":\"2024-12-12 11:40:38.032820\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":0,\"title\":\"Bella Vita\",\"naming_series\":\"ACC-PINV-.YYYY.-\",\"supplier\":\"Bella Vita\",\"supplier_name\":\"Bella Vita\",\"company\":\"French Connections\",\"posting_date\":\"2024-12-12\",\"posting_time\":\"11:40:38.087330\",\"set_posting_time\":0,\"due_date\":\"2025-01-11\",\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":0,\"currency\":\"INR\",\"conversion_rate\":1,\"use_transaction_date_exchange_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"is_subcontracted\":0,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":10,\"base_net_total\":10,\"total\":10,\"net_total\":10,\"tax_withholding_net_total\":10,\"base_tax_withholding_net_total\":10,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":10,\"base_rounding_adjustment\":0,\"base_rounded_total\":10,\"base_in_words\":\"\",\"grand_total\":10,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":10,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":10,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"contact_person\":\"Bella Vita-Bella Vita\",\"contact_display\":\"Bella Vita\",\"contact_mobile\":\"98984984\",\"contact_email\":\"\",\"shipping_address\":\"FC Address-Billing\",\"shipping_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"billing_address\":\"FC Address-Billing\",\"billing_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"payment_terms_template\":\"_Test Payment Term Template\",\"ignore_default_payment_terms_template\":0,\"status\":\"Draft\",\"per_received\":0,\"credit_to\":\"Creditors - FC\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"against_expense_account\":\"Cost of Goods Sold - FC\",\"letter_head\":\"8848 Digital\",\"group_same_items\":0,\"language\":\"en\",\"on_hold\":0,\"is_internal_supplier\":0,\"represents_company\":\"\",\"supplier_group\":\"PP Ltd Suppliers\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Invoice\",\"payment_schedule\":[{\"name\":\"hrtcnhonc4\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-12 11:40:38.032820\",\"modified\":\"2024-12-12 11:40:38.032820\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":1,\"payment_term\":\"_Test COD\",\"description\":\"_Test Cash on Delivery\",\"due_date\":\"2024-12-12\",\"invoice_portion\":50,\"discount_type\":\"Percentage\",\"discount_date\":\"2024-12-12\",\"discount\":0,\"payment_amount\":5,\"outstanding\":5,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":5,\"parent\":\"ACC-PINV-2024-25573\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Payment Schedule\"},{\"name\":\"hrtcfcg2jv\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-12 11:40:38.032820\",\"modified\":\"2024-12-12 11:40:38.032820\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":2,\"payment_term\":\"_Test N30\",\"description\":\"_Test Net 30 Days\",\"due_date\":\"2025-01-11\",\"invoice_portion\":50,\"discount_type\":\"Percentage\",\"discount_date\":\"2024-12-12\",\"discount\":0,\"payment_amount\":5,\"outstanding\":5,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":5,\"parent\":\"ACC-PINV-2024-25573\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Payment Schedule\"}],\"tax_withheld_vouchers\":[],\"taxes\":[],\"supplied_items\":[],\"advance_tax\":[],\"advances\":[],\"items\":[{\"name\":\"hrtcvao9sn\",\"owner\":\"purvi@8848digital.com\",\"creation\":\"2024-12-12 11:40:38.032820\",\"modified\":\"2024-12-12 11:40:38.032820\",\"modified_by\":\"purvi@8848digital.com\",\"docstatus\":0,\"idx\":1,\"item_code\":\"Freight\",\"item_name\":\"Freight\",\"description\":\"Freight\",\"item_group\":\"Services\",\"image\":\"\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"stock_qty\":1,\"price_list_rate\":10,\"base_price_list_rate\":10,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":10,\"amount\":10,\"base_rate\":10,\"base_amount\":10,\"pricing_rules\":\"\",\"stock_uom_rate\":10,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":10,\"net_amount\":10,\"base_net_rate\":10,\"base_net_amount\":10,\"valuation_rate\":0,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"warehouse\":\"Stores - FC\",\"has_batch_no\":0,\"has_serial_no\":0,\"use_serial_batch_fields\":1,\"expense_account\":\"Cost of Goods Sold - FC\",\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{}\",\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"Main - FC\",\"page_break\":0,\"parent\":\"ACC-PINV-2024-25573\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Invoice Item\"}],\"pricing_rules\":[],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\",\"supplier_tds\":null},\"__last_sync_on\":\"2024-12-12T06:11:06.591Z\",\"change_amount\":0,\"base_change_amount\":0}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370085791678541709661": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 6900,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabPayment Ledger Entry.remarks\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...n_account_currency\\\") \\\"amount_in_account_currency\\\",\\\"remarks\\\" ...\\n                                                             ^\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
