### ISSUE TITLE
Server error on creating Return / Credit Note

### ISSUE THREAD

**Issue by anandk-spyke-o1** [8848digital/erpnext#829]
### Information about bug

Server error on creating Return / Credit Note.
### Route
```
Form/Sales Invoice/ACC-SINV-2024-51216

### Module

selling

### Version

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### Traceback

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
           ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1922, in make_sales_return
    return make_return_doc("Sales Invoice", source_name, target_doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 675, in make_return_doc
    doclist = get_mapped_doc(
              ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 152, in get_mapped_doc
    map_child_doc(source_d, target_doc, table_map, source_doc)
  File "apps/frappe/frappe/model/mapper.py", line 268, in map_child_doc
    map_doc(source_d, target_d, table_map, source_parent)
  File "apps/frappe/frappe/model/mapper.py", line 177, in map_doc
    table_map["postprocess"](source_doc, target_doc, source_parent)
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 583, in update_item
    returned_qty_map = get_returned_qty_map_for_row(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/controllers/sales_and_purchase_return.py", line 293, in get_returned_qty_map_for_row
    parent = DocType(doctype)
             ^^^^^^^
NameError: name 'DocType' is not defined. Did you mean: 'doctype'?
```

**Comment by anandk-spyke-o1** [comment]
resolved
