### ISSUE TITLE
Error in UAE VAT 201 Report

### ISSUE THREAD

**Issue by Barathpalanisamy** [8848digital/erpnext#832]
### App Versions
```
{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.45.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
query-report/UAE VAT 201
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1778, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 931, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 931, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/regional/report/uae_vat_201/uae_vat_201.py", line 11, in execute
    data, emirates, amounts_by_emirate = get_data(filters)
  File "apps/erpnext/erpnext/regional/report/uae_vat_201/uae_vat_201.py", line 38, in get_data
    emirates, amounts_by_emirate = append_vat_on_sales(data, filters)
  File "apps/erpnext/erpnext/regional/report/uae_vat_201/uae_vat_201.py", line 47, in append_vat_on_sales
    emirates, amounts_by_emirate = standard_rated_expenses_emiratewise(data, filters)
  File "apps/erpnext/erpnext/regional/report/uae_vat_201/uae_vat_201.py", line 76, in standard_rated_expenses_emiratewise
    total_emiratewise = get_total_emiratewise(filters)
  File "apps/erpnext/erpnext/regional/report/uae_vat_201/uae_vat_201.py", line 137, in get_total_emiratewise
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column s.vat_emirate does not exist
LINE 2:     s.vat_emirate as emirate, sum(i.base_net_amount) as tota...
            ^


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "UAE VAT 201",
		"filters": "{\"company\":\"PP Ltd\",\"from_date\":\"2024-09-12\",\"to_date\":\"2024-12-12\"}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn s.vat_emirate does not exist\\nLINE 2:     s.vat_emirate as emirate, sum(i.base_net_amount) as tota...\\n            ^\\n\"]"
}
```

### Module

regional

### Version

ERPNext: v15.38.4 (pre-prod)
Frappe Framework: v15.45.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
