### ISSUE TITLE
Error in Accounts Payable Summary Report

### ISSUE THREAD

**Issue by Barathpalanisamy** [8848digital/erpnext#845]
### App Versions
```
{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.38.4",
	"frappe": "15.45.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
query-report/Accounts Payable Summary
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1778, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 931, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 931, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/accounts_payable_summary/accounts_payable_summary.py", line 15, in execute
    return AccountsReceivableSummary(filters).run(args)
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.py", line 29, in run
    self.get_data(args)
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.py", line 34, in get_data
    self.receivables = ReceivablePayableReport(self.filters).run(args)[1]
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 63, in run
    self.get_data()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 102, in get_data
    self.get_invoice_details()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 449, in get_invoice_details
    for pi in frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
TypeError: not all arguments converted during string formatting

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Accounts Payable Summary",
		"filters": "{\"company\":\"PP Ltd\",\"report_date\":\"2024-12-16\",\"ageing_based_on\":\"Due Date\",\"range\":\"30, 60, 90, 120\",\"party\":[],\"department\":[]}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: not all arguments converted during string formatting",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\nnot all arguments converted during string formatting\"]"
}
```

### Module

accounts

### Version

ERPNext: v15.38.4 (pre-prod)
Frappe Framework: v15.45.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
