### ISSUE TITLE
Server Error while submitting Payment Entry 

### ISSUE THREAD

**Issue by IamSaiyyamChhetri** [8848digital/erpnext#850]
### Information about bug

When trying to submit Payment Entry I'm getting server error.

- Previous change file Commit:
   - https://github.com/8848digital/erpnext/commit/78b869a1e4694f0d34fc361ec9d56aec8285766f
   
- Point to be note :
   - It's in my local with single ErpNext app without restoring db.

### App Versions
```
{
	"erpnext": "15.38.4",
	"frappe": "15.41.0"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
           ^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 109, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1160, in make_gl_entries
    make_gl_entries(gl_entries, cancel=cancel, adv_adj=adv_adj, clearing_date=clearing_date)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 49, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost, clearing_date=clearing_date)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 389, in save_entries
    validate_against_pcv(is_opening, gl_map[0]["posting_date"], gl_map[0]["company"])
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 693, in validate_against_pcv
    last_pcv_date = frappe.db.sql(
                    ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "posting_date" does not exist
LINE 1: SELECT posting_date FROM "tabPeriod Closing Voucher"
               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PAY-2024-00001\",\"owner\":\"saiyyam@8848digital.com\",\"creation\":\"2024-12-16 14:52:26.940615\",\"modified\":\"2024-12-16 14:52:27.154549\",\"modified_by\":\"saiyyam@8848digital.com\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Pay\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-12-16\",\"company\":\"8848 D\",\"party_type\":\"Supplier\",\"party\":\"Saiyyam\",\"party_name\":\"Saiyyam\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"party_balance\":0,\"paid_from\":\"Bank Account - 8D\",\"paid_from_account_type\":\"Bank\",\"paid_from_account_currency\":\"INR\",\"paid_from_account_balance\":0,\"paid_to\":\"Creditors - 8D\",\"paid_to_account_type\":\"Payable\",\"paid_to_account_currency\":\"INR\",\"paid_to_account_balance\":0,\"paid_amount\":10000,\"paid_amount_after_tax\":10000,\"source_exchange_rate\":1,\"base_paid_amount\":10000,\"base_paid_amount_after_tax\":10000,\"received_amount\":10000,\"received_amount_after_tax\":10000,\"target_exchange_rate\":1,\"base_received_amount\":10000,\"base_received_amount_after_tax\":10000,\"total_allocated_amount\":0,\"base_total_allocated_amount\":0,\"unallocated_amount\":10000,\"difference_amount\":0,\"apply_tax_withholding_amount\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_no\":\"1234\",\"reference_date\":\"2024-12-16\",\"status\":\"Draft\",\"custom_remarks\":0,\"remarks\":\"Amount INR 10000 to Saiyyam\\nTransaction reference no 1234 dated 2024-12-16\",\"base_in_words\":\"INR Ten Thousand only.\",\"is_opening\":\"No\",\"in_words\":\"INR Ten Thousand only.\",\"title\":\"Saiyyam\",\"doctype\":\"Payment Entry\",\"deductions\":[],\"taxes\":[],\"references\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-12-17T05:30:51.707Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700225405805786510261": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 610,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"posting_date\\\" does not exist\\nLINE 1: SELECT posting_date FROM \\\"tabPeriod Closing Voucher\\\"\\n               ^\\n\"]"
}
```

### Module

accounts

### Version

Frappe / ERPNext : 15

### Installation method

easy-install

**Comment by tinadn** [comment]
Resolved. Hence closing.
