### ISSUE TITLE
'PaymentReconciliation' object has no attribute 'clearing_date'

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#859]
### Information about bug

test_reverse_payment_reconciliation (erpnext.accounts.doctype.payment_entry.test_payment_entry.TestPaymentEntry)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/test_payment_entry.py", line 1633, in test_reverse_payment_reconciliation
    pr.reconcile()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 547, in reconcile
    self.reconcile_allocations()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 521, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions, self.clearing_date)
AttributeError: 'PaymentReconciliation' object has no attribute 'clearing_date'
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
