### ISSUE TITLE
Facing Server error while linking advance payment to Sales Invoice from payment tab

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#871]
### Information about bug

![image](https://github.com/user-attachments/assets/a7a11d11-3ff8-49bf-8251-9d9011b39024)
![image](https://github.com/user-attachments/assets/4bc758a4-0ef7-4763-8727-0a124ad0e8ac)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.46.1 (pre-prod)

Frappe Framework: v15.50.1 (pre-prod)

India Compliance: v15.14.5 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.46.1",
	"frappe": "15.50.1",
	"india_compliance": "15.14.5",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-buzqhnywla
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 332, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1177, in set_advances
    res = self.get_advance_entries(
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1235, in get_advance_entries
    payment_entries = get_advance_payment_entries_for_regional(
  File "apps/erpnext/erpnext/__init__.py", line 149, in caller
    return frappe.get_attr(overrides[function_path][-1])(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/overrides/payment_entry.py", line 345, in get_advance_payment_entries_for_regional
    payment_entries = get_advance_payment_entries(
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 2929, in get_advance_payment_entries
    allocated = list(q.run(as_dict=True))
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = boolean
LINE 1: ...'Debtors - FC') OR ("tabPayment Entry"."paid_from"=true AND ...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"SINV-24-00013\",\"owner\":\"Administrator\",\"creation\":\"2024-12-20 12:46:30.662418\",\"modified\":\"2024-12-20 12:46:30.662418\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Krishna\",\"naming_series\":\"SINV-.YY.-\",\"customer\":\"Krishna\",\"irn\":null,\"customer_name\":\"Krishna\",\"ewaybill\":null,\"e_waybill_status\":\"\",\"tax_id\":null,\"company\":\"French Connections\",\"company_tax_id\":null,\"posting_date\":\"2024-12-20\",\"posting_time\":\"12:46:30.803371\",\"set_posting_time\":0,\"due_date\":\"2024-12-20\",\"is_pos\":0,\"pos_profile\":null,\"is_consolidated\":0,\"is_return\":0,\"return_against\":null,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"is_reverse_charge\":0,\"is_export_with_gst\":0,\"amended_from\":null,\"location\":null,\"purchase_invoice\":null,\"cost_center\":null,\"project\":null,\"department\":null,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"scan_barcode\":null,\"update_stock\":0,\"set_warehouse\":\"Stores - FC\",\"set_target_warehouse\":null,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":5000,\"base_net_total\":5000,\"total\":5000,\"net_total\":5000,\"exempt_from_sales_tax\":0,\"tax_category\":\"\",\"taxes_and_charges\":null,\"shipping_rule\":null,\"incoterm\":null,\"named_place\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":5000,\"base_rounding_adjustment\":0,\"base_rounded_total\":5000,\"base_in_words\":\"INR Five Thousand only.\",\"grand_total\":5000,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":5000,\"in_words\":\"INR Five Thousand only.\",\"total_advance\":0,\"outstanding_amount\":5000,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_account\":null,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":null,\"gst_breakup_table\":null,\"total_billing_hours\":0,\"total_billing_amount\":0,\"cash_bank_account\":null,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"account_for_change_amount\":null,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"write_off_account\":null,\"write_off_cost_center\":null,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"loyalty_program\":\"new year\",\"loyalty_redemption_account\":null,\"loyalty_redemption_cost_center\":null,\"customer_address\":\"Krishna Billing Address-Billing\",\"address_display\":\"D-13, M.I.D.C. Industrial Area, Thermax Limited<br>\\nR.D.Aga Road, Chinchwad<br>Pune<br>\\nMaharashtra<br>411019<br>India<br>\\n<br>\\n\",\"billing_address_gstin\":null,\"gst_category\":\"Unregistered\",\"place_of_supply\":null,\"contact_person\":null,\"contact_display\":null,\"contact_mobile\":null,\"contact_email\":null,\"territory\":\"All Territories\",\"shipping_address_name\":null,\"shipping_address\":null,\"port_address\":null,\"dispatch_address_name\":null,\"dispatch_address\":null,\"company_address\":\"FC Address-Billing\",\"company_gstin\":null,\"company_address_display\":\"Ratanshinagar<br>\\nSangli<br>\\nMaharashtra<br>416416<br>India<br>\\n<br>\\n\",\"company_contact_person\":null,\"ignore_default_payment_terms_template\":0,\"payment_terms_template\":null,\"tc_name\":null,\"terms\":null,\"po_no\":\"\",\"po_date\":null,\"debit_to\":\"Debtors - FC\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"unrealized_profit_loss_account\":null,\"against_income_account\":\"Sales - FC\",\"sales_partner\":null,\"amount_eligible_for_commission\":5000,\"commission_rate\":0,\"total_commission\":0,\"letter_head\":\"8848 Digital\",\"group_same_items\":0,\"invoice_copy\":\"Original for Recipient\",\"select_print_heading\":null,\"language\":\"en\",\"transporter\":null,\"gst_transporter_id\":null,\"driver\":null,\"lr_no\":null,\"vehicle_no\":null,\"distance\":0,\"transporter_name\":null,\"mode_of_transport\":\"Road\",\"driver_name\":null,\"lr_date\":\"2024-12-20\",\"gst_vehicle_type\":\"Regular\",\"ecommerce_gstin\":null,\"ecommerce_supply_type\":null,\"port_code\":null,\"shipping_bill_number\":null,\"shipping_bill_date\":null,\"subscription\":null,\"from_date\":null,\"auto_repeat\":null,\"to_date\":null,\"status\":\"Draft\",\"einvoice_status\":\"\",\"inter_company_invoice_reference\":null,\"campaign\":null,\"represents_company\":null,\"source\":null,\"customer_group\":\"Commercial\",\"is_internal_customer\":0,\"is_discounted\":0,\"remarks\":null,\"doctype\":\"Sales Invoice\",\"timesheets\":[],\"sales_team\":[],\"packed_items\":[],\"items\":[{\"name\":\"2ojcf6l6rs\",\"owner\":\"Administrator\",\"creation\":\"2024-12-20 12:46:30.662418\",\"modified\":\"2024-12-20 12:46:30.662418\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"item_code\":\"Service Item\",\"item_name\":\"Service Item\",\"customer_item_code\":null,\"description\":\"Service Item\",\"gst_hsn_code\":\"01011020\",\"item_group\":\"All Item Groups\",\"brand\":null,\"image\":\"\",\"qty\":1,\"stock_uom\":\"Hrs\",\"uom\":\"Hrs\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":5000,\"amount\":5000,\"item_tax_template\":null,\"gst_treatment\":\"Nil-Rated\",\"base_rate\":5000,\"base_amount\":5000,\"pricing_rules\":null,\"stock_uom_rate\":5000,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":5000,\"net_amount\":5000,\"base_net_rate\":5000,\"base_net_amount\":5000,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":0,\"sgst_rate\":0,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":0,\"sgst_amount\":0,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"delivered_by_supplier\":0,\"income_account\":\"Sales - FC\",\"is_fixed_asset\":0,\"asset\":null,\"finance_book\":null,\"expense_account\":\"Cost of Goods Sold - FC\",\"discount_account\":null,\"deferred_revenue_account\":null,\"service_stop_date\":null,\"enable_deferred_revenue\":0,\"service_start_date\":null,\"service_end_date\":null,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":null,\"warehouse\":\"Stores - FC\",\"target_warehouse\":null,\"quality_inspection\":null,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"serial_no\":null,\"batch_no\":null,\"actual_qty\":0,\"company_total_stock\":0,\"sales_order\":\"SAL-ORD-2024-13515\",\"so_detail\":\"8cp7e211db\",\"sales_invoice_item\":null,\"delivery_note\":null,\"dn_detail\":null,\"delivered_qty\":0,\"purchase_order\":null,\"purchase_order_item\":null,\"location\":null,\"purchase_invoice\":null,\"cost_center\":\"Main - FC\",\"department\":null,\"project\":null,\"page_break\":0,\"parent\":\"SINV-24-00013\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\",\"__unsaved\":1}],\"taxes\":[],\"pricing_rules\":[],\"payments\":[],\"advances\":[],\"payment_schedule\":[{\"name\":\"gchup2eces\",\"owner\":\"Administrator\",\"creation\":\"2024-12-20 12:46:30.662418\",\"modified\":\"2024-12-20 12:46:30.662418\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"payment_term\":null,\"description\":null,\"due_date\":\"2024-12-20\",\"mode_of_payment\":null,\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount_date\":null,\"discount\":0,\"payment_amount\":5000,\"outstanding\":5000,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":5000,\"parent\":\"SINV-24-00013\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\",\"__unsaved\":1}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-12-20T07:16:31.149Z\"}",
		"method": "set_advances"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedFunction",
	"_exc_source": "india_compliance (app)",
	"_debug_messages": "[\"Error in query:\\noperator does not exist: character varying = boolean\\nLINE 1: ...'Debtors - FC') OR (\\\"tabPayment Entry\\\".\\\"paid_from\\\"=true AND ...\\n                                                             ^\\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\\n\"]"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
