### ISSUE TITLE
Server Error while creating POS invoice

### ISSUE THREAD

**Issue by arvind8848** [8848digital/erpnext#875]
### Information about bug

![image](https://github.com/user-attachments/assets/6092c10b-79de-46db-9a55-006cfd04ebc6)

### Module

accounts, selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.46.1 (pre-prod)

Frappe Framework: v15.50.1 (pre-prod)

India Compliance: v15.14.5 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.46.1",
	"frappe": "15.50.1",
	"india_compliance": "15.14.5",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/POS Invoice/new-pos-invoice-mmhzrhozlo
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 93, in search_widget
    is_whitelisted(frappe.get_attr(query))
  File "apps/frappe/frappe/__init__.py", line 1716, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.accounts.doctype.pos_invoice.pos_invoice' has no attribute 'item_query'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Item",
		"ignore_user_permissions": 0,
		"reference_doctype": "POS Invoice Item",
		"page_length": 10,
		"query": "erpnext.accounts.doctype.pos_invoice.pos_invoice.item_query",
		"filters": "{\"has_variants\":[\"=\",0],\"is_sales_item\":[\"=\",1],\"disabled\":[\"=\",0],\"is_fixed_asset\":[\"=\",0],\"pos_profile\":[\"=\",\"_Test POS Profile 3\"]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: module 'erpnext.accounts.doctype.pos_invoice.pos_invoice' has no attribute 'item_query'",
	"exc_type": "AttributeError"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
