### ISSUE TITLE
GroupingError in sql quey for payment entry

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#880]
### Information about bug

test_advance_reverse_payment_reconciliation (erpnext.accounts.doctype.payment_entry.test_payment_entry.TestPaymentEntry)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/test_payment_entry.py", line 1685, in test_advance_reverse_payment_reconciliation
    pr.get_unreconciled_entries()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 130, in get_unreconciled_entries
    self.get_nonreconciled_payment_entries()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 136, in get_nonreconciled_payment_entries
    payment_entries = self.get_payment_entries()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 182, in get_payment_entries
    payment_entries = get_advance_payment_entries_for_regional(
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/__init__.py", line 149, in caller
    return frappe.get_attr(overrides[function_path][-1])(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/payment_entry.py", line 363, in get_advance_payment_entries_for_regional
    taxes = get_taxes_summary(company, payment_entries)
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/payment_entry.py", line 430, in get_taxes_summary
    frappe.qb.from_(gl_entry)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPayment Entry.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...debit_in_account_currency") "tax_amount_reversed","tabPaymen...
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
