### ISSUE TITLE
Status error in sql query

### ISSUE THREAD

**Issue by tinadn** [8848digital/erpnext#882]
### Information about bug

test_closed_delivery_note (erpnext.stock.doctype.delivery_note.test_delivery_note.TestDeliveryNote)

### Module

accounts

### Version

Frappe - v15
Erpnext - v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/test_delivery_note.py", line 891, in test_closed_delivery_note
    self.assertEqual(frappe.db.get_value("Delivery Note", dn.name, "Status"), "Closed")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 518, in get_value
    result = self.get_values(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 622, in get_values
    out = self._get_values_from_table(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 895, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Status" does not exist
LINE 1: SELECT "Status" FROM "tabDelivery Note" WHERE "name"='DN-24-...
               ^
HINT:  Perhaps you meant to reference the column "tabDelivery Note.status".
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
