### ISSUE TITLE
While creating sales order for drop-ship, Address dispatch name field showing server error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#884]
### Information about bug

Steps-1 Create new sales order
2. Enable check box of Supplier delivers to Customer and link supplier
3. In Address tab, Address dispatch name field showing server error

![image](https://github.com/user-attachments/assets/2a3cf2e9-668f-40b7-8baa-c0798b9c8ac1)
![image](https://github.com/user-attachments/assets/c895b9e7-2cd7-42bb-a91a-fb24e05ff4f5)
![image](https://github.com/user-attachments/assets/c0dffab4-f2b2-4dc5-a28a-6318736a4435)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.46.1 (pre-prod)

Frappe Framework: v15.50.1 (pre-prod)

India Compliance: v15.14.5 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.46.1",
	"frappe": "15.50.1",
	"india_compliance": "15.14.5",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Order/new-sales-order-kweoigpise
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2484, in wrapper
    return fn(**kwargs)
  File "apps/frappe/frappe/contacts/doctype/address/address.py", line 269, in address_query
    link_doctype = filters.pop("link_doctype")
KeyError: 'link_doctype'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Address",
		"ignore_user_permissions": 0,
		"reference_doctype": "Sales Order",
		"page_length": 10,
		"query": "frappe.contacts.doctype.address.address.address_query",
		"filters": "{}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "KeyError: 'link_doctype'",
	"exc_type": "KeyError"
}
```
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
