### ISSUE TITLE
Selling Report - Not able to view Pending SO Items For Purchase Request Report.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#90]
### Information about bug

while reloading the report showing error.
![image](https://github.com/user-attachments/assets/9ca600ba-403d-46eb-926b-79fa16341d7b)

### Module

selling

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Pending SO Items For Purchase Request
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/utils.py", line 1115, in get_children
    acc = frappe.get_list(doctype, fields=fields, filters=filters)
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
LINE 3: ...ocstatus", 0) < '2' and coalesce("parent_account","") = '' a...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Account",
		"company": "8848 Digital",
		"parent": "8848 Digital",
		"is_root": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.utils.get_children",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Syntax error in query:\\nselect \\\"name\\\" as value, \\\"is_group\\\" as expandable, \\\"root_type\\\", \\\"report_type\\\", \\\"account_currency\\\"\\n\\t\\t\\tfrom \\\"tabAccount\\\"\\n\\t\\t\\twhere coalesce(\\\"tabAccount\\\".\\\"docstatus\\\", 0) < '2' and coalesce(\\\"parent_account\\\",\\\"\\\") = '' and \\\"tabAccount\\\".\\\"company\\\" = '8848 Digital'\\n\\t\\t\\t\\n\\t\\t\\t order by \\\"tabAccount\\\".\\\"modified\\\" ASC \"]"
}
```
```

**Comment by aasif-patel** [comment]
Resolved hence closing...
