### ISSUE TITLE
7 Test cases of Purchase order getting failed

### ISSUE THREAD

**Issue by rahulgupta8848** [8848digital/erpnext#919]
### Information about bug

getting error while runninf this command: bench run-tests --doctype "Purchase Order"

### Module

buying

### Version

Installed Apps
Assets: v0.0.1 (pre-prod)
CRM: v0.0.1 (master)
ERPNext: v15.47.1 (pre-prod)
Frappe Framework: v15.51.0 (pre-prod)
India Compliance: v15.14.6 (pre-prod)
Payments: v0.0.1 (version-15)
Projects: v0.0.1 (master)
sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
....
======================================================================
ERROR: test_auto_create_subcontracting_order (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1139, in test_auto_create_subcontracting_order
    make_subcontracted_items()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/controllers/tests/test_subcontracting_controller.py", line 1241, in make_subcontracted_items
    make_item(item, properties)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 73, in make_item
    item.insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 10, in validate
    validate_hsn_code(doc)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 30, in validate_hsn_code
    _validate_hsn_code(doc.gst_hsn_code)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py", line 58, in validate_hsn_code
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code.

======================================================================
ERROR: test_multi_po_pi (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1231, in test_multi_po_pi
    create_po_pi(**args)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1536, in create_po_pi
    doc_po =  create_purchase_order(**po)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1486, in create_purchase_order
    po.insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1636, in validate_transaction
    if validate_mandatory_fields(doc, ("company_gstin", "place_of_supply")) is False:
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 239, in validate_mandatory_fields
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Company GSTIN is a mandatory field for GST Transactions

======================================================================
ERROR: test_new_sc_flow (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1066, in test_new_sc_flow
    po = create_po_for_sc_testing()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1340, in create_po_for_sc_testing
    make_subcontracted_items()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/controllers/tests/test_subcontracting_controller.py", line 1241, in make_subcontracted_items
    make_item(item, properties)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 73, in make_item
    item.insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 10, in validate
    validate_hsn_code(doc)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 30, in validate_hsn_code
    _validate_hsn_code(doc.gst_hsn_code)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py", line 58, in validate_hsn_code
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code.

======================================================================
ERROR: test_purchase_invoice_deletion (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1320, in test_purchase_invoice_deletion
    pi = make_purchase_invoice(po.name)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 1081, in make_purchase_invoice
    doc = frappe.get_doc("Purchase Receipt", source_name)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1291, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 137, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 98, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Purchase Receipt PUR-ORD-2024-15334 not found

======================================================================
ERROR: test_single_po_pi (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1208, in test_single_po_pi
    create_po_pi(**args)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1536, in create_po_pi
    doc_po =  create_purchase_order(**po)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1486, in create_purchase_order
    po.insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 1636, in validate_transaction
    if validate_mandatory_fields(doc, ("company_gstin", "place_of_supply")) is False:
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 239, in validate_mandatory_fields
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Company GSTIN is a mandatory field for GST Transactions

======================================================================
ERROR: test_update_child_with_tax_template (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
Test Action: Create a PO with one item having its tax account head already in the PO.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 328, in test_update_child_with_tax_template
    ).insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item_tax_template.py", line 11, in validate
    validate_zero_tax_options(doc)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item_tax_template.py", line 21, in validate_zero_tax_options
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: GST Rate cannot be zero for Taxable GST Treatment

======================================================================
ERROR: test_update_items_for_subcontracting_purchase_order (erpnext.buying.doctype.purchase_order.test_purchase_order.TestPurchaseOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/test_purchase_order.py", line 1019, in test_update_items_for_subcontracting_purchase_order
    make_subcontracted_items()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/controllers/tests/test_subcontracting_controller.py", line 1241, in make_subcontracted_items
    make_item(item, properties)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 73, in make_item
    item.insert()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1318, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 10, in validate
    validate_hsn_code(doc)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 30, in validate_hsn_code
    _validate_hsn_code(doc.gst_hsn_code)
  File "/home/rahul/postgres_frappe/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py", line 58, in validate_hsn_code
    frappe.throw(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/rahul/postgres_frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code.

----------------------------------------------------------------------
Ran 48 tests in 51.074s

FAILED (errors=7)
```

**Comment by aasif-patel** [comment]
`frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code. `this error occurs because India Compliance adds an custom field on Item Table which is mandatory, and this is not handled in standard Test Cases

**Comment by aasif-patel** [comment]
@rahulgupta8848 Please test this issue

**Comment by rahulgupta8848** [comment]
solved
