### ISSUE TITLE
Manufacturing > Production Plan > Item Child Table

### ISSUE THREAD

**Issue by arvind8848** [8848digital/erpnext#94]
### Information about bug

After adding item on the child table system is showing error.
![Screenshot 2024-09-30 133504](https://github.com/user-attachments/assets/c884b823-d682-4de4-8d96-01a60c7b67fb)

### Module

manufacturing

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Production Plan/new-production-plan-fyqzxshndt
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 1687, in get_item_data
    item_details = get_item_details(item_code)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1220, in get_item_details
    res = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "0000-00-00"
LINE 5:    and (end_of_life is null or end_of_life='0000-00-00' or e...
                                                   ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "_Test FG Item 2"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.manufacturing.doctype.production_plan.production_plan.get_item_data",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "DatetimeFieldOverflow",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ndate/time field value out of range: \\\"0000-00-00\\\"\\nLINE 5:    and (end_of_life is null or end_of_life='0000-00-00' or e...\\n                                                   ^\\n\"]"
}
```
```

**Comment by Amandeep8848** [comment]
PR : https://github.com/8848digital/erpnext/pull/109

**Comment by aasif-patel** [comment]
Resolved hence closing...
