### ISSUE TITLE
Asset - After Submission of Asset Maintenance showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#97]
### Information about bug

![image](https://github.com/user-attachments/assets/ce6edf6f-7763-4e19-842f-a221218d9c74)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Asset Maintenance/ACC-ASS-2024-00002
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/assets/doctype/asset_maintenance/asset_maintenance.py", line 174, in get_maintenance_log
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabAsset Maintenance Log.asset_name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...t maintenance_status, count(asset_name) as count, asset_name
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"asset_name": "ACC-ASS-2024-00001"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.assets.doctype.asset_maintenance.asset_maintenance.get_maintenance_log",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"tabAsset Maintenance Log.asset_name\\\" must appear in the GROUP BY clause or be used in an aggregate function\\nLINE 1: ...t maintenance_status, count(asset_name) as count, asset_name\\n                                                             ^\\n\"]"
}
```
```

**Comment by Prateek8848** [comment]
PR on Asset maintain issues.
https://github.com/8848digital/erpnext/commit/13148e3cc0b360debb64536d2a98d8a68dec2c1c

**Comment by aasif-patel** [comment]
Resolved hence closing...
